### ISSUE TITLE
Essentials PEX Permissions

### ISSUE THREAD

**Issue by Adubbz** [keepcalm/BukkitForge#103]
When trying to run commands to do with essentials that i have given permissions for, it seems to think i don't have permission. I'm using PEX and your port of essentials. When running it in debug mode it gives no extra information except 

2013-01-04 12:30:56 [WARNING] [Minecraft] [PermissionsEx] Debug mode enabled
2013-01-04 12:31:00 [WARNING] [Minecraft] ºcAdubbz º4was denied access to command.

I'm pretty sure it's not an error on my part as these configs worked on my bukkit server previously but just incase i posted them. It seems the admin rank which has the '*' permission can't use them either unless they are opped:

PEX Permissions file:

http://pastebin.com/cqrrGLy9

Essentials config:

http://pastebin.com/Rp3QwF8B

I only have this issue with essentials, not any other plugins

**Comment by Erycus** [comment]
PermissionsEx has always been a little weird (and the coding is a nightmare, or so I'm told).  I had the same issue in 1.2.5 with PEX and I just went ahead and OPed myself making sure I was also set to admin group in the config files of PEX

**Comment by Adubbz** [comment]
Opping does indeed seem to be the workaround for it however it is annoying not having it working with essentials considering that is the main reason you'd want permissions anyway. I _think_ it is a bug with the essentials port rather than BukkitForge itself but i could be wrong

**Comment by keepcalm** [comment]
I have a temp fix, and it is: (drumroll :P) use GroupManager! It's working a lot better.

**Comment by Adubbz** [comment]
If it comes down to it i suppose i'll have to but my personal preference is PEX :S

**Comment by Adubbz** [comment]
No such luck with the latest build, glad your working on it though :)

**Comment by HaoSs07** [comment]
used GroupManager. tried pex. trowed the PC on the window and went back to GroupManager

**Comment by Adubbz** [comment]
It comes down to personal preference. However, it would be good if anyone could use any perms plugin they wish without any dramas

**Comment by keepcalm** [comment]
Yes, I'm working on this...

**Comment by Adubbz** [comment]
Thanks for your work so far on the matter, unfortunately, the same issue with Essentials is present using Build 68 and your custom PEX

**Comment by SpoonsJTD** [comment]
Closed as dupe - permissions issue.
