### ISSUE TITLE
 A plugin is trying to access a world

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#106]
03.01 21:09:24 [Server] WARNING A plugin is trying to access a world without specifying its name correctly! You need to remove configs from build 44 and older
03.01 21:09:24 [Server] WARNING A plugin is trying to access a world without specifying its name correctly! You need to remove configs from build 44 and older
03.01 21:09:24 [Server] WARNING A plugin is trying to access a world without specifying its name correctly! You need to remove configs from build 44 and older
03.01 21:09:24 [Server] WARNING A plugin is trying to access a world without specifying its name correctly! You need to remove configs from build 44 and older
03.01 21:09:24 [Server] WARNING A plugin is trying to access a world without specifying its name correctly! You need to remove configs from build 44 and older
03.01 21:09:24 [Server] WARNING A plugin is trying to access a world without specifying its name correctly! You need to remove configs from build 44 and older

I deleted all plugin configs, still spams it.

**Comment by TempestCraft** [comment]
Reset all of your config files for BukkitForge is my only guess.

**Comment by Erycus** [comment]
I can confirm what killerbees is saying, using a fresh folder.

**Comment by Erycus** [comment]
although it's APPEARING that it is happening when I place a block the message happens
It also seems to be occurring on chunk generation.

**Comment by xKillerbees** [comment]
I don't even log in and it spams it.

**Comment by keepcalm** [comment]
Using the latest build?

**Comment by xKillerbees** [comment]
Build 48. I always use the latest build before I report.

**Comment by keepcalm** [comment]
which plugins are you using?

**Comment by xKillerbees** [comment]
Worldedit
Essentials
Essentialsspawn
Logblock
Questioner
Towny
TownyChat
Vault
Voxelsniper

**Comment by keepcalm** [comment]
I have the exact same plugins installed in my dev environment and it doesn't happen to me... I might've fixed something. Can you reset your configs and update to the build that's about to build?

**Comment by xKillerbees** [comment]
It no longer spams it with 50.
