### ISSUE TITLE
server not loading

### ISSUE THREAD

**Issue by delsolsi213** [keepcalm/BukkitForge#107]
im having issues, i have a clean installation ofr the ftb mindcrack modpack  and everytime i start the server i get this errors, im using the latest forge and latest bukkitforge as of now {48} 

03.01 23:28:31 [Multicraft] Server stopped
03.01 23:28:31 [Multicraft] Looks like a crash, check the server console. Return value: 143
03.01 23:28:31 [Multicraft] Server shut down
03.01 23:28:30 [Server] INFO Stopping server
03.01 23:28:30 [Multicraft] Terminating server via signal
03.01 23:28:22 [Multicraft] Received stop command
03.01 23:28:22 [Multicraft] Received stop command
03.01 23:28:22 [Multicraft] Received stop command
03.01 23:28:22 [Multicraft] Received stop command
03.01 23:28:21 [Multicraft] Received stop command
03.01 23:28:21 [Multicraft] Received stop command
03.01 23:28:21 [Multicraft] Received stop command
03.01 23:28:21 [Multicraft] Received stop command
03.01 23:28:21 [Multicraft] Received stop command
03.01 23:28:20 [Multicraft] Received stop command
03.01 23:28:20 [Multicraft] Received stop command
03.01 23:28:20 [Multicraft] Received stop command
03.01 23:28:20 [Server] INFO at fy.run(SourceFile:849)
03.01 23:28:20 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:540)
03.01 23:28:20 [Server] INFO at ho.a(DedicatedServer.java:236)
03.01 23:28:20 [Server] INFO at ho.al(DedicatedServer.java:309)
03.01 23:28:20 [Server] INFO at x.a(CommandHandler.java:82)
03.01 23:28:20 [Server] INFO at hk.b(SourceFile:18)
03.01 23:28:20 [Server] INFO at w.a(SourceFile:187)
03.01 23:28:20 [Server] INFO at w.a(SourceFile:192)
03.01 23:28:20 [Server] INFO at hi.a(SourceFile:67)
03.01 23:28:20 [Server] INFO java.lang.NullPointerException
03.01 23:28:20 [Server] INFO An unknown error occurred while attempting to perform this command
03.01 23:28:20 [Server] INFO at fy.run(SourceFile:849)
03.01 23:28:20 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:540)
03.01 23:28:20 [Server] INFO at ho.a(DedicatedServer.java:236)
03.01 23:28:20 [Server] INFO at ho.al(DedicatedServer.java:309)
03.01 23:28:20 [Server] INFO at x.a(CommandHandler.java:82)
03.01 23:28:20 [Server] INFO at hf.b(SourceFile:29)
03.01 23:28:20 [Server] INFO java.lang.NullPointerException
03.01 23:28:20 [Server] INFO An unknown error occurred while attempting to perform this command
03.01 23:28:20 [Server] INFO Saving...
03.01 23:28:20 [Multicraft] Skipped 153 lines due to rate limit (30/s)
03.01 23:28:20 [Multicraft] Stopping server!
03.01 23:28:20 [Multicraft] Received stop command
03.01 23:27:39 [Server] INFO RedPowerMachine [RP Machine](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO RedPowerBase [RP Base](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO RedPowerCore [RedPower](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO Railcraft [Railcraft](Railcraft_1.4.6-6.12.2.0.zip) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO Forestry [Forestry for Minecraft](forestry-A-1.6.4.1.jar) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO BuildCraft|Factory [BC Factory](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO BuildCraft|Energy [BC Energy](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO BuildCraft|Builders [BC Builders](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO BuildCraft|Core [BuildCraft](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO factorization [Factorization](Factorization-0.7.10.jar) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO ExtrabiomesXL [ExtrabiomesXL](ExtrabiomesXL-universal-1.4.6-3.7.0.jar) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO EnderStorage [EnderStorage](EnderStorage 1.3.1.1.jar) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO CCTurtle [ComputerCraft Turtles](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO ComputerCraft [ComputerCraft](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO ChickenChunks [ChickenChunks](ChickenChunks 1.2.1.1.jar) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO AdvancedMachines [IC2 Advanced Machines Addon](AdvancedMachines_4.7a.zip) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO IC2 [IndustrialCraft 2](industrialcraft-2_1.112.170-lf.jar) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO powertools_chunkprotection [Chunk Protection](1.4.6_chunkprotection_0.1.1 %281%29.zip) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO powertools_shared [Power Tools Shared](1.4.6_power_tools_shared_0.1.1 %281%29.zip) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO BukkitForge [BukkitForge](BukkitForge-1.4.6-44.jar) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO BlockBreak [Block Break Event](BukkitForge-1.4.6-44.jar) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO mod_NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO mod_CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] INFO mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
03.01 23:27:39 [Server] SEVERE Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
03.01 23:27:39 [Server] INFO [1.4.6v2] Loading properties.
03.01 23:27:39 [Server] INFO Config loaded from: /config/ObsidiPlates.cfg
03.01 23:27:39 [Server] INFO /config/forestry/extrabees/machines.conf
03.01 23:27:39 [Server] INFO /config/forestry/extrabees/main.conf
03.01 23:27:38 [Server] INFO Starting Traincraft 3.1.13_010!
03.01 23:27:38 [Server] INFO [ModularForceFieldSystem] Module not loaded: EE3 not found
03.01 23:27:38 [Server] INFO [ModularForceFieldSystem] Loading module for EE3
03.01 23:27:38 [Server] INFO [ModularForceFieldSystem] Loading module for Buildcraft
03.01 23:27:38 [Server] INFO [ModularForceFieldSystem] Module not loaded: Universal Electricity not found
03.01 23:27:38 [Server] INFO [ModularForceFieldSystem] Loading module for Universal Electricity
03.01 23:27:38 [Server] INFO [ModularForceFieldSystem] Loading module for IC2
03.01 23:27:38 [Multicraft] Skipped 9 lines due to rate limit (30/s)
03.01 23:27:38 [Server] INFO Fluid registration: Liquid Green Dye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid BrownDye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid Brown Dye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid BlueDye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid Blue Dye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid PurpleDye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid Purple Dye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid CyanDye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid Cyan Dye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid Light GrayDye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid Light Gray Dye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid GrayDye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid Gray Dye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid PinkDye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid Pink Dye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid Lime GreenDye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid Lime Green Dye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid YellowDye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid Yellow Dye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid Light BlueDye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid Light Blue Dye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid MagentaDye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid Magenta Dye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid OrangeDye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid Orange Dye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid WhiteDye
03.01 23:27:38 [Server] INFO Fluid registration: Liquid White Dye
03.01 23:27:38 [Server] INFO Initializing Expansion: XyCraft World
03.01 23:27:38 [Server] INFO Initializing Expansion: XyCraft Core
03.01 23:27:37 [Server] WARNING Forestry: Using outdated version [1.6.4.1 (build:77)] for Minecraft 1.4.6. Consider updating.
03.01 23:27:36 [Server] INFO http://www.mod-buildcraft.com
03.01 23:27:36 [Server] INFO Copyright (c) SpaceToad, 2011
03.01 23:27:36 [Server] INFO Starting BuildCraft 3.3.0 (:10)
03.01 23:27:35 [Server] INFO Module AMICA is enabled.
03.01 23:27:35 [Server] INFO Module FABRICA is enabled.
03.01 23:27:35 [Server] INFO Module CAUTIA is enabled.
03.01 23:27:34 [Server] INFO Found ISTORE at index 6, inserting code afterwards...
03.01 23:27:34 [Server] INFO Found target method: s(I)V! Inserting call...
03.01 23:27:34 [Server] INFO Transforming EntitySheep...
03.01 23:27:34 [Server] INFO Config loaded from /./config/IC2.cfg
03.01 23:27:34 [Server] INFO Set UUID to 1357175380378-1817332964-1.4.6

**Comment by Erycus** [comment]
you're going to need more than this, not just multicraft's output.  look for server.log via ftp and find the values starting at 03.01 23:28:31

**Comment by delsolsi213** [comment]
lol i forgotten about that XD , it seems like i had 1 mod conflicting
