### ISSUE TITLE
Esstentials Chat No 2

### ISSUE THREAD

**Issue by Thornas88** [keepcalm/BukkitForge#108]
no fixed the vanilla chat is under the essentials chat and when i run the command /nick und give me a name bugs the chat and the chat range no work

**Comment by keepcalm** [comment]
Try 50?

**Comment by Kristallflamme** [comment]
what is 50 o.o

**Comment by Repooc** [comment]
http://build.aegisgaming.org/job/BukkitForge/50/  This is the revision 50 he is talking about.

**Comment by Thornas88** [comment]
my server runs und the chat plugin, but after 6 players works the chat not for the 7,8,9 other more players...

what is wrong? after the disconnect from players works the chat not for the player. The chat is empty, but the others player can hear him.

**Comment by Thornas88** [comment]
push
