### ISSUE TITLE
Spawn & Home Commands

### ISSUE THREAD

**Issue by Repooc** [keepcalm/BukkitForge#109]
It appears when doing /home (homename) or /spawn while in the nether it takes you to the coords in the nether that those are set to instead of bringing you to the desire locations.  I have not tested other teleportation commands but those are for certain the ones I have tested on a test server of mine.
Running FTB Mindcrack (v6) Minecraft 1.4.6
and Essentials located https://github.com/keepcalm/BukkitForge/tree/master/dist/plugins
I tried this with new install of Essentials and BukkitForge on a backup of my current world.
Using BukkitForge-1.4.6-50.jar  
No error spam in console

**Comment by keepcalm** [comment]
This _should_ be fixed. I'll try and work it out, though.

**Comment by Repooc** [comment]
To help with debugging I have tested and set a home in the main world and one in the nether.
Here is my userdata minus the timestamps and ipaddress section. This is the lastlocation and 2 homes i set.  base is in the main world and nether is in, well the nether.
lastlocation:
  world: world@0
  x: -298.5
  y: 57.0
  z: 52.5
  yaw: -217.65112
  pitch: 15.300028
afk: true
homes:
  base:
    world: world@0
    x: -298.93477637675704
    y: 60.0
    z: 52.181445315830956
    yaw: 180.74757
    pitch: -2.5501103
  nether:
    world: world@0
    x: -44.530184153339775
    y: 54.875
    z: 11.047121083826273
    yaw: -217.65112
    pitch: 15.300028

**Comment by Erycus** [comment]
can confirm with build 51

**Comment by keepcalm** [comment]
Hmm... Ok, world names aren't working properly...

**Comment by xTsukuyomix** [comment]
still happen on build 73, or i am doing something wrong

**Comment by Repooc** [comment]
Still an issue from what I know.

**Comment by TempestCraft** [comment]
I just removed the commands from essentials on my server and replaced it with a commands mod for forge.

**Comment by Repooc** [comment]
Can you reference what you did, like which mod you used and process of the what u did to remove the commands?  I assume revoke the permissions to use them in groupmanager with permission nodes.

**Comment by TempestCraft** [comment]
Opened notepad++
Opened Essentials.jar in winwar
Opened plugin.yml from the Essentials.jar in notepad++
Found command
  sethome:
    description: Set your home to your current location.
    usage: /<command> [[player:]name]
    aliases: [esethome]
Added "#" infront of each line
Saved plugin.yml
Started server and it worked.

**Comment by Repooc** [comment]
What about the "replaced it with a commands mod for forge." Did you install another mod to handle the commands?

**Comment by TempestCraft** [comment]
yea I used fihgu's command mods

**Comment by Repooc** [comment]
so are you using groupmanager or fih permissions?

**Comment by TempestCraft** [comment]
groupmanager

**Comment by xTsukuyomix** [comment]
i am using the same, but i am not able to disallow /setspawn. tryed - -essentials.setspawn but still work

**Comment by Repooc** [comment]
what temptestcraft and I are doing for work arounds are not simply removing permissions to use spawn... we are modifing essentials to not register the commands so another mod will take over...
In my case i have removed setspawn, spawn, home, sethome, delhome, warp, setwarp, delwarp from essentials functions and let a forge mod take over.... at least til bukkitforge is more stable/plugins more compatible

**Comment by xTsukuyomix** [comment]
thats cool, i did the same, but i cant prevent people from using fihgus /setspawn comand, which is bad, is it there a permission node i could use to stop fihgu setspawn been used? like only admin can set spawn 
found a way.
setspawn with fihgu commands, then re enable /setspawn from essential. and with permission lock it down from been altered by non op players

**Comment by joey19982** [comment]
I'm having this issue too. Players keep getting stuck in worlds with no way out other than for me to edit the config files. Can we get a fix ASAP?

**Comment by SpoonsJTD** [comment]
Dupe - world names issue
