### ISSUE TITLE
[BreakPrevention] Spawn/WorldGuard/Regios Destruction Protection

### ISSUE THREAD

**Issue by Erycus** [keepcalm/BukkitForge#113]
It appears that spawn and the above plugins protections are halfway broken.  I cannot build when I select regions and define them with those plugins or inside spawn I cannot build, but I can dig and destroy any existing blocks within protected areas.  I just can't place new ones.  Also, on destroying a block protected with worldguard it says I don't have perms but the block will still break.  Is this an issue already known and I didn't read about it somewhere?

**Comment by TempestCraft** [comment]
I recommend just making yourself op and just using spawn-protection: in your server.properties file, I set mine to over 200 since my spawn is kinda big

**Comment by Erycus** [comment]
But uh...that's the problem.  Default Spawn protection is having the same behavior .-.
Well, at least the protection on default world loading.  Do you mean a command?

**Comment by shakey2** [comment]
Ops can bypass spawn protection, don't give op to people you don't want touching spawn.

**Comment by keepcalm** [comment]
I just need to implement the canceling of block breaks.

**Comment by soulgriever** [comment]
has this been implemented yet? I notice that residence replaces the broken block but does not stop the actual block break

**Comment by keepcalm** [comment]
Yes, as of the latest builds it is.

**Comment by soulgriever** [comment]
unless you havent pushed it to jenkins yet as of build 68 it is not yet fixed :( ty for all your work though

**Comment by keepcalm** [comment]
AFAIK this is fixed

**Comment by SpoonsJTD** [comment]
Fixed until we hear otherwise. :)
