### ISSUE TITLE
Lockette Also Group Manager: Permissions don't work for some commands

### ISSUE THREAD

**Issue by TempestCraft** [keepcalm/BukkitForge#114]
Lockette: The signs don't accept custom events coming from them such as sign colors.

Ok I have a few plugins that work but the commands only work with ops such as worldedit

I did the permissions correctly since I did not get any yaml errors when using it in a paser.

**Comment by shakey2** [comment]
I'm having a similar issue, in that none of these nodes work with essentials group manager:
essentials.build.break
essentials.build.craft
essentials.build.drop
essentials.build.interact
essentials.build.pickup
essentials.build.place

There is another forge mod(NOT PLUGIN) that allows you to basically do permissions for that stuff but its incompatible with bukkitforge as you can see here: #115

**Comment by SpoonsJTD** [comment]
Closed as dupe - there are issues with permissions.
