### ISSUE TITLE
Towny not handling GM event?

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#116]
For some reason if you arent an operator you can't use any of the main commands of towny. Dont know if this is just my perms configuration or what but i did get a GM event error before , i would paste it here but it was in the testservers old files which are not deleted.  Any1 else experiencing this issue.

The message i get when trying a command like /t new is:
[Towny] Command disabled: using permissions

Recreated it:
03:04:50 CONSOLE: [INFO] You changed MomoNasty group to Owner.
03:04:50 CONSOLE: [SEVERE] Could not pass event GMUserEvent to Towny v0.82.0.0
03:04:50 CONSOLE: [SEVERE] Could not pass event GMUserEvent to Towny v0.82.0.0

**Comment by ayeso** [comment]
I have this exact same issue.

It looks like permissions do not get passed correctly. I tested with Essentials, as well as disabling essentials and using "townys permissions" neither seem to work.

**Comment by SpoonsJTD** [comment]
closing as dupe - permissions issue
