### ISSUE TITLE
World Duplication?

### ISSUE THREAD

**Issue by TempestCraft** [keepcalm/BukkitForge#117]
Today I received a messaged from one of my moderators that my world is messed up when he did /lag since the tps felt low.

Well this is what it says
World "world5@0"
Nether "world5@0"
The End "world5@0"
World "world5@0"

Im using Mindcrack v6

Also my world is only called World5 in the folder, so I have no idea where the "world@0" came from.
![2013-01-05_01 52 40](https://f.cloud.github.com/assets/3172080/44913/c0920b6c-571d-11e2-9502-aaa60a875cc2.png)

**Comment by Repooc** [comment]
I dont see the "world@0" in your pic but it does show World "world5@0" 2 times with different chunks/entities.  I get the same thing.

![MCDup](https://f.cloud.github.com/assets/1479745/44965/ff21bb72-5725-11e2-8c34-01ca83a6c096.jpg)

**Comment by TempestCraft** [comment]
I think I found out the reasoning of this, its because of Twilight forest.
