### ISSUE TITLE
Turtle crashes server

### ISSUE THREAD

**Issue by niklas-heer** [keepcalm/BukkitForge#118]
Here ist the error-log I'm getting:

java.lang.ClassCastException: dan200.turtle.shared.TurtlePlayer cannot be cast to iq
    at keepcalm.mods.bukkit.bukkitAPI.inventory.BukkitInventoryPlayer.<init>(BukkitInventoryPlayer.java:21)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntityHuman.<init>(BukkitEntityHuman.java:57)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntity.getEntity(BukkitEntity.java:104)
    at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.getBukkitEntity(BukkitEventFactory.java:102)
    at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callEntityDamageEvent(BukkitEventFactory.java:409)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingDamage(ForgeEventHandler.java:210)
    at net.minecraftforge.event.ASMEventHandler_106_ForgeEventHandler_onLivingDamage_LivingHurtEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:348)
    at md.d(EntityLiving.java:1209)
    at md.a(EntityLiving.java:1045)
    at qj.a(SourceFile:45)
    at dan200.turtle.shared.TileEntityTurtle.useStack(TileEntityTurtle.java:1884)
    at dan200.turtle.shared.TileEntityTurtle.attackWithItemStack(TileEntityTurtle.java:488)
    at dan200.turtle.shared.TurtleTool.attack(TurtleTool.java:127)
    at dan200.turtle.shared.TurtleTool.useTool(TurtleTool.java:112)
    at dan200.turtle.shared.TileEntityTurtle.useTool(TileEntityTurtle.java:1547)
    at dan200.turtle.shared.TileEntityTurtle.attack(TileEntityTurtle.java:1540)
    at dan200.turtle.shared.TileEntityTurtle.updateCommands(TileEntityTurtle.java:2551)
    at dan200.turtle.shared.TileEntityTurtle.g(TileEntityTurtle.java:2373)
    at yc.h(World.java:2155)
    at in.h(WorldServer.java:516)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at keepcalm.mods.bukkit.bukkitAPI.inventory.BukkitInventoryPlayer.<init>(BukkitInventoryPlayer.java:21)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntityHuman.<init>(BukkitEntityHuman.java:57)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntity.getEntity(BukkitEntity.java:104)
    at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.getBukkitEntity(BukkitEventFactory.java:102)
    at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callEntityDamageEvent(BukkitEventFactory.java:409)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingDamage(ForgeEventHandler.java:210)
    at net.minecraftforge.event.ASMEventHandler_106_ForgeEventHandler_onLivingDamage_LivingHurtEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:348)
    at md.d(EntityLiving.java:1209)
    at md.a(EntityLiving.java:1045)
    at qj.a(SourceFile:45)
    at dan200.turtle.shared.TileEntityTurtle.useStack(TileEntityTurtle.java:1884)
    at dan200.turtle.shared.TileEntityTurtle.attackWithItemStack(TileEntityTurtle.java:488)
    at dan200.turtle.shared.TurtleTool.attack(TurtleTool.java:127)
    at dan200.turtle.shared.TurtleTool.useTool(TurtleTool.java:112)
    at dan200.turtle.shared.TileEntityTurtle.useTool(TileEntityTurtle.java:1547)
    at dan200.turtle.shared.TileEntityTurtle.attack(TileEntityTurtle.java:1540)
    at dan200.turtle.shared.TileEntityTurtle.updateCommands(TileEntityTurtle.java:2551)
    at dan200.turtle.shared.TileEntityTurtle.g(TileEntityTurtle.java:2373)

-- Tile entity being ticked --
Details:
    Name: turtle // dan200.turtle.shared.RedPowerTileEntityTurtle
    Block type: ID #0
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-733,62,695), Chunk: (at 3,3,7 in -46,43; contains blocks -736,0,688 to -721,255,703), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
Stacktrace:
    at yc.h(World.java:2155)
    at in.h(WorldServer.java:516)

-- Affected level --
Details:
    Level name: RedBlock-FTA
    All players: 2 total; [iq['Eranuum'/4787, l='RedBlock-FTA', x=-752.07, y=93.17, z=701.52], iq['skat_koch'/191461, l='RedBlock-FTA', x=-575.16, y=49.00, z=862.67]]
    Chunk stats: ServerChunkCache: 1036 Drop: 0
    Level seed: 924047443525819175
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-164,71,628), Chunk: (at 12,4,4 in -11,39; contains blocks -176,0,624 to -161,255,639), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
    Level time: 118100 game time, 192645 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 32650 (now: false), thunder time: 12131 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

-- System Details --
Details:
    Minecraft Version: 1.4.6
    Operating System: Linux (amd64) version 3.2.0-24-generic
    Java Version: 1.7.0_07, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 443563960 bytes (423 MB) / 2126446592 bytes (2027 MB) up to 3817799680 bytes (3640 MB)
    JVM Flags: 2 total; -Xms2048M -Xmx4G
    AABB Pool Size: 7064 (395584 bytes; 0 MB) allocated, 6802 (380912 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    FML: MCP v7.25 FML v4.6.17.515 Minecraft Forge 6.5.0.489 58 mods loaded, 58 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BlockBreak [Block Break Event](BukkitForge-1.4.6-50.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge [BukkitForge](BukkitForge-1.4.6-50.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2 [IndustrialCraft 2](industrialcraft-2_1.112.170-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    AdvancedMachines [IC2 Advanced Machines Addon](AdvancedMachines_4.7a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ChickenChunks [ChickenChunks](ChickenChunks 1.2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ComputerCraft [ComputerCraft](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CCTurtle [ComputerCraft Turtles](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    EnderStorage [EnderStorage](EnderStorage 1.3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ExtrabiomesXL [ExtrabiomesXL](ExtrabiomesXL-universal-1.4.6-3.7.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    factorization [Factorization](Factorization-0.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Core [BuildCraft](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Builders [BC Builders](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Energy [BC Energy](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Factory [BC Factory](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forestry [Forestry for Minecraft](forestry-A-1.6.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Railcraft [Railcraft](Railcraft_1.4.6-6.12.2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCore [RedPower](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerBase [RP Base](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerMachine [RP Machine](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCompat [RP Compat](RedPowerCompat-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWiring [RP Wiring](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLogic [RP Logic](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLighting [RP Lighting](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWorld [RP World](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerControl [RP Control](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion [Thermal Expansion](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Factory [Factory](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Energy [Energy](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Transport [Transport](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Transport [BC Transport](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Silicon [BC Silicon](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    TwilightForest [The Twilight Forest](twilightforest-1.14.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    XyCraft [XyCraft](xycraft-universal-1.4.6-0.9.44.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    GregTech_Addon [GregTech-Addon](GregTechMod_2.73c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2NuclearControl [Nuclear Control](IC2NuclearControl-1.4.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ModularForceFieldSystem [Modular ForceField System V2](ModularForceFieldSystemV2.2.8.2.14.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    OmniTools [OmniTools](OmniTools-2.2.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    SoulShards [SoulShards](SoulShards-v1.21-universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    StevesCarts [Steve's Carts](StevesCarts2.0.0.a41.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Thaumcraft [Thaumcraft](Thaumcraft3.0.1c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    TC [Traincraft](Traincraft-3.1.13_010.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|Core [WR-CBE Core](WR-CBE Core 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|Addons [WR-CBE Addons](WR-CBE Addons 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|RedPower [WR-CBE RedPower](WR-CBE RedPower 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    drceph.petrogen [Petroleum Generator]([1.4.6]PetroGen-1.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BinnieCore [Binnie Core](extrabees-1.4.9.6-prerelease.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ExtraBees [Extra Bees](extrabees-1.4.9.6-prerelease.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IronChest [Iron Chest](ironchest-universal-1.4.6-4.5.1.203.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    MiscPeripherals [MiscPeripherals](miscperipherals-2.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    AdvancedSolarPanel [Advanced Solar Panels](mod_AdvancedSolarPanels_3_3_2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    GraviSuite [Gravitation Suite](mod_zGraviSuite_1_6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ObsidiPlates [Obsidian Pressure Plates](obsidiplates-universal-1.2.0.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PortalGun [Portal Gun](portalgun1.4.6v2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge Details: 1.4.6 (Bukkit API version 1.4.5-R0.2)
Plugins Loaded:org.anjocaido.groupmanager.GroupManager(GroupManager v${GMVer} (${build.number}) (Phoenix): Enabled), com.sk89q.worldedit.bukkit.WorldEditPlugin(WorldEdit v5.4.5: Enabled), net.anticreeper.Anticreeper(AntiCreeper3 v4.5: Enabled), com.nijikokun.bukkit.Permissions.Permissions(Permissions v3.1.6: Enabled), com.earth2me.essentials.Essentials(Essentials v${build.number}: Enabled), com.earth2me.essentials.xmpp.EssentialsXMPP(EssentialsXMPP v${build.number}: Enabled), com.earth2me.essentials.chat.EssentialsChat(EssentialsChat v${build.number}: Enabled), com.earth2me.essentials.protect.EssentialsProtect(EssentialsProtect v${build.number}: Enabled), com.earth2me.essentials.antibuild.EssentialsAntiBuild(EssentialsAntiBuild v${build.number}: Enabled), com.earth2me.essentials.spawn.EssentialsSpawn(EssentialsSpawn v${build.number}: Enabled) and com.earth2me.essentials.geoip.EssentialsGeoIP(EssentialsGeoIP v${build.number}: Enabled)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 2481 (138936 bytes; 0 MB) allocated, 1986 (111216 bytes; 0 MB) used
    Player Count: 2 / 25; [iq['Eranuum'/4787, l='RedBlock-FTA', x=-752.07, y=93.17, z=701.52], iq['skat_koch'/191461, l='RedBlock-FTA', x=-575.16, y=49.00, z=862.67]]
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)

**Comment by Maximuscr31** [comment]
I am having the exact same issue. I am using build 53
