### ISSUE TITLE
Thread priorities not handled correctly in worldguard?

### ISSUE THREAD

**Issue by clienthax** [keepcalm/BukkitForge#119]
In worldguard, it is possible to break blocks in a protected area

com.sk89q.worldguard.bukkit.WorldGuardBlockListener

```
@EventHandler(priority = EventPriority.HIGH, ignoreCancelled = true)
public void onBlockBreak(BlockBreakEvent event) {
```

if we put the event.setCancelled(true) right at the start of this it works fine
however once its called by the if block with the conditionals met, it will not work properly and allows the user to break blocks in a protected area
this does not happen with placing blocks

**Comment by keepcalm** [comment]
Fixed!
