### ISSUE TITLE
BukkitForge and DragonMounts

### ISSUE THREAD

**Issue by futhermukker** [keepcalm/BukkitForge#122]
I just installed DragonMounts plugin can be found here: http://www.minecraftforum.net/topic/827863-146-dragon-mounts-091-wip/  I started a new map and the first thing I tried was to spawn an enderdragon. Withouth Bukkitforge I can spawn dragons with ease, but with Bukkitforge I get this error in my server log and the game stops working. here is a link to the server log: http://dl.dropbox.com/u/95441499/server.log

Also if I take out Bukkitforge, start a map, spawn a dragon, exit  game, put Bukkitforge back in, start the game, try to load map. Bukkit forge errors will not let the map load. I must trash that map and start a new one.

Let me know if you need anymore information. Should be pretty easy to dupe. As I tried it 5 times with the same result.

Thank you.

**Comment by keepcalm** [comment]
I fixed that, update to latest build.

**Comment by futhermukker** [comment]
ok, sorry I did not know that. thank you I will update now.
