### ISSUE TITLE
WorldEdit Wand Issue

### ISSUE THREAD

**Issue by Kiokimaru** [keepcalm/BukkitForge#128]
I don't know exactly what specific information would help but when I use //wand and I teleport to some one on my server I can no longer set regions using the wand only a map reset seems to fix the issue. I'm only using the WorldEdit supplied by keepcalm and jcommands. I do have redpower, industrialcraft, computercraft, compactsolars, modularforcefield, netherores, thaumcraft 3, balkons weapons mod, ironchests, and mocreatures. The console does not give any errors or anything. I'm using the latest version of all mods listed.

**Comment by Benet** [comment]
It's not BukkitForge issue. Worldedit 5.4.5 is glitched as hell. Only way to solve this problem is fixing 5.4.6 to work with BukkitForge.

**Comment by Kiokimaru** [comment]
Ah. Thanks for the heads up. I wish i knew how to fix it up. Could some one with the knowledge fix it up? Many thanks if you would.

-----Original Message-----

**Comment by keepcalm** [comment]
What? They released 5.4.6?

**Comment by Kiokimaru** [comment]
No sadly just a snapshot. http://www.minecraftforum.net/topic/1597478-worldedit-546-snapshot-and-mc-145-bukkit-server/ I hope this little info helps. It seems that the snapshot is bugged too. I didn't do much just a simple google search.

**Comment by Mceonith** [comment]
I can't get pos to work or wand at all i get a "position set to null" error (with 5.4.5) anyone know?

**Comment by keepcalm** [comment]
Update your build

**Comment by SpoonsJTD** [comment]
Closed as dupe - Wand Issue and WorldEdit breaking after time.
