### ISSUE TITLE
Factions 1.6.9.4 and 1.8 not working

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#130]
Heya another issue you posted that Factions now works without modifications (do you mean no mods installed?). I have vault installed  too as Factions requires that, however i have tried loading factions both 1.6.9.4 and 1.8 and get a severe error:

01:48:39 Factions: Enabling Factions v1.6.9.4
01:48:39 CONSOLE: [SEVERE] [Factions v1.6.9.4] GSON lib not found. Your CraftBukkit build is too old (< 1.3.2) or otherwise not compatible.

in my lib folder i have gson-2.1.jar.
More info: Using the direwolf20 modpack and using MCMA as server wrapper.
Thanks -Momo

**Comment by Adubbz** [comment]
What build of bukkitforge are you using? The change regarding factions is in build 59+

**Comment by ghost** [comment]
im using build 61 (latest)

**Comment by ghost** [comment]
well i tryed changing the name of the lib jar to gson-2.1-cb but that doesnt work either still getting the severe error (still using build 61)
