### ISSUE TITLE
permissions not working?

### ISSUE THREAD

**Issue by Bucky420** [keepcalm/BukkitForge#131]
umm if any one can confirm pex or group manager working  

permissions like -worledit.\* or - '*' are't working

i running this on tekkit lite

**Comment by TempestCraft** [comment]
Pex does not work. Use group manager.

**Comment by ghost** [comment]
Pex is working fine with me, But try using group manager.

**Comment by Benet** [comment]
I can confirm this. I am using build 63. I tried pex, group manager and permissionsbukkit and none of them worked.

**Comment by ghost** [comment]
so far build build 63 and just now 66 i have gotten pex to work much better than groupmanager, thanks to hypno

**Comment by keepcalm** [comment]
OK, try using the PEX jar in the dist/ folder for now. I'm working on integrating BukkitForge support into vanilla PEX.

**Comment by SpoonsJTD** [comment]
Closing as dupe - permissions issue.
