### ISSUE TITLE
Build 63 same issue for GSON

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#133]
Trying to use Factions and i get this errror still.
I now have gson-2.1.jar and gson-2.1-cb.jar in my lib folder

04:37:47 CONSOLE: [SEVERE] [Factions v1.6.9.4] GSON lib not found. Your CraftBukkit build is too old (< 1.3.2) or otherwise not compatible.

Edit: Their might be a memory leak as my testserver i am using the new build and the memory usage has double not sure if true for others but the memory usage was not this high on the previous builds (not sure just stating observation) IGNORE

**Comment by keepcalm** [comment]
delete all the files in your lib folder?

**Comment by ghost** [comment]
deleting files now

**Comment by ghost** [comment]
Deleted lib folder and now have this error instead
The only gson now in the lib folder is gson-2.1-cb.jar

04:44:37 CONSOLE: [SEVERE] [Factions v1.6.9.4] GSON lib not found. Your CraftBukkit build is too old (< 1.3.2) or otherwise not compatible.

**Comment by ghost** [comment]
ignore issue about memory leak just me being dumb :P

**Comment by keepcalm** [comment]
Whoops... I screwed up. Sorry!

**Comment by ghost** [comment]
lol np im patient :D
