### ISSUE TITLE
[Notifications] Posted Double

### ISSUE THREAD

**Issue by Repooc** [keepcalm/BukkitForge#136]
Using the notifications from your Essentials port, User placed 2 buckets of lava and got message 2 times for each.  Screenshot for the example.
![Double Post](https://f.cloud.github.com/assets/1479745/46156/034e5eda-582a-11e2-99ca-3cf017e0aa96.jpg)

**Comment by SpoonsJTD** [comment]
No more Essentials port -- if you get this with actual Essentials plug-in, please create new issue.
