### ISSUE TITLE
mod block logging build 63

### ISSUE THREAD

**Issue by shakey2** [keepcalm/BukkitForge#137]
While Logblock is now able to log basalt(is metadamage block) where it couldn't before it does not log the metadamage number with the block so it only shows the base ID number. Also almost all the other mod blocks are still not logged including some Redpower 2 machines.

**Comment by shakey2** [comment]
I will love you to death if you can get mod block destruction/place events to work. This is the only thing holding me back from taking my server public :(

You have all my gratitude for working on this mod, you are a godsend to forge server owners!

**Comment by SpoonsJTD** [comment]
Closed as dupe, another LogBlock issue already exists.
