### ISSUE TITLE
Mcbans

### ISSUE THREAD

**Issue by HypnoTherapist** [keepcalm/BukkitForge#141]
Mcbans enables. When I run a /lookup command it doesnt Show up, i turned on debugging in mcbans., It shows me as having run that command. If i ban someone it doesn't show up. i DID put in the correct API key.
GREAT Mod though I have Commandbook and PermissionsEX  and MChat running without a problem!

**Comment by ghost** [comment]
woah u have pex running correctly? i saw that command book was running nicely would u say to use it over essentials?

**Comment by HypnoTherapist** [comment]
in a heartbeat.

**Comment by ghost** [comment]
sweet i should have just sticked with it essentials just packages too many things together some i know im not gonna use. Also for pex which version are u using? and are u using all 3 jars chatmanager modifyworld and pex or just the pex jar and mchat for chat?

**Comment by HypnoTherapist** [comment]
i use modifyWorld pEx and mchat

**Comment by Repooc** [comment]
Hate to high jack this issue, but HypnoTherapist, do you mind linking/giving versions of those plugins you are using? I see mchat on bukkit.org says it requires vault and you didnt state you use that.

**Comment by HypnoTherapist** [comment]
Mchat is the latest from their Bukkitddev page, The same for Vault. command book and PEX are both the latest compatible for 1.4.6 and I actually am NOT running modify world at this time.

**Comment by Repooc** [comment]
Ok I found the ones I think you are referring to.  Just to clarify version numbers on 2 of them... For mchat, there is 4 releases for Nov 14, so is it safe to think you got the one named MChat b287 (Game Version CB 1.3.2-R3.0) and the command book, there are 2 for released Nov 13, CommandBook 2.2/CommandBook 2.2(Jar only) (Game Version CB 1.4.2-R0.2CB 1.3.2-R3.0CB 1.2.5-R5.0)

**Comment by HypnoTherapist** [comment]
Update: Modifyworld is working Great and my commandbook is 2.1, pex is  v1.19.5, Vault is  1.2.22-b277

**Comment by Repooc** [comment]
Sorry I asked about mchat, and thank you for the info thus far. is 2.2 command book not working?

**Comment by HypnoTherapist** [comment]
No problem glad to Help. Still have ZERO output from mcbans, which is weird. however in its own debug area it shows me as running those commands.BUT they don't actually do anything. IE: bans don't go through.

**Comment by ghost** [comment]
hypno hey man thnks for the suggestions for the last 5 hours since u told me pex and all that worked i installed and setup everything. Got the right versions of each luckily after hit and miss. However u said u have modifyworld working correctly? its the only one i cant see to get working, i have permissions nodes given to all groups modifyworld.\* but cant break blocks anywhere even super far from spawn, could you tell me how u got it to work? thnks man for all the info and help

edit: my permissions yml
http://puu.sh/1KGAc

**Comment by HypnoTherapist** [comment]
well to be honest i installed it and it DID prevent my guinea pig player from building however after posting that i realized that I could build and he couldnt even when give build perms. I realized it was only follwing OP permissions. SO Modify world is still unconfirmed

**Comment by Repooc** [comment]
I cant get the modifyworld.\* to work either.

**Comment by Repooc** [comment]
Hypno, have you successfully got permissions to work for plugins without being op'd?  I cant seem to get it to work correctly.
If so, what have you done as my permissions, I cant even check lag as permission is denied but I can if I am op'd
http://pastebin.com/KUKeXC9U
Example of permissions.  I do not have modify world installed so I dont have modifyworld.\* in as I couldnt get that to work either.  I have tried both the pex here and the on on bukkit

**Comment by HypnoTherapist** [comment]
Well your paste only has perms for the owner group with one of them being *.  Test out pex with a default group. Also I just noticed keepkalm did a Pex build. I haven't tried it out yet.

**Comment by SpoonsJTD** [comment]
Closed as dupe - another permissions issue.
