### ISSUE TITLE
LogBlock CommandsHandler/PlayerInteractEvent

### ISSUE THREAD

**Issue by Chasgasm** [keepcalm/BukkitForge#143]
When I use /lb tool I receive this error: http://pastebin.com/XZ6AxaiF
I still receive the tool, however, when I try to right-click on a block with it to see who has edited it I receive these errors: http://pastebin.com/0wGZRZ72

Everything else with logblock seems to work fine at the moment.

**Comment by SpoonsJTD** [comment]
Closed as dupe - already have LogBlock issue.
