### ISSUE TITLE
[WorldGuard] BlockBreakEvent

### ISSUE THREAD

**Issue by Chasgasm** [keepcalm/BukkitForge#145]
If a player breaks a block in a protected region it will give them a "No Permissions" message and the block will respawn, but the block item will still drop.

**Comment by delsolsi213** [comment]
yeah this also happens with anyother protection plugin towny/griefprevention etc

**Comment by clienthax** [comment]
Fixed in latest build

**Comment by Chasgasm** [comment]
It's not. The latest build is the one I'm already on.

**Comment by keepcalm** [comment]
Try the latest build.

**Comment by Chasgasm** [comment]
Seems to be fixed with the build from @clienthax located in ticket #155 
Blocks are no longer dropping and players without permissions cannot break blocks in a region made by WorldGuard that they are not added to. :)

**Comment by hitZor** [comment]
It isn't fixed with clienthax's build nor by 73 build. It happens with both WorldGuard and Grief Prevention without any server errors. :/

**Comment by Chasgasm** [comment]
Actually still happening. Woops.

**Comment by SpoonsJTD** [comment]
Please recheck this. Permissions and player events have been worked on.

**Comment by SpoonsJTD** [comment]
Consensus seems to be that this is fixed.
