### ISSUE TITLE
[VoxelSniper] vs range

### ISSUE THREAD

**Issue by voxelhelp** [keepcalm/BukkitForge#146]
Can't get it to work.
I've seen a bug on voxel wiki, linked http://ciscogeek.com/minecraft/Talk:VoxelSniper

"For some reason large parts of the time I cant snipe blocks outside the standard 5 block selection range, and no the range restriction feature is not on. -- DobaCrafter 11:16, 14 April 2012 (CDT)
Quit your minecraft and restart. Should fix it (did for me) -DemonPlaysPro(talk) 11:25, 14 April 2012 (CDT)"

Got problem like this and quitting, restarting server not helps.. Are there a 3rd side mod to fix this issue or something...
Is there only me having this problem?? Can't create brush size 3+ voxel's with 5 block create distance, they just weigh upon me! searching for a noclip plugin and installing it is not solution.

I've never installed VoxelSniper on usual server and i don't know who cases that problem - bukkitforge's voxelsniper edit, or voxelsniper plugin at all.. I don't know how i should run this function.

I am very bad at English, so sorry.

**Comment by Chasgasm** [comment]
This happens as well with /thor from CommandBook. I might be wrong, but I think it's because for the block to be interacted with it needs to be highlighted (outlined) and that doesn't happen when you are more than 5 blocks away from it.

**Comment by voxelhelp** [comment]
Thanks for your answer.
I'm not sure, but there is no outline in voxelsniper youtube videos.. And people can create what they want from any distance.
- i can't replace items with arrow (it's because i'm noob, or because this is port to secondary system management bukkitforge and  this doesn't working well)..
  I can replace things with worldedit (still doesn't know how to install WE Cui into forge) so doesn't matter. I just said about that bug.

Anyway thanks to keepcalm and people who helped him for ability to use such mods on my SMP server without bukkit server management and etc.

I will try to search for commandbook, but as i remember it is for singleplayer gaming.

**Comment by minecrafter** [comment]
By CommandBook, @Chasgasm means the plugin by sk89q.

**Comment by voxelhelp** [comment]
Anyone is using this (CommandBook) to fix my issue?

I ask because of existence of 100 commands which i don't need so installing this mod on my server is too hard, but if I or people here found there's no alternative - i'll try this mod.

**Comment by minecrafter** [comment]
Um, no.

He said that CommandBook also has this issue. Installing it won't help.

**Comment by voxelhelp** [comment]
oh ok, i see now... There were 5 am when i read that, so i was a lil' bit inattentive

**Comment by SpoonsJTD** [comment]
I am having a hard time following this to understand if this is an issue with Bukkitforge or with VoxelSniper?

**Comment by voxelhelp** [comment]
I think it's bukkitforge issue, cuz any plugin with longrange thingy is not working i guess.

CommandBook...
