### ISSUE TITLE
Server Crashed

### ISSUE THREAD

**Issue by Repooc** [keepcalm/BukkitForge#148]
I am not sure if this was exactly due to BukkitForge but I would assume it has something to possibly do with it.

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 1/6/13 11:40 PM
Description: Ticking entity

java.lang.ClassCastException: keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntity cannot be cast to keepcalm.mods.bukkit.bukkitAPI.entity.BukkitLivingEntity
    at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callEntityDeathEvent(BukkitEventFactory.java:346)
    at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callEntityDeathEvent(BukkitEventFactory.java:342)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingDeathEvent(ForgeEventHandler.java:196)
    at net.minecraftforge.event.ASMEventHandler_105_ForgeEventHandler_onLivingDeathEvent_LivingDeathEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:353)
    at md.a(EntityLiving.java:1278)
    at thaumcraft.common.entities.golems.EntityGolemWorker.a(EntityGolemWorker.java:169)
    at md.a(EntityLiving.java:1111)
    at thaumcraft.common.entities.golems.EntityGolemWorker.a(EntityGolemWorker.java:254)
    at thaumcraft.common.blocks.BlockArcaneFurnace.a(BlockArcaneFurnace.java:126)
    at lq.D(Entity.java:1011)
    at lq.d(Entity.java:955)
    at md.e(EntityLiving.java:1535)
    at md.c(EntityLiving.java:1823)
    at thaumcraft.common.entities.golems.EntityGolemWorker.c(EntityGolemWorker.java:129)
    at md.j_(EntityLiving.java:843)
    at yc.a(World.java:2295)
    at in.a(WorldServer.java:647)
    at yc.g(World.java:2257)
    at yc.h(World.java:2103)
    at in.h(WorldServer.java:516)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callEntityDeathEvent(BukkitEventFactory.java:346)
    at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callEntityDeathEvent(BukkitEventFactory.java:342)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingDeathEvent(ForgeEventHandler.java:196)
    at net.minecraftforge.event.ASMEventHandler_105_ForgeEventHandler_onLivingDeathEvent_LivingDeathEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:353)
    at md.a(EntityLiving.java:1278)
    at thaumcraft.common.entities.golems.EntityGolemWorker.a(EntityGolemWorker.java:169)
    at md.a(EntityLiving.java:1111)
    at thaumcraft.common.entities.golems.EntityGolemWorker.a(EntityGolemWorker.java:254)
    at thaumcraft.common.blocks.BlockArcaneFurnace.a(BlockArcaneFurnace.java:126)
    at lq.D(Entity.java:1011)
    at lq.d(Entity.java:955)
    at md.e(EntityLiving.java:1535)
    at md.c(EntityLiving.java:1823)
    at thaumcraft.common.entities.golems.EntityGolemWorker.c(EntityGolemWorker.java:129)
    at md.j_(EntityLiving.java:843)
    at yc.a(World.java:2295)
    at in.a(WorldServer.java:647)
    at yc.g(World.java:2257)

-- Entity being ticked --
Details:
    Entity Type: entGolemStone (thaumcraft.common.entities.golems.EntityGolemStone)
    Entity ID: 246374
    Name: Stone Golem
    Exact location: -943.72, 69.78, 595.35
    Block location: World: (-944,69,595), Chunk: (at 0,4,3 in -59,37; contains blocks -944,0,592 to -929,255,607), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
    Momentum: -0.04, -0.30, -0.01
Stacktrace:
    at yc.h(World.java:2103)
    at in.h(WorldServer.java:516)

-- Affected level --
Details:
    Level name: world
    All players: 4 total; [iq['Superkaze'/1503, l='world', x=-945.45, y=68.00, z=591.29], iq['madenman333'/24719, l='world', x=-155.49, y=60.00, z=-669.34], iq['Cursewordz'/249084, l='world', x=-340.06, y=64.00, z=97.62], iq['Johnny587'/255308, l='world', x=89.27, y=68.00, z=-648.70]]
    Chunk stats: ServerChunkCache: 1364 Drop: 0
    Level seed: 1512012717392234586
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (86,79,-360), Chunk: (at 6,4,8 in 5,-23; contains blocks 80,0,-368 to 95,255,-353), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 6474378 game time, 6589517 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 123109 (now: false), thunder time: 111377 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

-- System Details --
Details:
    Minecraft Version: 1.4.6
    Operating System: Linux (amd64) version 2.6.18-308.8.2.el5.028stab101.1
    Java Version: 1.7.0_09-icedtea, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 295096200 bytes (281 MB) / 585609216 bytes (558 MB) up to 1056309248 bytes (1007 MB)
    JVM Flags: 6 total; -Xincgc -Xmx1G -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=2 -XX:+AggressiveOpts
    AABB Pool Size: 1733 (97048 bytes; 0 MB) allocated, 287 (16072 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 63
    FML: MCP v7.25 FML v4.6.17.515 Minecraft Forge 6.5.0.489 58 mods loaded, 58 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BlockBreak [Block Break Event](BukkitForge-1.4.6-50.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge [BukkitForge](BukkitForge-1.4.6-50.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2 [IndustrialCraft 2](industrialcraft-2_1.112.170-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    AdvancedMachines [IC2 Advanced Machines Addon](AdvancedMachines_4.7a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ChickenChunks [ChickenChunks](ChickenChunks 1.2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ComputerCraft [ComputerCraft](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CCTurtle [ComputerCraft Turtles](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    EnderStorage [EnderStorage](EnderStorage 1.3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ExtrabiomesXL [ExtrabiomesXL](ExtrabiomesXL-universal-1.4.6-3.7.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    factorization [Factorization](Factorization-0.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Core [BuildCraft](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Builders [BC Builders](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Energy [BC Energy](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Factory [BC Factory](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forestry [Forestry for Minecraft](forestry-A-1.6.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Railcraft [Railcraft](Railcraft_1.4.6-6.12.2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCore [RedPower](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerBase [RP Base](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerMachine [RP Machine](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCompat [RP Compat](RedPowerCompat-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWiring [RP Wiring](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLogic [RP Logic](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLighting [RP Lighting](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWorld [RP World](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerControl [RP Control](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion [Thermal Expansion](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Factory [Factory](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Energy [Energy](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Transport [Transport](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Transport [BC Transport](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Silicon [BC Silicon](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    TwilightForest [The Twilight Forest](twilightforest-1.14.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    XyCraft [XyCraft](xycraft-universal-1.4.6-0.9.44.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    GregTech_Addon [GregTech-Addon](GregTechMod_2.73c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2NuclearControl [Nuclear Control](IC2NuclearControl-1.4.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ModularForceFieldSystem [Modular ForceField System V2](ModularForceFieldSystemV2.2.8.2.14.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    OmniTools [OmniTools](OmniTools-2.2.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    SoulShards [SoulShards](SoulShards-v1.21-universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    StevesCarts [Steve's Carts](StevesCarts2.0.0.a41.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Thaumcraft [Thaumcraft](Thaumcraft3.0.1c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    TC [Traincraft](Traincraft-3.1.13_010.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|Core [WR-CBE Core](WR-CBE Core 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|Addons [WR-CBE Addons](WR-CBE Addons 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|RedPower [WR-CBE RedPower](WR-CBE RedPower 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    drceph.petrogen [Petroleum Generator]([1.4.6]PetroGen-1.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BinnieCore [Binnie Core](extrabees-1.4.9.6-prerelease.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ExtraBees [Extra Bees](extrabees-1.4.9.6-prerelease.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IronChest [Iron Chest](ironchest-universal-1.4.6-4.5.1.203.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    MiscPeripherals [MiscPeripherals](miscperipherals-2.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    AdvancedSolarPanel [Advanced Solar Panels](mod_AdvancedSolarPanels_3_3_2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    GraviSuite [Gravitation Suite](mod_zGraviSuite_1_6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ObsidiPlates [Obsidian Pressure Plates](obsidiplates-universal-1.2.0.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PortalGun [Portal Gun](portalgun1.4.6v2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge Details: 1.4.6 (Bukkit API version 1.4.5-R0.2)
Plugins Loaded:org.anjocaido.groupmanager.GroupManager(GroupManager v${GMVer} (${build.number}) (Phoenix): Enabled), com.nijikokun.bukkit.Permissions.Permissions(Permissions v3.1.6: Enabled), com.earth2me.essentials.Essentials(Essentials v${build.number}: Enabled), com.earth2me.essentials.chat.EssentialsChat(EssentialsChat v${build.number}: Enabled), com.earth2me.essentials.protect.EssentialsProtect(EssentialsProtect v${build.number}: Enabled), com.earth2me.essentials.spawn.EssentialsSpawn(EssentialsSpawn v${build.number}: Enabled), com.earth2me.essentials.antibuild.EssentialsAntiBuild(EssentialsAntiBuild v${build.number}: Enabled) and com.earth2me.essentials.geoip.EssentialsGeoIP(EssentialsGeoIP v${build.number}: Enabled)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 637 (35672 bytes; 0 MB) allocated, 36 (2016 bytes; 0 MB) used
    Player Count: 4 / 10; [iq['Superkaze'/1503, l='world', x=-945.45, y=68.00, z=591.29], iq['madenman333'/24719, l='world', x=-155.49, y=60.00, z=-669.34], iq['Cursewordz'/249084, l='world', x=-340.06, y=64.00, z=97.62], iq['Johnny587'/255308, l='world', x=89.27, y=68.00, z=-648.70]]
    Is Modded: Definitely; Server brand changed to 'fml'

**Comment by Erycus** [comment]
I believe that bukkit doesn't want a poor thaumcraft golem to die.
I know that bukkit is using a dummy instance of entity for creatures that are part of mods so that might have something to do with this...
