### ISSUE TITLE
Essentials still thinks players are new after server restart

### ISSUE THREAD

**Issue by clienthax** [keepcalm/BukkitForge#149]
After restarting the server, when a player joins they will be placed at the spawn point

**Comment by Repooc** [comment]
I have had the same issue.

**Comment by delsolsi213** [comment]
i know is not a fix but a way around that, just disable the spawn option for newbies

**Comment by keepcalm** [comment]
Try latest build

**Comment by HaoSs07** [comment]
keepcalm, thx for the fast updates! 

I have a quick question, on last build i tried ( 53 ), i had a start kit in essentials config for new players, and every time someone reloged in to the game, he got the kit over and over again . can't test if this is fixed, as jenkins is down, do you know something about this bug ?

**Comment by keepcalm** [comment]
Yes, I fixed it.
