### ISSUE TITLE
Modifyworld not working with newest build 63+ currently using build 68

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#152]
Currently using the latest build 68 and modifyworld is still not working. Superperms are enabled via pex and this is my permissions.yml 
http://puu.sh/1KHEp

**Comment by ghost** [comment]
yup just switched the jars for pex to the one u uploaded modifyworld.\* doesnt work for the groups i made

**Comment by Chasgasm** [comment]
Same problem here. Can't do anything unless I'm opped even when in a group with '*' permissions.

**Comment by ghost** [comment]
yup only on op any1 can break D:

**Comment by Repooc** [comment]
Actually I can't seem to get pex to set any permissions correctly, used standard Pex and tried one ported.
Plugins installed are commandbook (tried 2.1 and 2.2), clearlagg...
I have added all the groups via console.  Promoted myself through the ranks via console, added the permissions via in game after giving Owner permissions.\* in console.

**Comment by ghost** [comment]
well chatmanager doesnt work but ive gotten mchat to work though :). my permissions are working fine though

**Comment by Repooc** [comment]
Can you share permissions file so I can compare mine?  Have you been modifying you permissions file via ingame or manually? Don't think it should matter.  I been doing it via in game.

**Comment by ghost** [comment]
Its in the first post

**Comment by SpoonsJTD** [comment]
Closed as dupe - permissions issue.
