### ISSUE TITLE
Possible Pex Issue with some permission nodes.

### ISSUE THREAD

**Issue by Repooc** [keepcalm/BukkitForge#154]
I have installed ClearLagg and by default it seems to function. I op'd myself and can run commands but if I deop myself and let pex handle permissions for it, I get I dont have permissions.
My permission file:
http://pastebin.com/2E2YcHrq

Link to clearlagg permission nodes:
http://dev.bukkit.org/server-mods/clearlagg/

**Comment by Repooc** [comment]
Even using /home that I set in the overworld isnt working correctly, I assume its caused by bukkitforge.  I did a test and set my home in the overworld, went to the nether and tried to do home and it didnt take me to the correct world. just left me in the nether.

**Comment by Repooc** [comment]
Cant seem to get group manager to work with giving permissions to use the command as well.

**Comment by clienthax** [comment]
All permissions plugins are a bit buggy atm, there is a custom build of pex now, want to try it?
https://github.com/keepcalm/BukkitForge/blob/master/dist/plugins/PermissionsEx-BukkitForge.jar

**Comment by Repooc** [comment]
I have tried it forgot to mention that.

**Comment by keepcalm** [comment]
Try with the most recent build, I may have fixed it.

**Comment by SpoonsJTD** [comment]
Closed as dupe - permissions issue.
