### ISSUE TITLE
The jenkins link seems down

### ISSUE THREAD

**Issue by bemk** [keepcalm/BukkitForge#155]
Cloudflare is giving me this exact message on the Jenkins link

Website currently unavailable
The website you are trying to access is currently unavailable. Please try again at a later time.
If you are the site owner, here is a help resource to help resolve the issue.

**Comment by clienthax** [comment]
yep its dead atm, heres the latest build if needed
http://uppit.com/emg58kg3veac/BukkitForge-1.4.7-CUSTOM_BUILD.jar

**Comment by bemk** [comment]
Thanks, I'll do some experimenting with it.

**Comment by keepcalm** [comment]
Thanks clienthax :D
