### ISSUE TITLE
[heal|invsee] heal command gives hook error on filling hunger

### ISSUE THREAD

**Issue by clienthax** [keepcalm/BukkitForge#157]
Error: rp.a(I)V

**Comment by ghost** [comment]
Same here with me trying to use that command and /invsee sometimes works and sometimes doesn't.

**Comment by SpoonsJTD** [comment]
Please re-check. I was able to do both fine.

**Comment by SpoonsJTD** [comment]
Seems fine, please re-open if still broken.
