### ISSUE TITLE
[BroadCaster] Broadcast messages dont work

### ISSUE THREAD

**Issue by clienthax** [keepcalm/BukkitForge#159]
http://dev.bukkit.org/server-mods/adminchat-broadcaster-1-0-broadc/files/4-broadcaster-1-2/

Broadcase messages send from console and plugins dont appear in game

**Comment by TempestCraft** [comment]
Use this plugin http://dev.bukkit.org/server-mods/deckerz-announcer/

**Comment by Repooc** [comment]
Just tested the one you suggested, awesome!  Thanks for that.

**Comment by SpoonsJTD** [comment]
The latest version of this plugin is for CB 1.2.5-R4.0.
