### ISSUE TITLE
Towny

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#16]
http://dev.bukkit.org/server-mods/towny-advanced/
Latest of both, your mod and this. This is due to the version check. 

14.12 01:37:02 [Server] INFO at java.lang.Thread.run(Thread.java:722)
14.12 01:37:02 [Server] INFO at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:40)
14.12 01:37:02 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:245)
14.12 01:37:02 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:886)
14.12 01:37:02 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:902)
14.12 01:37:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
14.12 01:37:02 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
14.12 01:37:02 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
14.12 01:37:02 [Server] INFO at com.palmergames.bukkit.towny.Towny.onEnable(Unknown Source)
14.12 01:37:02 [Server] INFO at com.palmergames.bukkit.towny.Towny.registerEvents(Unknown Source)
14.12 01:37:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:499)
14.12 01:37:02 [Server] INFO org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register com.palmergames.bukkit.towny.listeners.TownyPlayerListener@3c9fc958 while not enabled
14.12 01:37:02 [Server] SEVERE Error occurred while enabling Towny v0.82.0.2 (Is it up to date?)
14.12 01:37:02 [Server] INFO =============================================================
14.12 01:37:02 [Server] INFO [Towny] Version: 0.82.0.2 - Mod Disabled
14.12 01:37:02 [Server] INFO ==============================================================
14.12 01:37:02 [Server] INFO [com.palmergames.bukkit.towny.Towny] [Towny] Disabling Towny v0.82.0.2
14.12 01:37:02 [Server] INFO [Towny] Database: [Load] flatfile [Save] flatfile
14.12 01:37:02 [Server] INFO ====================      Towny      ========================
14.12 01:37:02 [Server] INFO [com.palmergames.bukkit.towny.Towny] [Towny] Enabling Towny v0.82.0.2
14.12 01:37:02 [Server] INFO Loading PostWorld plugins...
14.12 01:37:02 [Server] INFO Thread: BukkitCoreAPI-0
14.12 01:37:02 [Server] INFO Hi!
14.12 01:37:02 [Server] INFO [com.palmergames.bukkit.towny.Towny] [Towny] Loading Towny v0.82.0.2
14.12 01:37:02 [Server] INFO Plugins are being loaded...

**Comment by keepcalm** [comment]
So to fix this I need to make the version a bukkit-style number?

**Comment by xKillerbees** [comment]
Actually, towny has an option to bypass the version check. I didn't know what you could do though in case other plugins do not have that feature.
