### ISSUE TITLE
PermissionsEx doesn't work still (Build 72)

### ISSUE THREAD

**Issue by TempestCraft** [keepcalm/BukkitForge#160]
I get "You do not have access to that command" with all commands I try which I have given perms to for my default group

here is my permissions file
http://pastebin.com/fWecxTxu

The screenshot below is what I get when trying to use /help
http://img339.imageshack.us/img339/7289/20130107180320.png

**Comment by Chasgasm** [comment]
I'm pretty sure this is a ModifyWorld issue. Without ModifyWorld my PEX seems to work fine.

**Comment by TempestCraft** [comment]
I removed Modifyworld, I forgot to remove it's permissions

**Comment by Chasgasm** [comment]
The first permission in every group of your permissions file needs a space added to the beginning so that the "-" lines up with the "p" in "permissions". I think YML is pretty strict about that.

**Comment by TempestCraft** [comment]
it is lined up, its just a bug in pastebins website, scroll down and look in the raw file.

**Comment by SpoonsJTD** [comment]
Closed as dupe - permissions issue.
