### ISSUE TITLE
Server crash at startup with build 71 and CUSTOM_BUILD

### ISSUE THREAD

**Issue by Factor2** [keepcalm/BukkitForge#161]
Server crashes on startup with the two builds mentioned in the title

Wiping these libraries (gson-2.1-cb.jar?) and manually adding them  to the server directory probably works, but have yet to try.

03:24:41 CONSOLE: [INFO] Forge Mod Loader version 4.6.17.515 for Minecraft 1.4.6 loading
03:24:41 CONSOLE: [SEVERE] There were errors during initial FML setup. Some files failed to download or were otherwise corrupted. You will need to manually obtain the following files from these download links and ensure your lib directory is clean.
03:24:41 CONSOLE: [SEVERE] **\* Download http://files.minecraftforge.net/fmllibs/argo-2.25.jar
03:24:41 CONSOLE: [SEVERE] **\* Download http://files.minecraftforge.net/fmllibs/guava-12.0.1.jar
03:24:41 CONSOLE: [SEVERE] **\* Download http://files.minecraftforge.net/fmllibs/asm-all-4.0.jar
03:24:41 CONSOLE: [SEVERE] **\* Download http://files.minecraftforge.net/fmllibs/bcprov-jdk15on-147.jar
03:24:41 CONSOLE: [SEVERE] **\* Download http://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.3/commons-lang-2.3.jar
03:24:41 CONSOLE: [SEVERE] **\* Download http://repo.maven.apache.org/maven2/org/avaje/ebean/2.8.1/ebean-2.8.1.jar
03:24:41 CONSOLE: [SEVERE] **\* Download https://github.com/keepcalm/BukkitForge/blob/master/lib/gson-2.1-cb.jar?raw=true
03:24:41 CONSOLE: [SEVERE] **\* Download http://repo.maven.apache.org/maven2/org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.jar
03:24:41 CONSOLE: [SEVERE] **\* Download http://repo.maven.apache.org/maven2/org/yaml/snakeyaml/1.9/snakeyaml-1.9.jar
03:24:41 CONSOLE: [SEVERE] **\* Download http://repo.maven.apache.org/maven2/org/fusesource/jansi/jansi/1.9/jansi-1.9.jar
03:24:41 CONSOLE: [SEVERE] **\* Download https://github.com/keepcalm/BukkitForge/blob/master/lib/guava10-renamed.jar?raw=true
03:24:41 CONSOLE: [SEVERE] **\* Download http://repo.maven.apache.org/maven2/mysql/mysql-connector-java/5.1.14/mysql-connector-java-5.1.14.jar
03:24:41 CONSOLE: [SEVERE] <===========>
03:24:41 CONSOLE: [SEVERE] The following is the errors that caused the setup to fail. They may help you diagnose and resolve the issue
03:24:41 CONSOLE: [SEVERE] The file gson-2.1-cb.jar was found in your lib directory and has an invalid checksum 881bf5cf5adb67e406df8dd5061c61bb4c3e143a (expecting bbf47ddc2e8931665390d4de33caf0ece9d3ff75) - it is unlikely to be the correct download, please move it out of the way and try again.
03:24:41 CONSOLE: [SEVERE] <<< ==== >>>
03:24:41 CONSOLE: [SEVERE] The following is diagnostic information for developers to review.
03:24:41 CONSOLE: [SEVERE] Error details
03:24:41 CONSOLE: file gson-2.1-cb.jar was found in your lib directory and has an invalid checksum 881bf5cf5adb67e406df8dd5061c61bb4c3e143a (expecting bbf47ddc2e8931665390d4de33caf0ece9d3ff75) - it is unlikely to be the correct download, please move it out of the way and try again.
03:24:41 CONSOLE: [INFO] Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: A fatal error occured and FML cannot continue
03:24:41 CONSOLE: [INFO] at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:175)
03:24:41 CONSOLE: [INFO] at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:133)
03:24:41 CONSOLE: [INFO] at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
03:24:41 CONSOLE: [INFO] at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1375)
03:24:41 CONSOLE: [INFO] Caused by: java.lang.RuntimeException: A fatal error occured and FML cannot continue
03:24:41 CONSOLE: [INFO] at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:228)
03:24:41 CONSOLE: [INFO] at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:155)
03:24:41 CONSOLE: [INFO] ... 3 more

**Comment by shakey2** [comment]
I am having this problem as well with build 71

**Comment by Chasgasm** [comment]
Delete the gson-2.1-cb.jar from your lib folder and start the server up. It should redownload it automatically and work fine.

**Comment by Factor2** [comment]
Thanks Chasgasm. That worked great; build 71 works now
