### ISSUE TITLE
Plugins don't load at all

### ISSUE THREAD

**Issue by iakat** [keepcalm/BukkitForge#162]
Here's the server output
http://ix.io/3Ut
Here's my files tree:
http://ix.io/3Uu
Using Tekkit Lite server, BukkitForge build 72.

Expected behiavour:
- Output mentioning plugins/*
- Eventual successful load

Actual behiavour:
- BukkitForge doesn't try to load any plugin from the plugins/ directory.

**Comment by ghost** [comment]
Try taking out Forge Essentials.

**Comment by keepcalm** [comment]
Yes. I don't think BukkitForge is compatible with FE.

**Comment by iakat** [comment]
Tried so.
Output:
http://ix.io/3US
File tree:
http://ix.io/3UT

**Comment by mmis1000** [comment]
You should unzio the Essentials-2.9.5-all.zip
and put what part you want to use into plugin
also,I don't think the worldedit should be placed in lib
