### ISSUE TITLE
Factions working perms and some things broken however

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#163]
got factions 1.8 to work however in protected areas u cant destroy blocks but the the block pops out as an item so basically a huge dupe right there. Also giving the perms for factions dont work unless op. thanks again for all that we do have though keepcalm!

**Comment by keepcalm** [comment]
Try the _very_ latest build. I either fixed something or created a huge vulnerability. It would be much appreciated if you can tell me if permissions work.

**Comment by ghost** [comment]
yah my perms for other plugins work cmdbook pex is working fine so far with mchat prefixes and all were working fine for me. just the factions perms werent working when given and i was using the latest build 73 if ya want to come on and see,, pm me for the ip

**Comment by ghost** [comment]
also since ur here tagapi is working forgot which version, but nametags isnt working when given the perms would be nice if u could port tagapi since it works nicely with factions (if you have time that is, i definitely would prefer a factions fully working port though)

**Comment by Adubbz** [comment]
They do? I'm using PEX and the perms for essentials are definately not working still (unless opped) (I'm using build 73)

**Comment by ghost** [comment]
yup my perms for let cmdbook is working correctly i feel essentials is just overall bugged so i avoided it and thanks to Hypno(forgotlastpart) i use cmdbook instead running with mchat prefixs and perms working so far

**Comment by ghost** [comment]
have u configured pex right? i feel like i know what might be causing the problem use my config:
http://puu.sh/1L7mz

**Comment by Adubbz** [comment]
Using your config didn't help, it's an issue with either the essentials port or BukkitForge

**Comment by ghost** [comment]
yah i bet :( use commandbook unfortunately it doesnt have econ so only downside

**Comment by SpoonsJTD** [comment]
Closed as dupe - permissions issue.
