### ISSUE TITLE
[TownyChat] NoClassDefFoundError

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#164]
08.01 00:40:26 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
08.01 00:40:26 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
08.01 00:40:26 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
08.01 00:40:26 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
08.01 00:40:26 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
08.01 00:40:26 [Server] INFO at java.security.AccessController.doPrivileged(Native Method)
08.01 00:40:26 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
08.01 00:40:26 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
08.01 00:40:26 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.palmergames.bukkit.towny.Towny
08.01 00:40:26 [Server] INFO at java.lang.Thread.run(Thread.java:722)
08.01 00:40:26 [Server] INFO at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:47)
08.01 00:40:26 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:265)
08.01 00:40:26 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:915)
08.01 00:40:26 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:931)
08.01 00:40:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:390)
08.01 00:40:26 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
08.01 00:40:26 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
08.01 00:40:26 [Server] INFO at com.palmergames.bukkit.TownyChat.Chat.onEnable(Unknown Source)
08.01 00:40:26 [Server] INFO at com.palmergames.bukkit.TownyChat.Chat.checkPlugins(Unknown Source)
08.01 00:40:26 [Server] INFO java.lang.NoClassDefFoundError: com/palmergames/bukkit/towny/Towny
08.01 00:40:26 [Server] SEVERE Error occurred while enabling TownyChat v0.32 (Is it up to date?)

**Comment by minecrafter** [comment]
Did you install Towny?

**Comment by xKillerbees** [comment]
Lol, yes.

**Comment by minecrafter** [comment]
What version?

**Comment by xKillerbees** [comment]
The same version I've used for so long. Bukkitforge 63 loaded it fine, 73 does this.

**Comment by ghost** [comment]
you have towny working? with perms? i mean i got it working just couldnt do anything unless im op

**Comment by SpoonsJTD** [comment]
Please re-check, I just loaded Towny advanced 0.82 with all plugins fine.

**Comment by SpoonsJTD** [comment]
No response, closing.
