### ISSUE TITLE
Mindcrack V7 (Recently Updated) + BukkitForge #74

### ISSUE THREAD

**Issue by Repooc** [keepcalm/BukkitForge#166]
Had some issues and it crashed on me on first couple attempts to start the server after the update which was just mod updates.
Paste Bin Links:
ForgeLog #74 (If I recall)
http://pastebin.com/DeDPjY3F

We were on Jenkins #50 prior so we went back and this is the ForgeLoge for that.  Server didn't crash but yet still errors for you to look at.
http://pastebin.com/4cXCxtv2

Server Log for both which were in one file
http://pastebin.com/p8hATyrG

**Comment by HaoSs07** [comment]
you dont need to post all the logs :P just the crash report found here : /home/repooc/mindcrack/./crash-reports/crash-2013-01-08_10.53.25-server.txt

**Comment by Repooc** [comment]
Better safe than sorry.  Just to note, I tried starting the newly updated server without deleting the contents of the lib folder then tried after and you see the log for after deleting the lib folder.

**Comment by shakey2** [comment]
I'm getting this error on build 74 as well. Also I'm using mindcrack v6.

**Comment by ghost** [comment]
Build 74 has a vulnerability in it will cause crashes for all these types of packs that add new entities. Same happened on my Dwolf20 server, went back to 73 server is not crashing :) though some plugins dont work :(

**Comment by SpoonsJTD** [comment]
Pretty sure this is fixed in the latest builds, I saw this a week or so ago but I no longer get it. Feel free to reopen if you confirm it isn't fixed in latest.
