### ISSUE TITLE
Weird crash on build 74.

### ISSUE THREAD

**Issue by Benet** [keepcalm/BukkitForge#167]
---- Minecraft Crash Report ----
// You're mean.

Time: 08.01.13 16:03
Description: Ticking entity

java.lang.NullPointerException
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntity.getEntity(BukkitEntity.java:216)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingAttack(ForgeEventHandler.java:180)
    at net.minecraftforge.event.ASMEventHandler_38_ForgeEventHandler_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:338)
    at md.a(EntityLiving.java:993)
    at qj.a(SourceFile:45)
    at lq.y(Entity.java:540)
    at md.y(EntityLiving.java:569)
    at lq.j_(Entity.java:431)
    at md.j_(EntityLiving.java:808)
    at qj.j_(SourceFile:31)
    at qr.j_(SourceFile:145)
    at yc.a(World.java:2291)
    at in.a(WorldServer.java:647)
    at yc.g(World.java:2253)
    at yc.h(World.java:2107)
    at in.h(WorldServer.java:516)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:680)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntity.getEntity(BukkitEntity.java:216)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingAttack(ForgeEventHandler.java:180)
    at net.minecraftforge.event.ASMEventHandler_38_ForgeEventHandler_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:338)
    at md.a(EntityLiving.java:993)
    at qj.a(SourceFile:45)
    at lq.y(Entity.java:540)
    at md.y(EntityLiving.java:569)
    at lq.j_(Entity.java:431)
    at md.j_(EntityLiving.java:808)
    at qj.j_(SourceFile:31)
    at qr.j_(SourceFile:145)
    at yc.a(World.java:2291)
    at in.a(WorldServer.java:647)
    at yc.g(World.java:2253)

-- Entity being ticked --
Details:
    Entity Type: Zombie (qr)
    Entity ID: 930
    Name: Zombie
    Exact location: 297,50, 64,00, 263,50
    Block location: World: (297,64,263), Chunk: (at 9,4,7 in 18,16; contains blocks 288,0,256 to 303,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Momentum: 0,00, -0,08, 0,00
Stacktrace:
    at yc.h(World.java:2107)
    at in.h(WorldServer.java:516)

-- Affected level --
Details:
    Level name: world
    All players: 1 total; [iq['Benets7'/192, l='world', x=255,36, y=64,00, z=169,70]]
    Chunk stats: ServerChunkCache: 625 Drop: 0
    Level seed: 4646184398499300824
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (252,64,164), Chunk: (at 12,4,4 in 15,10; contains blocks 240,0,160 to 255,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 13568 game time, 30004 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 101809 (now: false), thunder time: 128698 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:680)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

-- System Details --
Details:
    Minecraft Version: 1.4.7
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.7.0_07, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 894131104 bytes (852 MB) / 1029046272 bytes (981 MB) up to 1029046272 bytes (981 MB)
    JVM Flags: 2 total; -Xmx1024M -Xms1024M
    AABB Pool Size: 4650 (260400 bytes; 0 MB) allocated, 3904 (218624 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 63
    FML: MCP v7.26 FML v4.7.4.520 Minecraft Forge 6.6.0.497 17 mods loaded, 17 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BlockBreak [Block Break Event](BukkitForge-1.4.7-74.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge [BukkitForge](BukkitForge-1.4.7-74.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2 [IndustrialCraft 2](industrialcraft-2_1.112.170-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCore [RedPower](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerBase [RP Base](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerMachine [RP Machine](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCompat [RP Compat](RedPowerCompat-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWiring [RP Wiring](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLogic [RP Logic](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLighting [RP Lighting](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWorld [RP World](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerControl [RP Control](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge Details: 1.4.6 (Bukkit API version 1.4.5-R0.2)
Plugins Loaded:[No plugins loaded]
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 1373 (76888 bytes; 0 MB) allocated, 762 (42672 bytes; 0 MB) used
    Player Count: 1 / 20; [iq['Benets7'/192, l='world', x=255,36, y=64,00, z=169,70]]
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)

Next time i started the server crash was the same except ticking entity.

-- Entity being ticked --
Details:
    Entity Type: Chicken (oy)
    Entity ID: 152
    Name: Chicken
    Exact location: 133,50, 63,00, 336,50
    Block location: World: (133,63,336), Chunk: (at 5,3,0 in 8,21; contains blocks 128,0,336 to 143,255,351), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Momentum: 0,00, -0,08, 0,00
Stacktrace:
    at yc.h(World.java:2107)
    at in.h(WorldServer.java:516)

Some kind of problem with mobs ?

**Comment by charlieTheBotDev** [comment]
I get the what looks like the same crash from build 74

I'm using Direwolf20 server v4

---- Minecraft Crash Report ----
// You're mean.

Time: 1/9/13 3:33 AM
Description: Ticking entity

java.lang.NullPointerException
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntity.getEntity(BukkitEntity.java:216)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingAttack(ForgeEventHandler.java:180)
    at net.minecraftforge.event.ASMEventHandler_115_ForgeEventHandler_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:342)
    at md.a(EntityLiving.java:993)
    at ow.a(SourceFile:195)
    at lq.y(Entity.java:540)
    at md.y(EntityLiving.java:569)
    at lq.j_(Entity.java:431)
    at md.j_(EntityLiving.java:808)
    at ow.j_(SourceFile:106)
    at yc.a(World.java:2295)
    at in.a(WorldServer.java:647)
    at yc.g(World.java:2257)
    at yc.h(World.java:2103)
    at in.h(WorldServer.java:516)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntity.getEntity(BukkitEntity.java:216)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingAttack(ForgeEventHandler.java:180)
    at net.minecraftforge.event.ASMEventHandler_115_ForgeEventHandler_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:342)
    at md.a(EntityLiving.java:993)
    at ow.a(SourceFile:195)
    at lq.y(Entity.java:540)
    at md.y(EntityLiving.java:569)
    at lq.j_(Entity.java:431)
    at md.j_(EntityLiving.java:808)
    at ow.j_(SourceFile:106)
    at yc.a(World.java:2295)
    at in.a(WorldServer.java:647)
    at yc.g(World.java:2257)

-- Entity being ticked --
Details:
    Entity Type: Bat (ow)
    Entity ID: 75
    Name: Bat
    Exact location: 591.83, 12.10, 585.32
    Block location: World: (591,12,585), Chunk: (at 15,0,9 in 36,36; contains blocks 576,0,576 to 591,255,591), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
    Momentum: -0.21, -0.05, 0.22
Stacktrace:
    at yc.h(World.java:2103)
    at in.h(WorldServer.java:516)

-- Affected level --
Details:
    Level name: Project-Icarus
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 625 Drop: 0
    Level seed: 463294852
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (488,63,657), Chunk: (at 8,3,1 in 30,41; contains blocks 480,0,656 to 495,255,671), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
    Level time: 3131919 game time, 3375069 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 3166 (now: false), thunder time: 79290 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

-- System Details --
Details:
    Minecraft Version: 1.4.6
    Operating System: Linux (amd64) version 2.6.32-279.el6.x86_64
    Java Version: 1.7.0_10, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1397254408 bytes (1332 MB) / 1809055744 bytes (1725 MB) up to 5726666752 bytes (5461 MB)
    JVM Flags: 2 total; -Xms1G -Xmx6G
    AABB Pool Size: 1006 (56336 bytes; 0 MB) allocated, 682 (38192 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 4, tcache: 0, allocated: 3, tallocated: 63
    FML: MCP v7.25 FML v4.6.17.515 Minecraft Forge 6.5.0.489 55 mods loaded, 55 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BlockBreak [Block Break Event](BukkitForge-1.4.7-74.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge [BukkitForge](BukkitForge-1.4.7-74.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ChickenChunks [ChickenChunks](ChickenChunks 1.2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ComputerCraft [ComputerCraft](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CCTurtle [ComputerCraft Turtles](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    EnderStorage [EnderStorage](EnderStorage 1.3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ExtrabiomesXL [ExtrabiomesXL](ExtrabiomesXL-universal-1.4.7-3.8.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    factorization [Factorization](Factorization-0.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    GraviGun [GraviGun](GravityGun1.4.6v1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2 [IndustrialCraft 2](industrialcraft-2_1.112.170-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2NuclearControl [Nuclear Control](IC2NuclearControl-1.4.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ModularForceFieldSystem [Modular ForceField System V2](ModularForceFieldSystemV2.2.8.2.14.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    OmniTools [OmniTools](OmniTools-2.2.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PortalGun [Portal Gun](PortalGun1.4.7v2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Core [BuildCraft](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Builders [BC Builders](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Energy [BC Energy](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Factory [BC Factory](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forestry [Forestry for Minecraft](forestry-A-1.7.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Railcraft [Railcraft](Railcraft_1.4.6-6.13.1.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCore [RedPower](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerBase [RP Base](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerMachine [RP Machine](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCompat [RP Compat](RedPowerCompat-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWiring [RP Wiring](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLogic [RP Logic](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLighting [RP Lighting](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWorld [RP World](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerControl [RP Control](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    SoulShards [SoulShards](SoulShards-v1.26-universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    StevesCarts [Steve's Carts](StevesCarts2.0.0.a42.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Thaumcraft [Thaumcraft](Thaumcraft3.0.1c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion [Thermal Expansion](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Factory [Factory](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Energy [Energy](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Transport [Transport](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|Core [WR-CBE Core](WR-CBE Core 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|Addons [WR-CBE Addons](WR-CBE Addons 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|RedPower [WR-CBE RedPower](WR-CBE RedPower 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Transport [BC Transport](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Silicon [BC Silicon](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ChargePads [Charge Pads](chargepads-universal-2.3.0.58.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CompactSolars [Compact Solar Arrays](compactsolars-universal-1.4.6-3.2.0.21.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    EE3 [Equivalent Exchange 3](ee3-universal-pre1f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IronChest [Iron Chest](ironchest-universal-1.4.7-4.5.2.213.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    MiscPeripherals [MiscPeripherals](miscperipherals-2.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    GraviSuite [Gravitation Suite](mod_zGraviSuite_1_6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Mystcraft [Mystcraft](mystcraft-uni-1.4.6-0.9.5.00.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ObsidiPlates [Obsidian Pressure Plates](obsidiplates-universal-1.2.0.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    XyCraft [XyCraft](xycraft-universal-1.4.6-0.9.44.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge Details: 1.4.6 (Bukkit API version 1.4.5-R0.2)
Plugins Loaded:GroupManager v${GMVer} (${build.number}) (Phoenix): Enabled, WorldEdit v5.4.5: Enabled, WorldGuard v5.6.5: Enabled, Permissions v3.1.6: Enabled, Essentials v${build.number}: Enabled, EssentialsXMPP v${build.number}: Enabled, EssentialsChat v${build.number}: Enabled, EssentialsProtect v${build.number}: Enabled, EssentialsSpawn v${build.number}: Enabled, EssentialsAntiBuild v${build.number}: Enabled and EssentialsGeoIP v${build.number}: Enabled
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 575 (32200 bytes; 0 MB) allocated, 258 (14448 bytes; 0 MB) used
    Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)

**Comment by Benet** [comment]
Same thing on build 76

-- Entity being ticked --
Details:
    Entity Type: Bat (ow)
    Entity ID: 84
    Name: Bat
    Exact location: 305,03, 43,02, 305,20
    Block location: World: (305,43,305), Chunk: (at 1,2,1 in 19,19; contains blocks 304,0,304 to 319,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Momentum: 0,18, 0,05, -0,07
Stacktrace:
    at yc.h(World.java:2107)
    at in.h(WorldServer.java:516)

**Comment by SpoonsJTD** [comment]
Ticking entity - pretty sure it's fixed in latest builds
