### ISSUE TITLE
Towny - Not broadcasting town border messages.

### ISSUE THREAD

**Issue by ayeso** [keepcalm/BukkitForge#168]
I noticed towny does not broadcast any message when you leave/enter a region.

Ie, leave your town and enter wilderness, you do not get a message saying "wilderness"

**Comment by ghost** [comment]
most of towny is broken since you cant use the perms

**Comment by keepcalm** [comment]
I need to implement the playerMoveEvent for this to work. It's coming...

**Comment by SpoonsJTD** [comment]
Closing as dupe - playermoveevent is captured in another issue.
