### ISSUE TITLE
Voxelsniper

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#17]
Latest of everything. This one though I do not know why it does this.

14.12 06:42:57 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
14.12 06:42:57 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
14.12 06:42:57 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:38)
14.12 06:42:57 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84)
14.12 06:42:57 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
14.12 06:42:57 [Server] INFO at java.security.AccessController.doPrivileged(Native Method)
14.12 06:42:57 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
14.12 06:42:57 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
14.12 06:42:57 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.Entity
14.12 06:42:57 [Server] INFO ... 6 more
14.12 06:42:57 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:148)
14.12 06:42:57 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
14.12 06:42:57 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
14.12 06:42:57 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
14.12 06:42:57 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
14.12 06:42:57 [Server] INFO at com.thevoxelbox.voxelsniper.VoxelSniper.<init>(VoxelSniper.java:49)
14.12 06:42:57 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/Entity
14.12 06:42:57 [Server] INFO at java.lang.Thread.run(Thread.java:722)
14.12 06:42:57 [Server] INFO at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:40)
14.12 06:42:57 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:239)
14.12 06:42:57 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugins(BukkitServer.java:858)
14.12 06:42:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
14.12 06:42:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
14.12 06:42:57 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:152)
14.12 06:42:57 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/minecraft/server/Entity
14.12 06:42:57 [Server] SEVERE Could not load './plugins/VoxelSniper-5.168.0.jar' in folder './plugins'

**Comment by keepcalm** [comment]
Ok, going to have to port that then, or modify the ClassLoader.

**Comment by keepcalm** [comment]
I've done the code, I just need to compile it.

**Comment by xKillerbees** [comment]
Sounds good, thanks. Looking forward to the updated version of bukkitforge to test more.

**Comment by keepcalm** [comment]
I've ported it, feel free to test :)
