### ISSUE TITLE
worldguard bug

### ISSUE THREAD

**Issue by vasyacullin** [keepcalm/BukkitForge#172]
video http://www.youtube.com/watch?v=nPOsrWug9YQ

**Comment by charlieTheBotDev** [comment]
I also have this problem, as well as explosions still damaging the area even though flags are off. 

BukkitForge Build 73

**Comment by hitZor** [comment]
Yea, that's kinda annoying bug. Because of that one i cannot open beta of my server. :( But i trust in keepcalm's great work and expect that fixed asap. :) :+1:

**Comment by alexbegt** [comment]
McPriate, We will not help you if you keep pushing up your error report.

**Comment by keepcalm** [comment]
Pushes removed. Believe it or not, I DO read every bug report. Sometimes I just don't respond to them.

**Comment by charlieTheBotDev** [comment]
Any news on a fix for this / other worlguard related issues?

**Comment by vasyacullin** [comment]
keepcalm, please correct the error with "worldguard".
When you break a protected block, it appears there again and drops a copy

**Comment by xTsukuyomix** [comment]
well since i also saw that explosives like tnt,nukes .itnt still work. i used what keepcalm gave us on his dist folder
essentials AntiBuild, it at least prevent its placing from players
also since we run with mods, is recommendable ban assambers,deployers, since they skip this permission

**Comment by SpoonsJTD** [comment]
Closing as dupe - another worldguard issue exists.
