### ISSUE TITLE
ClearLag crash

### ISSUE THREAD

**Issue by milten21** [keepcalm/BukkitForge#173]
Then I tried to use /lagg unloadchunks command, I get a crash

Crash report:
http://pastebin.com/TdB6Qg9H
Forge log:
http://pastebin.com/nguxdUBg

BukkitForge Build 73

**Comment by TempestCraft** [comment]
Use version 1.7.0, I think that one works, I use it but I'm on build 72 so I'm only 99% sure that it works on 73

**Comment by milten21** [comment]
Thank you, all work fine!
