### ISSUE TITLE
Newest build causing server crash

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#177]
Upon joining my private testing server, the server gives an error and then crashes.

server.log: http://pastebin.com/2Vp9pdJM

Currently running bukkitforge build 74

**Comment by ghost** [comment]
yes its a known issue with latest build use 73 instead

**Comment by clienthax** [comment]
confirmed

**Comment by ghost** [comment]
looks like build 76 is causing this too i am using direwolf20 modpack btw so i feel like same is happening for mindcrack servers

**Comment by mmis1000** [comment]
all issues caused by keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingAttack(ForgeEventHandler.java:180)
seem fixed in the newest version.
redownload it may fix that

**Comment by SpoonsJTD** [comment]
Should be fixed in latest build.
