### ISSUE TITLE
It's wrong in the minecraft 1.4.6 server.

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#179]
It's wrong in the minecraft 1.4.6 server.
Can the mod  loaded in the version of 1.4.6?
If it can loaded in the 1.4.7 only  ,I think I will worry that I want to use the 1.4.6 > <
MOD version is -76 or -75 (My English isn;t very well, I hope you can understand what I say .)

I had install the ess ,lockette , mcMMO , MobHealth , multiworld , Quickshop , residence , WorldBorder ,& WorldEdit.
The ESS can use something command.
The Lockette work badly.It can't put the sign on the  -( I forget the word…… en .. the chest.)
The mcMMO is working bad too.It can use anything I think.
The MobHealth is working.
The multiworld can't create or delete the world . I try it, but……is wrong.
The Quickshop . It would destroy the chest.
The residence can't create too.But it can selected.
The WorldBorder is Run very well. THX.
The WorldEdit .It can be used.But I  thing something would be wrong ,but I forget .
(I run rhe mod of 6x .Sorry I forgot the specific version. But  now, I use the 7X. I can't use at all....TAT  I hope you can be solve . BEST WISH= -)

This is the crash-report::

---- Minecraft Crash Report ---- // Oops.  Time: 1/9/13 7:18 PM Description: Ticking entity  java.lang.NullPointerException
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntity.getEntity(BukkitEntity.java:216)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingAttack(ForgeEventHandler.java:180)
    at net.minecraftforge.event.ASMEventHandler_18_ForgeEventHandler_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:328)
    at md.a(EntityLiving.java:993)
    at qj.a(SourceFile:45)
    at lq.d(Entity.java:1084)
    at lq.d(Entity.java:957)
    at md.e(EntityLiving.java:1535)
    at md.c(EntityLiving.java:1823)
    at qj.c(SourceFile:26)
    at qn.c(SourceFile:141)
    at md.j_(EntityLiving.java:843)
    at qj.j_(SourceFile:31)
    at yc.a(World.java:2295)
    at in.a(WorldServer.java:645)
    at yc.g(World.java:2257)
    at yc.h(World.java:2103)
    at in.h(WorldServer.java:514)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Stacktrace:  at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntity.getEntity(BukkitEntity.java:216)  at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingAttack(ForgeEventHandler.java:180)   at net.minecraftforge.event.ASMEventHandler_18_ForgeEventHandler_onLivingAttack_LivingAttackEvent.invoke(.dynamic)  at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)     at net.minecraftforge.event.EventBus.post(EventBus.java:103)    at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:328)     at md.a(EntityLiving.java:993)  at qj.a(SourceFile:45)  at lq.d(Entity.java:1084)   at lq.d(Entity.java:957)    at md.e(EntityLiving.java:1535)     at md.c(EntityLiving.java:1823)     at qj.c(SourceFile:26)  at qn.c(SourceFile:141)     at md.j_(EntityLiving.java:843)     at qj.j_(SourceFile:31)     at yc.a(World.java:2295)    at in.a(WorldServer.java:645)   at yc.g(World.java:2257)  -- Entity being ticked -- Details:    Entity Type: Skeleton (qn)  Entity ID: 47   Name: Skeleton  Exact location: 134.92, 10.83, 128.54   Block location: World: (134,10,128), Chunk: (at 6,0,0 in 8,8; contains blocks 128,0,128 to 143,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)   Momentum: 0.03, -0.17, -0.03 Stacktrace:    at yc.h(World.java:2103)    at in.h(WorldServer.java:514)  -- Affected level -- Details:    Level name: world   All players: 0 total; []    Chunk stats: ServerChunkCache: 625 Drop: 0  Level seed: 8416346706291052742     Level generator: ID 00 - default, ver 1. Features enabled: true     Level generator options:    Level spawn location: World: (215,64,220), Chunk: (at 7,4,12 in 13,13; contains blocks 208,0,208 to 223,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)  Level time: 39467 game time, 39467 day time     Level dimension: 0  Level storage version: 0x04ABD - Anvil  Level weather: Rain time: 3684 (now: false), thunder time: 6852 (now: false)    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false Stacktrace:     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)     at ho.r(DedicatedServer.java:270)   at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)   at fy.run(SourceFile:849)  -- System Details -- Details:    Minecraft Version: 1.4.6    Operating System: Windows 7 (x86) version 6.1   Java Version: 1.7.0_01, Oracle Corporation  Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation    Memory: 743690904 bytes (709 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)    JVM Flags: 2 total; -Xmx1024M -Xms1024M     AABB Pool Size: 2707 (151592 bytes; 0 MB) allocated, 480 (26880 bytes; 0 MB) used   Suspicious classes: FML and Forge are installed     IntCache: cache: 18, tcache: 0, allocated: 3, tallocated: 63    FML: MCP v7.25 FML v4.6.12.511 Minecraft Forge 6.5.0.471 18 mods loaded, 18 mods active     mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available   FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available   fihgu's Core Mod [fihgu's Core Mod](minecraft_server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available   BlockBreak [Block Break Event](BukkitForge-1.4.7-75.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available    BukkitForge [BukkitForge](BukkitForge-1.4.7-75.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available     jammyfurniture [Jammy Furniture Mod](1.4.6_Jammy_Furniture_Mod_V4.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available    CustomNpcs [CustomNpcs 1.4.5](CustomNPCs_1.4.6_小柒cn.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available    RedPowerCore [RedPower](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available    RedPowerBase [RP Base](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available     RedPowerMachine [RP Machine](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available     RedPowerCompat [RP Compat](RedPowerCompat-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available   RedPowerWiring [RP Wiring](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available  RedPowerLogic [RP Logic](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available    RedPowerLighting [RP Lighting](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available  RedPowerWorld [RP World](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available     RedPowerControl [RP Control](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available     UsefulFood [UsefulFood](usefulfood_v1.2.3-universal_cn.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available     BukkitForge Details: 1.4.6 (Bukkit API version 1.4.5-R0.2) Plugins Loaded:WorldBorder v1.6.1: Enabled, QuickShop v3.2A: Enabled, MultiWorld v4.4.1: Enabled, GroupManager v${GMVer} (${build.number}) (Phoenix): Enabled, WorldEdit v5.4.5: Enabled, Permissions v3.1.6: Enabled, Lockette v1.7.7: Enabled, mcMMO v1.3.11-b1030: Enabled, MobHealth v5.3.2: Enabled, Essentials v${build.number}: Enabled, EssentialsXMPP v${build.number}: Enabled, EssentialsProtect v${build.number}: Enabled, EssentialsSpawn v${build.number}: Enabled, EssentialsGeoIP v${build.number}: Enabled, EssentialsChat v${build.number}: Enabled, EssentialsAntiBuild v${build.number}: Enabled and Residence v2.6.6.1: Enabled     Profiler Position: N/A (disabled)   Vec3 Pool Size: 1549 (86744 bytes; 0 MB) allocated, 565 (31640 bytes; 0 MB) used    Player Count: 0 / 20; []    Is Modded: Definitely; Server brand changed to 'fml'    Type: Dedicated Server (map_server.txt)

**Comment by shakey2** [comment]
Its not because of your minecraft version, it should work fine with 1.4.6 The reason its not working for you is a bug that has nothing to do with using the wrong version. Remember this mod is in alpha state right now so its extremely buggy/unfinished.

**Comment by keepcalm** [comment]
If you update to the versions from the technic jenkins, you will have a stable version that fixes this.
