### ISSUE TITLE
Missing Biome mapping for BiomeGenBase

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#18]
It's caused on block update, like throwing a splash potion. 

14.12 06:46:11 [Server] SEVERE This crash report has been saved to: /./crash-reports/crash-2012-12-14_06.46.11-server.txt
14.12 06:46:11 [Server] INFO ... 20 more
14.12 06:46:11 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.block.BukkitBlock.<clinit>(BukkitBlock.java:425)
14.12 06:46:11 [Server] INFO Caused by: java.lang.IllegalArgumentException: Missing Biome mapping for BiomeGenBase[32]
14.12 06:46:11 [Server] INFO at fy.run(SourceFile:856)
14.12 06:46:11 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
14.12 06:46:11 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
14.12 06:46:11 [Server] INFO at ho.r(DedicatedServer.java:252)
14.12 06:46:11 [Server] INFO at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:696)
14.12 06:46:11 [Server] INFO at ht.b(SourceFile:30)
14.12 06:46:11 [Server] INFO at iw.b(NetworkListenThread.java:55)
14.12 06:46:11 [Server] INFO at iv.d(NetServerHandler.java:82)
14.12 06:46:11 [Server] INFO at cg.b(TcpConnection.java:451)
14.12 06:46:11 [Server] INFO at fl.a(SourceFile:58)
14.12 06:46:11 [Server] INFO at iv.a(NetServerHandler.java:499)
14.12 06:46:11 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:25)
14.12 06:46:11 [Server] INFO at net.minecraftforge.event.EventBus.post(EventBus.java:103)
14.12 06:46:11 [Server] INFO at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
14.12 06:46:11 [Server] INFO at net.minecraftforge.event.ASMEventHandler_82_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
14.12 06:46:11 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:279)
14.12 06:46:11 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callPlayerInteractEvent(BukkitEventFactory.java:186)
14.12 06:46:11 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callPlayerInteractEvent(BukkitEventFactory.java:196)
14.12 06:46:11 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.getBlockAt(BukkitWorld.java:195)
14.12 06:46:11 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.getBlock(BukkitChunk.java:90)
14.12 06:46:11 [Server] INFO java.lang.ExceptionInInitializerError
14.12 06:46:11 [Server] SEVERE Encountered an unexpected exception ExceptionInInitializerError
14.12 06:46:11 [Server] INFO    ... 20 more
14.12 06:46:11 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.block.BukkitBlock.<clinit>(BukkitBlock.java:425)
14.12 06:46:11 [Server] INFO Caused by: java.lang.IllegalArgumentException: Missing Biome mapping for BiomeGenBase[32]
14.12 06:46:11 [Server] INFO    at fy.run(SourceFile:856)
14.12 06:46:11 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
14.12 06:46:11 [Server] INFO    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
14.12 06:46:11 [Server] INFO    at ho.r(DedicatedServer.java:252)
14.12 06:46:11 [Server] INFO    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:696)
14.12 06:46:11 [Server] INFO    at ht.b(SourceFile:30)
14.12 06:46:11 [Server] INFO    at iw.b(NetworkListenThread.java:55)
14.12 06:46:11 [Server] INFO    at iv.d(NetServerHandler.java:82)
14.12 06:46:11 [Server] INFO    at cg.b(TcpConnection.java:451)
14.12 06:46:11 [Server] INFO    at fl.a(SourceFile:58)
14.12 06:46:11 [Server] INFO    at iv.a(NetServerHandler.java:499)
14.12 06:46:11 [Server] INFO    at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:25)
14.12 06:46:11 [Server] INFO    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
14.12 06:46:11 [Server] INFO    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
14.12 06:46:11 [Server] INFO    at net.minecraftforge.event.ASMEventHandler_82_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
14.12 06:46:11 [Server] INFO    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:279)
14.12 06:46:11 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callPlayerInteractEvent(BukkitEventFactory.java:186)
14.12 06:46:11 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callPlayerInteractEvent(BukkitEventFactory.java:196)
14.12 06:46:11 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.getBlockAt(BukkitWorld.java:195)
14.12 06:46:11 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.getBlock(BukkitChunk.java:90)
14.12 06:46:11 [Server] INFO java.lang.ExceptionInInitializerError
14.12 06:46:00 [Server] INFO Sending serverside check to: killerbeez
14.12 06:46:00 [Server] INFO Loading Player: killerbeez
14.12 06:46:00 [Multicraft] killerbeez ran command Message of the Day
14.12 06:46:00 [Connect] User killerbeez, IP 
14.12 06:46:00 [Server] INFO Loading dimension 13 (world) (ho@43edccf7)
14.12 06:46:00 [Server] INFO User killerbeez connecting with mods [ThermalExpansion, BuildCraft|Silicon, ServerCapes, ThermalExpansion|NEI, BuildCraft|Transport, ThermalExpansion|Transport, GraviSuite, ChargePads, BuildCraft|Core, IC2NuclearControl, ThermalExpansion|Factory, MoCreatures, ObsidiPlates, IC2, ThermalExpansion|Energy, StevesCarts, ExtrabiomesXL, ExtraBees, Mystcraft, Forestry, ComputerCraft, BinnieCore, AdvancedSolarPanel, BuildCraft|Factory, IronChest, BuildCraft|Energy, GregTech_Addon, Railcraft, ImmibisCore, MiscPeripherals, CCTurtle, Tubestuff, ModularForceFieldSystem, ForgeIRC, BuildCraft|Builders]

Plugins

craftconomy
towny
townychat
worldedit
questioner
register

**Comment by keepcalm** [comment]
That's an interesting one. No clue why that's happening, fairly certain I did biomes properly in 1.3.2.

**Comment by xKillerbees** [comment]
I can provide the environment if it helps testing at all. If you can't reproduce it that is.

**Comment by keepcalm** [comment]
I'm going to post an update which will contain code to tell me what the issue is. So if you could recreate and post the new log, using [this version](https://github.com/keepcalm/BukkitForge/blob/master/dist/bukkitForge-1.4.5-xKillerBees.jar?raw=true)

**Comment by xKillerbees** [comment]
When I use that version, it won't finish booting. 

14.12 21:16:29 [Server] INFO    at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:155)
14.12 21:16:29 [Server] INFO    at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:102)
14.12 21:16:29 [Server] INFO    at cpw.mods.fml.relauncher.RelaunchLibraryManager.discoverCoreMods(RelaunchLibraryManager.java:317)
14.12 21:16:29 [Server] INFO Caused by: java.lang.NullPointerException
14.12 21:16:29 [Server] INFO    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1369)
14.12 21:16:29 [Server] INFO    at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
14.12 21:16:29 [Server] INFO    at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:133)
14.12 21:16:29 [Server] INFO    at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:175)
14.12 21:16:29 [Server] INFO Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException

**Comment by keepcalm** [comment]
Whoops. But I think I found it anyway, so it's ok.
