### ISSUE TITLE
Console Error - "Unknown entity: buildcraft.core.EntityBlock"

### ISSUE THREAD

**Issue by Factor2** [keepcalm/BukkitForge#180]
Hi

As of build 71, the console spams this error message. Im not sure what its related to, cannot figure it out.

[WARNING] Unknown entity: buildcraft.core.EntityBlock - returning a dummy instance of BukkitEntity...

I have tried upgrading but later builds cause server crashing. Will post the error log for the higher builds in another issue.

Thank you

**Comment by keepcalm** [comment]
Try using the builds from the technicpack jenkins, they are stable now. Also, it's nothing to worry about.
