### ISSUE TITLE
[Shutdown Event] Server shutdown events not being forwarded to plugins

### ISSUE THREAD

**Issue by kenneaal** [keepcalm/BukkitForge#187]
Plugins are not getting the server shutdown event, and are thus not saving their latest data during server shutdown.
Most evident for my sake in Residence, which has an internal save cycle (Works fine), but doesn't currently save on shutdown.

**Comment by keepcalm** [comment]
Ok. I should probably call that...

**Comment by keepcalm** [comment]
Fixed
