### ISSUE TITLE
BukkitForge and Buildcraft quarries

### ISSUE THREAD

**Issue by vaiman** [keepcalm/BukkitForge#188]
Haven't seen this bug posted elsewhere but whenever I restart my server my quarry's mining arm disappears and my console displays this error:  BukkitForge - UnknownEntity: BuildCraft.Factory.EntityMechanicalArm - Returning a dummy instance of bukkit entity.

Thanks in advance for any help.

BukkitForge build - 63

**Comment by ghost** [comment]
i would suggest using build 73 its the latest build working with mods like buildcraft

**Comment by keepcalm** [comment]
Don't worry about it. It's just meant in case I missed a vanilla entity
