### ISSUE TITLE
java.lang.NoSuchMethodError: iq.h(F)Laob

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#19]
Caused by throwing a splash potion. 

14.12 06:55:23 [Server] SEVERE This crash report has been saved to: /./crash-reports/crash-2012-12-14_06.55.23-server.txt
14.12 06:55:23 [Server] INFO at fy.run(SourceFile:856)
14.12 06:55:23 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
14.12 06:55:23 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
14.12 06:55:23 [Server] INFO at ho.r(DedicatedServer.java:252)
14.12 06:55:23 [Server] INFO at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:696)
14.12 06:55:23 [Server] INFO at ht.b(SourceFile:30)
14.12 06:55:23 [Server] INFO at iw.b(NetworkListenThread.java:55)
14.12 06:55:23 [Server] INFO at iv.d(NetServerHandler.java:82)
14.12 06:55:23 [Server] INFO at cg.b(TcpConnection.java:451)
14.12 06:55:23 [Server] INFO at fl.a(SourceFile:58)
14.12 06:55:23 [Server] INFO at iv.a(NetServerHandler.java:525)
14.12 06:55:23 [Server] INFO at ir.a(ItemInWorldManager.java:378)
14.12 06:55:23 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:25)
14.12 06:55:23 [Server] INFO at net.minecraftforge.event.EventBus.post(EventBus.java:103)
14.12 06:55:23 [Server] INFO at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
14.12 06:55:23 [Server] INFO at net.minecraftforge.event.ASMEventHandler_78_ForgeEventHandler_playerSaysHai_PlayerInteractEvent.invoke(.dynamic)
14.12 06:55:23 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.playerSaysHai(ForgeEventHandler.java:220)
14.12 06:55:23 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.PlayerUtilities.getTargetBlock(PlayerUtilities.java:17)
14.12 06:55:23 [Server] INFO java.lang.NoSuchMethodError: iq.h(F)Laob;
14.12 06:55:23 [Server] SEVERE Encountered an unexpected exception NoSuchMethodError
14.12 06:55:23 [Server] INFO    at fy.run(SourceFile:856)
14.12 06:55:23 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
14.12 06:55:23 [Server] INFO    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
14.12 06:55:23 [Server] INFO    at ho.r(DedicatedServer.java:252)
14.12 06:55:23 [Server] INFO    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:696)
14.12 06:55:23 [Server] INFO    at ht.b(SourceFile:30)
14.12 06:55:23 [Server] INFO    at iw.b(NetworkListenThread.java:55)
14.12 06:55:23 [Server] INFO    at iv.d(NetServerHandler.java:82)
14.12 06:55:23 [Server] INFO    at cg.b(TcpConnection.java:451)
14.12 06:55:23 [Server] INFO    at fl.a(SourceFile:58)
14.12 06:55:23 [Server] INFO    at iv.a(NetServerHandler.java:525)
14.12 06:55:23 [Server] INFO    at ir.a(ItemInWorldManager.java:378)
14.12 06:55:23 [Server] INFO    at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:25)
14.12 06:55:23 [Server] INFO    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
14.12 06:55:23 [Server] INFO    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
14.12 06:55:23 [Server] INFO    at net.minecraftforge.event.ASMEventHandler_78_ForgeEventHandler_playerSaysHai_PlayerInteractEvent.invoke(.dynamic)
14.12 06:55:23 [Server] INFO    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.playerSaysHai(ForgeEventHandler.java:220)
14.12 06:55:23 [Server] INFO    at keepcalm.mods.bukkit.forgeHandler.PlayerUtilities.getTargetBlock(PlayerUtilities.java:17)
14.12 06:55:23 [Server] INFO java.lang.NoSuchMethodError: iq.h(F)Laob;

14.12 06:46:00 [Server] INFO User killerbeez connecting with mods [ThermalExpansion, BuildCraft|Silicon, ServerCapes, ThermalExpansion|NEI, BuildCraft|Transport, ThermalExpansion|Transport, GraviSuite, ChargePads, BuildCraft|Core, IC2NuclearControl, ThermalExpansion|Factory, MoCreatures, ObsidiPlates, IC2, ThermalExpansion|Energy, StevesCarts, ExtrabiomesXL, ExtraBees, Mystcraft, Forestry, ComputerCraft, BinnieCore, AdvancedSolarPanel, BuildCraft|Factory, IronChest, BuildCraft|Energy, GregTech_Addon, Railcraft, ImmibisCore, MiscPeripherals, CCTurtle, Tubestuff, ModularForceFieldSystem, ForgeIRC, BuildCraft|Builders]

Plugins

craftconomy
towny
townychat
worldedit
questioner
register

**Comment by keepcalm** [comment]
Already fixed

**Comment by xKillerbees** [comment]
Just haven't released it yet? Alright
