### ISSUE TITLE
[Towny] could not pass event player 

### ISSUE THREAD

**Issue by xTsukuyomix** [keepcalm/BukkitForge#190]
i have been trying to have essentials spawn+essentials and towny, downloaded from bukkitforge both of them , but always i set homes/spawn, it don't change of dimensions and just go to the coordinates.
also i get this towny error when go nether or die in nether
http://pastebin.com/bf4vx3aL

this is spawn.yml generated by essentials spawn

http://pastebin.com/PWQ6ZHwT

 i hope i can get some help, haven't found this error on search function, using 
BukkitForge-1.4.6-59.jar
and mindcrack server mod pack

**Comment by keepcalm** [comment]
You are a long way behind, update. Most recent builds can be found [here](http://bit.ly/11l3Dmi)

**Comment by xTsukuyomix** [comment]
still happen on build lastest build 1.4.7-20

**Comment by SpoonsJTD** [comment]
Try this again if you would latest build, various issues have been fixed since 20.

**Comment by SpoonsJTD** [comment]
Fixed unless we hear otherwise.
