### ISSUE TITLE
World Handler?

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#191]
I dont know if thats the right term? But i feel like a lot of issues are caused by the way the world is made/handled. In other words the world if loaded via forge will be 1 world folder with dimensions. Thus leading all plugins to believe every wold has the same coordinates when claiming/making regions. For example in factions if u claim a region in the overworld the same amount of space will be claimed in the nether and end. So i think if possible keepcalm could you let bukkit take over world management?  thanks for all the support though and as of build 73 modpacks like ftb are still working :D.

**Comment by keepcalm** [comment]
Unfortunately I can't do that, since it would break other mods (like mystcraft). So I have to fool bukkit into differing between dimensions.

**Comment by ghost** [comment]
Sweet i rather have mystcraft though tbh :),  since im using dwolf20

**Comment by Erycus** [comment]
Hm...somewhat similar problem here..
I'm trying to use this plugin and everything loads fine, and even the island generation 'works' http://dev.bukkit.org/server-mods/islandworld/
But uh...well it kinda just on island generation deletes the chunks that were there and then puts in the chunks for the skyblock...except it does it in the overworld >_>

2013-01-09 18:14:02 [WARNING] [BukkitForge] Apparently IslandWorld isn't an integer! Interesting! Using overworld instead...

Do you think there's a way the plugin maker could make this compatible by giving a config option that would generate the world files by creating a folder inside the world folder named DIM3?
Either that or I could perhaps somehow use the overworld as the island world, but...nether portals would be uh...teleporting people into the void probably whenever they try to go back to the 'overworld' (which would be a mystdimension) and end up in the skyislandworld which is DIM0

**Comment by charlieTheBotDev** [comment]
I'm not sure how well it worked yet (I tested for <5 mins) but I put in links to world folders in the style of vanilla (0,1,2). In theory this should let you put worlds in the correct location so that both bukkit and forge see them correctly. As said, not really done much testing yet but I'd like to think my theory is correct at least lol

**Comment by Erycus** [comment]
Could you provide a bit more detail by what you mean by links and how you did this?
