### ISSUE TITLE
Working Plugins page

### ISSUE THREAD

**Issue by TempestCraft** [keepcalm/BukkitForge#195]
Heres the current list http://bukkitforge.tempestcraft.ca/

Please tell me if any on the list don't work, I have not tested most of the plugins.

**Comment by shakey2** [comment]
Right now there are no plugins that work without any problems.

**Comment by TempestCraft** [comment]
My plugin has no errors with BukkitForge.

**Comment by shakey2** [comment]
It may not have any errors but that doesn't mean its fully working. Most of the bukkit hooks haven't been ported or aren't working properly yet.

**Comment by TempestCraft** [comment]
Well mine just sends a set message from the plugin's config thats all and it also has no permissions.

**Comment by Factor2** [comment]
Currently three plugins work well for me with build 73, maybe not 100%, but well enough!

ClearLagg - removes entities, as far as i can tell it works 100%.
Essentials.jar - this also works almost 100%, i use it as my permissions plugin since dedicated permission plugins are not working too well.
Lockette - I can lock chests for single users and lists of friends. Does not work with permissions though. Chest protection also works.

Thanks again keepcalm :)

**Comment by xTsukuyomix** [comment]
someone have found a working protection plugin, for player have their items safe?
i found that Command Shops works properly, totally functional
Grief Prevention, make protection, can be re-sized, locks modded items, but you can not make ore than 1 claim and you must place a chest for create it. i seems it fine :smile:

**Comment by TempestCraft** [comment]
I just created a page for the working plugins, theres a few more I need to add but I added most of them, keep commenting with more plugins.

**Comment by profjb** [comment]
Tempest ile add to this helpfull list. 

Hawkeye reloaded 1.4.6 Works! - need to add mySQL before it loads though.
Schedueld announcer 2 - Works!
WorldBorder - Works!
Vault - Works!
and all the plugins on this thread: http://forums.technicpack.net/threads/bukkitforge-getting-bukkit-plugins-on-tekkit-lite.34804/

**Comment by xTsukuyomix** [comment]
chestshop, don't work properly , even if you see it there, i tested, it dupes items, and if you sell it give money and don't remove it from user, let you make a shop in name of nonexistent players. or i am doing something really wrong xD

**Comment by xTsukuyomix** [comment]
one more, and this is good for server owners
TOWNY works locks, prevent use , let users make towns, well it need a bit of help from owners most for configuring it.
well it don't behave nicely with dimension so using /town spawn not from overworld most-likely kill you in a wall xD
but essentials also kill you, so i could say this is a win

**Comment by unrivaledneo** [comment]
Havnt been able to get any shop system working would have been nice though even multiverse doesnt work. wont let me import my map or use the one it generates

**Comment by shakey2** [comment]
Honeypot is listed as working but I can't seem to give myself permission to use it with groupmanager, I've also not been able to get permission nodes for banning item use or block place/destroy/interact to work with group manager. Has anyone been able to get that stuff working with group manager or PEX?

**Comment by TempestCraft** [comment]
ok I just made a new list and I changed the URL to the new list.

Most of the list is not finished but will be soon.

**Comment by xTsukuyomix** [comment]
anyone have found a anti cheat plugin?

**Comment by TempestCraft** [comment]
Im pretty sure that NoCheatPlus works but I could be wrong.

**Comment by interfect** [comment]
Citadel, PrisonPearl, and CombatTag do not seem to work. RadioBeacon does work, imperfectly. RandomSpawn loads but does not randomly spawn me.

**Comment by charlieTheBotDev** [comment]
I see iConomy on that list but when I try to use commands with it, it doesn't do anything. I use /money and it comes up in the server log but nothing else happens. I'm using the latest build of iConomy and BukkitForge as well as essentials.

Edit: 
Also, lockette doesnt work for me either, placing signs on or around chests as shown on the dev page for the plugin doesn't work.

**Comment by xTsukuyomix** [comment]
i used iconomy, but a better mix is vault+ iconomy, for /money with only iconomy use /balance. since iconomy "talk" to essentials

**Comment by TempestCraft** [comment]
I will remove that one, I did not test most of the plugins.

**Comment by charlieTheBotDev** [comment]
GriefPrevention also does not work properly. There are issues with modifying claims still.

Edit: on the bright side, I tested scheduledannouncer2 and Buycraft and confirmed that they both work 100% :)

**Comment by charlieTheBotDev** [comment]
Just tested a neat little plugin called Shops (http://dev.bukkit.org/server-mods/simple-shops/) it works quite well as far as I can tell. It needs iConomy and Vault.

Edit: Can't get iConomy to work properly though, only OP's can do /money player and /money doesn't work

**Comment by unrivaledneo** [comment]
what version u running cause /shop create dont do nothing at all

**Comment by unrivaledneo** [comment]
miltiverse doesnt work either always get the failed when importing worlds latest version of everything too

**Comment by SpoonsJTD** [comment]
May I recommend we create a wiki page for the list and link to it from the readme instead of using this issue as an announcement and discussion for various plug-ins?

**Comment by TempestCraft** [comment]
I can just make a forums page on my website, wouldn't take long since I would just have to make the domain point to the folder with the forums.

Sadly I don't have the power to edit the readme

**Comment by interfect** [comment]
You can edit the readme. Just fork the project, use the Github editor, and make a pull request.

That's probably where the working plugins list ought to go, too. In the readme, or in a file in the repo. A project wiki page would also work, assuming Github has something like that around here somewhere.

**Comment by SpoonsJTD** [comment]
Done, please track them here:
https://github.com/keepcalm/BukkitForge/wiki/Working-plugins-page
