### ISSUE TITLE
Permissions not being recognized?

### ISSUE THREAD

**Issue by UgLounge** [keepcalm/BukkitForge#196]
Using BukkitForge 1.4.7-82 GroupManager as well as PEX/PermissionsBukkit isn't working.
They load and have people in the default group, but upon a standard player trying to run nearly any command; they are hit with "You do not have access/permission to this command".

The commands are simple Essentials /home and /sethome.  Would really appreciate some help.

**Comment by Erycus** [comment]
Please search before posting an issue.  #103 #131 #154 #160
