### ISSUE TITLE
Craftpacket Stamper crashing Server

### ISSUE THREAD

**Issue by xfloh22** [keepcalm/BukkitForge#199]
as soon as someone puts a craftpacket into the stamper, it crashes the entire server and it cant be started again unless you remove bukkitforge and add it back in.

errorlog:

Time: 1/10/13 3:30 PM
Description: Ticking tile entity

java.lang.NullPointerException
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.getName(BukkitPlayer.java:119)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.hashCode(BukkitPlayer.java:749)
    at java.util.WeakHashMap.remove(WeakHashMap.java:543)
    at org.bukkit.plugin.SimplePluginManager.unsubscribeFromDefaultPerms(SimplePluginManager.java:680)
    at org.bukkit.permissions.PermissibleBase.clearPermissions(PermissibleBase.java:179)
    at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:153)
    at org.bukkit.permissions.PermissibleBase.<init>(PermissibleBase.java:31)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntityHuman.<init>(BukkitEntityHuman.java:51)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.<init>(BukkitPlayer.java:109)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.<init>(BukkitPlayer.java:114)
    at keepcalm.mods.bukkit.forgeHandler.BukkitCraftingHandler.onCrafting(BukkitCraftingHandler.java:61)
    at cpw.mods.fml.common.registry.GameRegistry.onItemCrafted(GameRegistry.java:309)
    at sq.a(SlotCrafting.java:118)
    at factorization.common.ItemCraft.craftAt(ItemCraft.java:229)
    at factorization.common.TileEntityStamper.doLogic(TileEntityStamper.java:160)
    at factorization.common.TileEntityFactorization.g(TileEntityFactorization.java:318)
    at yc.h(World.java:2155)
    at in.h(WorldServer.java:516)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.getName(BukkitPlayer.java:119)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.hashCode(BukkitPlayer.java:749)
    at java.util.WeakHashMap.remove(WeakHashMap.java:543)
    at org.bukkit.plugin.SimplePluginManager.unsubscribeFromDefaultPerms(SimplePluginManager.java:680)
    at org.bukkit.permissions.PermissibleBase.clearPermissions(PermissibleBase.java:179)
    at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:153)
    at org.bukkit.permissions.PermissibleBase.<init>(PermissibleBase.java:31)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntityHuman.<init>(BukkitEntityHuman.java:51)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.<init>(BukkitPlayer.java:109)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.<init>(BukkitPlayer.java:114)
    at keepcalm.mods.bukkit.forgeHandler.BukkitCraftingHandler.onCrafting(BukkitCraftingHandler.java:61)
    at cpw.mods.fml.common.registry.GameRegistry.onItemCrafted(GameRegistry.java:309)
    at sq.a(SlotCrafting.java:118)
    at factorization.common.ItemCraft.craftAt(ItemCraft.java:229)
    at factorization.common.TileEntityStamper.doLogic(TileEntityStamper.java:160)
    at factorization.common.TileEntityFactorization.g(TileEntityFactorization.java:318)

-- Tile entity being ticked --
Details:
    Name: factory_stamper // factorization.common.TileEntityStamper
    Block type: ID #0
    Block data value: Unknown? (Got -1)
    Block location: World: (-152,77,-10171), Chunk: (at 8,4,5 in -10,-636; contains blocks -160,0,-10176 to -145,255,-10161), Region: (-1,-20; contains chunks -32,-640 to -1,-609, blocks -512,0,-10240 to -1,255,-9729)
Stacktrace:
    at yc.h(World.java:2155)
    at in.h(WorldServer.java:516)

-- Affected level --
Details:
    Level name: world
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 677 Drop: 0
    Level seed: 1921637940329527432
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (283,64,296), Chunk: (at 11,4,8 in 17,18; contains blocks 272,0,288 to 287,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 16536309 game time, 10636480 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 19620 (now: false), thunder time: 164667 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

-- System Details --
Details:
    Minecraft Version: 1.4.6
    Operating System: Linux (amd64) version 3.2.0-34-generic
    Java Version: 1.6.0_37, Sun Microsystems Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Sun Microsystems Inc.
    Memory: 4496556616 bytes (4288 MB) / 6174015488 bytes (5888 MB) up to 6174015488 bytes (5888 MB)
    JVM Flags: 2 total; -Xmx6G -Xms6G
    AABB Pool Size: 307 (17192 bytes; 0 MB) allocated, 303 (16968 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 1, tcache: 0, allocated: 1, tallocated: 63
    FML: MCP v7.25 FML v4.6.17.515 Minecraft Forge 6.5.0.489 63 mods loaded, 63 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BlockBreak [Block Break Event](BukkitForge-1.4.7-73.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge [BukkitForge](BukkitForge-1.4.7-73.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    powertools_shared [Power Tools Shared](1.4.6_power_tools_shared_0.1.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    powertools_chunkprotection [Chunk Protection](1.4.6_chunkprotection_0.1.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2 [IndustrialCraft 2](industrialcraft-2_1.112.170-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    AdvancedMachines [IC2 Advanced Machines Addon](AdvancedMachines_4.7a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ChickenChunks [ChickenChunks](ChickenChunks 1.2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ComputerCraft [ComputerCraft](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CCTurtle [ComputerCraft Turtles](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    EnderStorage [EnderStorage](EnderStorage 1.3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ExtrabiomesXL [ExtrabiomesXL](ExtrabiomesXL-universal-1.4.7-3.8.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    factorization [Factorization](Factorization-0.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Core [BuildCraft](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Builders [BC Builders](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Energy [BC Energy](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Factory [BC Factory](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forestry [Forestry for Minecraft](forestry-A-1.7.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Railcraft [Railcraft](Railcraft_1.4.6-6.13.1.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCore [RedPower](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerBase [RP Base](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerMachine [RP Machine](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCompat [RP Compat](RedPowerCompat-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWiring [RP Wiring](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLogic [RP Logic](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLighting [RP Lighting](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWorld [RP World](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerControl [RP Control](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion [Thermal Expansion](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Factory [Factory](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Energy [Energy](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Transport [Transport](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Transport [BC Transport](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Silicon [BC Silicon](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    TwilightForest [The Twilight Forest](twilightforest-1.14.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    XyCraft [XyCraft](xycraft-universal-1.4.6-0.9.44.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    GregTech_Addon [GregTech-Addon](GregTechMod_2.75b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2NuclearControl [Nuclear Control](IC2NuclearControl-1.4.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ModularForceFieldSystem [Modular ForceField System V2](ModularForceFieldSystemV2.2.8.2.14.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    OmniTools [OmniTools](OmniTools-2.2.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PortalGun [Portal Gun](PortalGun1.4.7v2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    SoulShards [SoulShards](SoulShards-v1.26-universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    StevesCarts [Steve's Carts](StevesCarts2.0.0.a42.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Thaumcraft [Thaumcraft](Thaumcraft3.0.1c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    TC [Traincraft](Traincraft-3.1.13_010.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|Core [WR-CBE Core](WR-CBE Core 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|Addons [WR-CBE Addons](WR-CBE Addons 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|RedPower [WR-CBE RedPower](WR-CBE RedPower 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    drceph.petrogen [Petroleum Generator]([1.4.6]PetroGen-1.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BinnieCore [Binnie Core](extrabees-1.4.9.12-prerelease.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ExtraBees [Extra Bees](extrabees-1.4.9.12-prerelease.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    fihgu's Core Mod [fihgu's Core Mod](fihgus Core Mod%282.1.2%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    fihgu's Protection Mod [fihgu's Protection Mod](fihgus Protection Mod%282.1.2%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    fihgu's Teleport Mod [fihgu's Teleport Mod](fihgus Teleport Mod%282.1.2%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IronChest [Iron Chest](ironchest-universal-1.4.7-4.5.2.213.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    MiscPeripherals [MiscPeripherals](miscperipherals-2.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    AdvancedSolarPanel [Advanced Solar Panels](mod_AdvancedSolarPanels_3_3_2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    GraviSuite [Gravitation Suite](mod_zGraviSuite_1_6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ObsidiPlates [Obsidian Pressure Plates](obsidiplates-universal-1.2.0.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge Details: 1.4.6 (Bukkit API version 1.4.5-R0.2)
Plugins Loaded:WorldEdit v5.4.5: Enabled, SimpleRestart v1.3.4: Enabled and Essentials v${build.number}: Enabled
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 34 (1904 bytes; 0 MB) allocated, 34 (1904 bytes; 0 MB) used
    Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)

**Comment by keepcalm** [comment]
Ok. I'll fix that.

**Comment by xfloh22** [comment]
thanks ^^

**Comment by keepcalm** [comment]
Fixed in most recent builds
