### ISSUE TITLE
[Essentials-Chat] Player loses most of incoming chat after death or relog till the next restart.

### ISSUE THREAD

**Issue by Malcanteth** [keepcalm/BukkitForge#208]
Subj. Essentials local chat does not work for "once removed" players, also some plugin messages are not delivered to them.

**Comment by keepcalm** [comment]
"once removed"? Explain further.

**Comment by Malcanteth** [comment]
Checked r50, did not get any better. "Once removed" is "EntityPlayer" was removed from the game (player died or disconnected) and player becomes new entity, that's what I beleive, the source of the problem.

**Comment by Malcanteth** [comment]
r80: fixed, as well as #242
