### ISSUE TITLE
Could not pass event GMUserEvent to Towny v0.82.0.5

### ISSUE THREAD

**Issue by AeroEden** [keepcalm/BukkitForge#210]
Hey I'm still getting this error, I'm using the 21st build on the Technic Jenkins thingy :P
I think its something to do with GroupManager, anyway heres the error
http://pastebin.com/FKXSmZFt
Also I'm having a problem with not getting the starting tools from Essentials
Im using the Essentials-BukkitForge one (3 days ago), or should I be using the older one? (25 days ago) Thanks

**Comment by SpoonsJTD** [comment]
Closed as dupe, another issue captures this problem.
