### ISSUE TITLE
Error with Towny 0.82.0.5 with listeners

### ISSUE THREAD

**Issue by eisterman** [keepcalm/BukkitForge#211]
This error happened to me with the release of 88 BukkitForge on Minecraft Forge API 1.4.6 with version 6.5.0.486

http://pastebin.com/f3yuuGWR

This happens when there is only Towny and when there are other plugins, with or without dependencies.

**Comment by AeroEden** [comment]
Open up the Towny config file and change bypass_version_check to true
That should fix your error :)

**Comment by eisterman** [comment]
I hate this setting... XD Thanks
