### ISSUE TITLE
[Permissions] player.hasPermission not working .... old permission are :\

### ISSUE THREAD

**Issue by Bucky420** [keepcalm/BukkitForge#212]
i have my own plugin that banns items that relies on permissions highly but i use p.haspermission now i look in to another plugin called laggmeter and it hase some code that checks to see if new permission work or not ;\ so here it is 

``` java
  this.history.setMaxSize(averageLength);
    getServer().getScheduler().scheduleSyncRepeatingTask(this, this.poller, 0L, interval);
    if (checkCrapPermissions()) {
      out("Old permissions system detected. Using it.");
      this.crapPermissions = true;
    }
    String loggingMessage = "";
    if (enableLogging) {
      loggingMessage = "  Logging to " + this.logger.getFilename();
    }
    out("Enabled!  Polling every " + interval + " server ticks." + loggingMessage);
  }
  protected boolean permit(Player player, String permission) {
    boolean permit = false;
    if (this.crapPermissions) {
      permit = this.pHandler.permission(player, permission);
    }
    else {
      permit = player.hasPermission(permission);
    }
    return permit;
  }
  private boolean checkCrapPermissions() {
    boolean crap = false;

    Plugin test = getServer().getPluginManager().getPlugin("Permissions");
    if (test != null) {
      crap = true;
      this.pHandler = ((Permissions)test).getHandler();
    }

    return crap;
  }
```

it would be nice if you could get haspermission working please in the meen time ill add this code to my plugin :DDDD hope this helps any one having issues with permissions ... your plugin must use old permission with bukkit forge

**Comment by keepcalm** [comment]
No, BukkitForge uses SuperPerms.Did you give the player permissions in permissions.yml?

**Comment by Bucky420** [comment]
So this is never gona work?    U know almost all plugins use this don't u?
Also I'm using your version of group manager with the bridg

**Comment by SpoonsJTD** [comment]
keepcalm, can you explain the difference between superperms and 'haspermission'? I've determined this to be the problem with the Factions plug-in as well. Seems that haspermission always returns false for anyone but Ops/Admins.

**Comment by SpoonsJTD** [comment]
Ok, I did some more reading. According to this page http://dev.bukkit.org/server-mods/superpermstest/pages/test-results/, player.hasPermission is the correct way to check permissions using superperms.

**Comment by Bucky420** [comment]
:-)  I rly ned this

**Comment by SpoonsJTD** [comment]
codedbgt, can you explain to me more how you handled this? I understand the code you provided except for the cast to 'Permissions' of the test plugin. I can't find that interface or class.

**Comment by SpoonsJTD** [comment]
Found it, TheYeti's Permissions plugin.

**Comment by Bucky420** [comment]
its here take a look http://wiki.nexua.org/Permissions/API/Usage

**Comment by SpoonsJTD** [comment]
I assume if you do this, then perms you've set up in PEX won't work? Do you put the perms in the server file? What in game commands do you use?

I have to say after looking at a lot of plugin code, and I realize it's no fault of keepcalm's, the minecraft community used Notch's code way too much as an example when building stuff like forge and bukkit. This stuff is dying for some nice dependency inversion patterns like service provider/consumers and loosely coupled messaging.

**Comment by Bucky420** [comment]
im using keepcalms essentials and group manager and it only works with the group manager bridge installed as well ... if any thing we just need to make a bridge plugin to hook in to pex and all them other permision plugins and ports them over to the "oldpermissoin" way :D

**Comment by SpoonsJTD** [comment]
I'm not even able to get permissions to work by calling permission plugins directly, bypassing SuperPerms.

**Comment by krim404** [comment]
It's possible using vault to get the perm, but nearly every plugin uses playerInstance.hasPermission();

**Comment by SpoonsJTD** [comment]
Please recheck your perms! Based on some recent changes, perms should be working now, although Pex doesn't seem to be working. I was able to use essentials and bPerms to set perms that then enable users to perform activities. I specifically checked with Factions.

**Comment by krim404** [comment]
Fixed in last commit.
