### ISSUE TITLE
Jenkins requiring login

### ISSUE THREAD

**Issue by Dilski** [keepcalm/BukkitForge#214]
I dont know if it's meant to, but i cant get on the jenkins as it's requiring a login?

**Comment by shakey2** [comment]
Jenkins is having issues again, its been having problems like this for awhile now :(

**Comment by Dilski** [comment]
is there anywhere else i can D/L the latest build?

**Comment by shakey2** [comment]
nope, unless keepcalm uploads latest to github

**Comment by mmis1000** [comment]
ahh.....
It works well for me
I just download it 3 minutes ago
The link on the frontpage of bukkitforge project is working

**Comment by shakey2** [comment]
Look at timestamps mmis, it wasn't working when we posted.
