### ISSUE TITLE
[Essentials-Chat] Chat range buggy ... again

### ISSUE THREAD

**Issue by Thornas88** [keepcalm/BukkitForge#215]
the chat range is buggy show this Issues by Forge Bukkit Plugins https://github.com/Bukkit-Forge-Plugins/Bukkit-Forge-Plugin-Errors/issues/4

please fix that.

**Comment by SpoonsJTD** [comment]
Please recheck this, there have been a number of issues resolved, including a join/rejoin bug.

**Comment by SpoonsJTD** [comment]
No word
