### ISSUE TITLE
WorldEdit don't works and Essentials is reallyyyyyyyyy buggy

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#216]
Hey! I've BukkitForge-1.4.6-0 (and I tested it also with the 1.4.7-21) in my coremods folder, many zip files for ForgeEssentials and tousand other mods in my mods folder and some plugins in my plugins folder.

The really important things, like /sethome and /setwarp dont works!

I'm really sad about WorlEdit.. :( I downloaded WorldEdit 5.4.5 from the BukkitForge Plugin List and when I try to make //wand, there comes "#1. Left click....region...", but I neither become a Wood-Axe, nor can select a region, even if I cheat me a woodaxe!

Please help me :)

Thanks and sorry, if my english is bad!

**Comment by rom3ox** [comment]
I have your same config and world edit is working perfect for me. I can use the /wand command and select with the wand.

why dont you try to select with //pos1 or //hpos1 to test if its a wand problem that conflicts with another plugin like residence or similar?

**Comment by mmis1000** [comment]
Worldedit works well for me(though I found it can't work in end,nether,other world mod make,any change will appear in overworld)
I think there is some mod you use conflict with bukkitforge
I suggest you try again with clear minecraft sv.

**Comment by mmis1000** [comment]
If it is a wand problem,you can change the select tool in the worldedit config

**Comment by keepcalm** [comment]
Remove ForgeEssentials (if you have it installed), and update to a build from [here](http://build.technicpack.net/job/BukkitForge)
