### ISSUE TITLE
[Dimensions] Need a working World-Switch Plugin :S

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#219]
Hey! I need a plugin like Multiverse or MultiWorld, but does it work by you??? I can't create a world, an if i copy the world from my singleplayer saves, i even cannot tp me to the world and i need a farmworld D:

Help mee :(

**Comment by SpoonsJTD** [comment]
tp now works across dimensions. Worlds can't be generated yet, but that issue is captured elsewhere.
