### ISSUE TITLE
More options

### ISSUE THREAD

**Issue by Victor9401** [keepcalm/BukkitForge#220]
Can you add an option in the config to prevent Warning spam
For example
[WARNING] [BukkitForge] Unknown entity: ic2.core.item.tool.EntityMiningLaser - returning a dummy instance of BukkitEntity...
it is really annoying, but i think not so important on the productive server (in this spam i cant find error logs, and ForgeModLoader log is too big...)

**Comment by keepcalm** [comment]
Yes, just ignore it. I'll remove the spam now.
