### ISSUE TITLE
Which WorldGuard's version can I use with BukkitForge N

### ISSUE THREAD

**Issue by nfs4141** [keepcalm/BukkitForge#221]
Hello everyone,

I want to put Worldgurad on my server but the different versions I tested don't woek. Which version can I use ?

Thanks, Nfs4141

**Comment by ghost** [comment]
the newest version works for  me

**Comment by keepcalm** [comment]
The newest version. The reason it doesn't work is because I haven't finished writing a lot of code. But as of the latest build, creeper explosions shouldn't occure anymore :D

**Comment by charlieTheBotDev** [comment]
I just put build 29 on my server to test the creeper explosions and they still cause damage to the environment :/

**Comment by shadoom** [comment]
wg 5.7
bf #67

ftb mindcrack pack;

tnt deny flag doesnt work
