### ISSUE TITLE
LWC >:(

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#222]
Hi! I've problems with LWC! Nothing in the log, but  when i want to open f.e. a chest! It tells me, that there's a critic error, altough i connect it with myiql in the config

**Comment by AeroEden** [comment]
Yea, it doesn't work at the moment.
But the Developer of the Plugin is actually gonna make a LWC version for BukkitForge.
So all you do is wait.

**Comment by SpoonsJTD** [comment]
Closed as dupe - #134
