### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Overload1252** [keepcalm/BukkitForge#224]
I do know that there were quite a few threads about pex not working, but it's my fav permissions handling plugin and I saw that new build was released 2 days ago and so I tried it with 1.4.7 tekkit lite using latest jars etc. (downloaded bukkitforge 1.4.7 from jenkins)
Problem is that regardless of what permission I add it wouldn't have any effect, so is it bug for me or it's for everyone like that? cuz I don't really wanna reroll to groupmanager :S

**Comment by xTsukuyomix** [comment]
same for me. none pex permission seems to register, i removed mywold+ its permission and also tested using mywolrd and its permission, both end on you are not allow to use this command.

**Comment by Overload1252** [comment]
I just tested out groupmanager, it ends up the same for me, no permission works anyways.  Both pex and essentials pack was downloadoaded from here.

**Comment by xTsukuyomix** [comment]
my GM works perfectly, beside for towny which seems to ignore it and trow "commands disable" but essentialsgroupmanagers works fine, even able of prevent placement or use of mining lasers, nukes  itnt and tnt

**Comment by SpoonsJTD** [comment]
Closed as dupe - permissions issue.
