### ISSUE TITLE
Towny not creating area's

### ISSUE THREAD

**Issue by Lightforger** [keepcalm/BukkitForge#225]
Using technic build21, Towny 0.82.0.5

Creating a town/plot works, walking crossing chunk borders does show the correct information of the chunk you are entering (towny/plot/wilderness), but once you stop moving, you instantly change to "wilderness".
/towny map - shows nothing
everything else also acts like you are in wilderness.

**Comment by SpoonsJTD** [comment]
Closed as dupe, another issue captures this.
