### ISSUE TITLE
[AdminCmd] - Most commands

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#227]
Most of the commands in AdminCmd don't work, I imagine that's because the things they need aren't implemented yet, such as firing ghast fire balls etc. however this plugin is really good and I know that it's my favourite for all its features, so if you have the time, please try and make a few things work :+1:  thank you!

Main commands:
/sethome
/home
/setspawn
/spawn
/tp [shortversion of playername]
/tphere [shortversion of playername]

Essentially all the commands that use the short version of the name don't work properly
Also the AFK system doesn't work, as it cannot detect player movement, only player damage

**Comment by ghost** [comment]
Latest version of BukkitForge (30) - Feed the Beast (Direwolf20 pack v3) with a few extra mods running

**Comment by l1nuxfre4k** [comment]
Oh also would like this working :)
Essentials is no good at all, fucks up perms and all so was hoping i could get this to work :D

**Comment by keepcalm** [comment]
Are you _sure_ afk doesn't work - try latest builds. Also, short versions should work, make sure you're using the actual short versions of commands

**Comment by SpoonsJTD** [comment]
These should all be working now due to fixes to playername case and interdimension tp.
