### ISSUE TITLE
[Lockette] doesn't lock chests

### ISSUE THREAD

**Issue by various123** [keepcalm/BukkitForge#229]
When I place the sign on the chest, sign immediately dissapear, while I can place signs on 
doors, trapdoors and blocks which are prescribed in the Lockette config file. But i can't place signs on chests from other mods if they are prescribed in the config file.

**Comment by SpoonsJTD** [comment]
Signs may be fixed now, try the latest build again please (64+).

**Comment by Malcanteth** [comment]
Yes, it is fixed (confirmed by thread opener).
