### ISSUE TITLE
BukkitForge not working with essentials?

### ISSUE THREAD

**Issue by Soos621** [keepcalm/BukkitForge#230]
Hello,
i am using MC 1.4.7
tekkit lite 0.5.2 (was having same problem before tekkit lite update)
and Essentials (minus group manager and chat because it wouldn't let us chat either)
All the latest plugins have been installed, unless jenkins came out with another after .30 lol

 i am having problems with my server, I can't type in any commands! its keeps giving me this error. to my knowledge its saying that bukkitforge cant load essentials commands?

http://pastie.org/5677783

and this is the server.log if ya need it

http://pastie.org/5677718

Thanks!

**Comment by rom3ox** [comment]
I have the same config as you and i can use group manager as permissions manager working perfectly. Also i can use all commands if i am op or have the correct permissions.

Its seems like a problem with your essentials version. Did you try the BukkitForge essentials last version? or at least did you try to delete all essentials config and let it generate again with default config?.

**Comment by Soos621** [comment]
no, i haven't tried that i will though (i have installed multiple fresh copies though)
and yes 
bukkitforge .30
essentials 2.9.6 
i will get back to you about the config file reset.
and thank you for the quick response ^^
