### ISSUE TITLE
worldedit 5.5 is out,seems need a port

### ISSUE THREAD

**Issue by mmis1000** [keepcalm/BukkitForge#231]
worldedit 5.5 is out
Now worldedit have a option to configure if excessive damage value is valid.
This may fix the compatibility with redpower2 since redpower2 use the damage value over 16
However I just test it.
It is obvious the unported worldedit won't work correctly though it doesn't crash at start.
the schematic command doesn't work because it think I haven't chose a region.
but set,replace...etc works

**Comment by shakey2** [comment]
The current ported version isn't fully working yet either.

**Comment by mmis1000** [comment]
ahh...
I knew that,but at least its basic feature works
I rarely use the commands beside replace.stack paste.copy.schematic.set and some shape command.
And the reason I want a ported 5.5 is because it can get the damage value over 16
And some mods like railcraft,redpower use the damage vale over 16
It means some blocks can't be copy by worldedit before will available since this version.
It will be very useful to make a map

**Comment by SpoonsJTD** [comment]
Closing as dupe, other worldedit issues.

**Comment by NNickey** [comment]
Please dont close as a dupe and not supply a link to the other issue.. Thanks.
