### ISSUE TITLE
PermissionsEx - Modifyworld module.

### ISSUE THREAD

**Issue by Lightforger** [keepcalm/BukkitForge#233]
BukkitForge-1.4.7-30 & newest modifyworld

As far as i tested, all restrictions seem to work pretty well, a user with no rights wasn't able to place/destroy/pickup/hold/etc..

However, the permissions that are supposed to give users permissions do not work.
eg, modifyworld.\* or without wildcards,
modifyworld.blocks.interact.2 + modifyworld.blocks.destroy.2
Still doesn't allow a user to do anything (error: "air doesn't fit into grass')

**Comment by Thornas88** [comment]
yes the error came by my too. I have wrote you this problem few days ago and i wait of the fixing of this problem.

**Comment by unrivaledneo** [comment]
there is a setting in the config file, i had this same problem too plugins/essentials/config file and look for EssentialsAntiBuild i set them to false and everyone worked

**Comment by Lightforger** [comment]
unrivaledneo, what versions are you using of bukkitforge, essentials (bukkitforge edit or normal one?) & modifyworld?
I had already changed those values to false, still doesn't work.
Are you using a database for pex?

removed all plugins/mods except BukkitForge, pex & modifyworld, still cannot get it to work
"/pex user <user>" show the person should have the correct permissions.
Tried both bukkitforge pex's as well as the last 3 official pex/modifyworld versions

If possible, could you upload your minecraft_server.jar & pex/modifyworld jar/folders? It would allow me to see exactly what settings are causing it to break :)

**Comment by SpoonsJTD** [comment]
Closed as dupe - captured in #212
