### ISSUE TITLE
Block placement logging/detection.

### ISSUE THREAD

**Issue by Lightforger** [keepcalm/BukkitForge#234]
BukkitForge-1.4.7-30 -  lastest versions of all plugins

Coreprotect does not log/detect any blocks being placed, same for the protection plugin "ChunkOwn".
Worldguard however does correctly deny block placing.

**Comment by Overload1252** [comment]
Have you tried pluging it to mysql?

**Comment by SpoonsJTD** [comment]
Closed as dupe - lack of block event captured in other issue.
