### ISSUE TITLE
[Base] Some files created in desktop

### ISSUE THREAD

**Issue by bilenkonito** [keepcalm/BukkitForge#235]
BukkitForge-1.4.7-30

Plugins loaded: 

No plugins loaded.

Problem: 

When I start the server the permissions.yml and bukkit.yml files are created on the desktop, as well as the /plugins/PlugMetrics

It's happening both at my client and server.

**Comment by keepcalm** [comment]
Are you doing something wrong? this never happens for me. Can't reproduce, can't fix.
