### ISSUE TITLE
[MCMMO] ISSUE

### ISSUE THREAD

**Issue by axzxc1236** [keepcalm/BukkitForge#242]
I am using build #21 and mcmmo build #1152 (Can be found at http://nuclearw.com:8080/job/mcMMO/)
I wanted to use "Mining skill",But right click didn't work.....
I hold a pickaxe!  But "Unarmed skill" happened.

And when I hold everything (besides torch),Unarmed skill is happen.

Should I update ForgeBukkit to build #30 or update mcmmo to build #1174?

Sorry for my bad English.

**Comment by Malcanteth** [comment]
Both updates are not helpful at all, #208 is the same ticket.

**Comment by SpoonsJTD** [comment]
208 doesn't seem related?

**Comment by keepcalm** [comment]
Update to the latest build, post if anything improves

**Comment by Malcanteth** [comment]
Relation is: it happens after you die or rejoin and lasts until the server restart. Checking the state of issue in current build in 3... 2... 1...

**Comment by clienthax** [comment]
Works fine on my server. ima say missconfiguration

**Comment by alexbegt** [comment]
Please any plugin errors put them here: https://github.com/Bukkit-Forge-Plugins/Bukkit-Forge-Plugin-Errors

**Comment by simpman** [comment]
I can confirm that this is still present as of Build 59. It occurs when you use a skill and die, or relogin and lasts until you restart the server. It seems to think any item in hand is the last item you used for a skill. The gaining of XP seems uneffected by this, and correctly gives XP for the tool in hand. I also don't seem to be gaining XP from fishing, and occasionally get an error.to console, I think it is when someone is getting damaged by one of the mobs added by mods, and raises the same exception as Ticket #171 

> Could not pass event EntityDamageByEntityEvent to mcMMO v1.3.13-b1252
> org.bukkit.event.EventException

**Comment by SpoonsJTD** [comment]
Please retry with latest build. A change was made that should fix join/rejoin issues.

**Comment by Malcanteth** [comment]
Close it, this issue is fixed.
