### ISSUE TITLE
CoreProtect ISSUE

### ISSUE THREAD

**Issue by axzxc1236** [keepcalm/BukkitForge#244]
1. Coreprotect didn't record anything.

2.Even OP can't use /co i

I need the fix now........

I am using build#21.
Should I update?

**Comment by MatadorPants** [comment]
Please check your logs before posting this. The latest version of CoreProtect and the latest version of BukkitForge post a log saying CoreProtect was NOT started due to a Bukkit version check.

**Comment by SpoonsJTD** [comment]
Captured in other issues
