### ISSUE TITLE
Votifier

### ISSUE THREAD

**Issue by Overload1252** [keepcalm/BukkitForge#245]
Is it just me or votifier fails to work? I tried to get it to work (I do know how) but it doesnt respond, can anyone confirm that it is working or isn't?

**Comment by nixsy9** [comment]
it works flawlessly for me. I also use a plugin called votifier scripts along side it.

**Comment by Overload1252** [comment]
I solved the prob already, thanks for answer anyways

**Comment by clienthax** [comment]
It works, but sometimes it doesnt give out items (essentials bug?)

**Comment by nixsy9** [comment]
Give this a try with it. Works for my server http://dev.bukkit.org/server-mods/votifierscripts/

**Comment by ghost** [comment]
Can you please let me know how you fixed this. I cant get it to work and I don't get and errors or messages in my console. Not even when I put it in debug mode

**Comment by nixsy9** [comment]
Are you using a listener and have the right port open for the listener?

**Comment by ghost** [comment]
Yes I have tried many listeners as well as listener plugins. I have the port set in config.yml and all the sites say connected successfully. The problem is nothing ever happens after that. No errors or messages in console

**Comment by nixsy9** [comment]
I do not use a listener myself as I use the above votifierscripts But I hear this is a working listener. http://dev.bukkit.org/server-mods/votifier/forum/vote-listeners/47290-vlistener-items-messages-config/

If votifierscripts and votifier with a listener do not work I am unsure how to help.

**Comment by ghost** [comment]
Yeah I have tried both and neither will work. I just never get any notices even though the servers say they connected successfully. Its like it is making it through the port but not getting to votifier or something it is strange.
