### ISSUE TITLE
[Essentials] License violation of "essentials" plugin

### ISSUE THREAD

**Issue by necrodoom** [keepcalm/BukkitForge#246]
see comment on commit https://github.com/keepcalm/BukkitForge/commit/ae1378b8f964dfaa479ea2830639988ef581bc31

**Comment by Erycus** [comment]
This has already been noted, as you referenced.  So close this 'issue' because it is not an issue.  You are wasting space.

**Comment by SpoonsJTD** [comment]
I recommend we keep open until Essentials port is compliant.
