### ISSUE TITLE
[Traincraft] Entity Dummy instance failed

### ISSUE THREAD

**Issue by profjb** [keepcalm/BukkitForge#248]
src.train.common.entity.rollingStock.EntityPassengerSeat - returning a dummy instance of BukkitEntity...

Is the main problem.

however here is the crash report anyway:

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 1/14/13 6:32 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/lwjgl/input/Keyboard
    at src.train.common.api.AbstractWorkCart.pressKeyClient(AbstractWorkCart.java:55)
    at src.train.common.api.AbstractWorkCart.j_(AbstractWorkCart.java:29)
    at src.train.common.entity.rollingStock.EntityMailWagen_DB.j_(EntityMailWagen_DB.java:161)
    at yc.a(World.java:2295)
    at in.b(WorldServer.java:656)
    at iv.a(NetServerHandler.java:239)
    at eb.a(SourceFile:136)
    at cg.b(TcpConnection.java:454)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.input.Keyboard
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:93)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 16 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.4.6
    Operating System: Linux (amd64) version 2.6.32-5-amd64
    Java Version: 1.7.0_09, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 302680392 bytes (288 MB) / 734081024 bytes (700 MB) up to 2077753344 bytes (1981 MB)
    JVM Flags: 8 total; -Xincgc -Xmx2048M -XX:PermSize=256M -XX:MaxPermSize=512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=8 -XX:+AggressiveOpts
    AABB Pool Size: 7880 (441280 bytes; 0 MB) allocated, 7000 (392000 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    FML: MCP v7.25 FML v4.6.17.515 Minecraft Forge 6.5.0.489 62 mods loaded, 62 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BlockBreak [Block Break Event](BukkitForge-1.4.7-CUSTOM_BUILD.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge [BukkitForge](BukkitForge-1.4.7-CUSTOM_BUILD.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2 [IndustrialCraft 2](industrialcraft-2_1.112.170-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    AdvancedMachines [IC2 Advanced Machines Addon](AdvancedMachines_4.7a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ChickenChunks [ChickenChunks](ChickenChunks 1.2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ComputerCraft [ComputerCraft](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CCTurtle [ComputerCraft Turtles](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    EnderStorage [EnderStorage](EnderStorage 1.3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ExtrabiomesXL [ExtrabiomesXL](ExtrabiomesXL-universal-1.4.6-3.7.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    factorization [Factorization](Factorization-0.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Core [BuildCraft](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Builders [BC Builders](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Energy [BC Energy](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Factory [BC Factory](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forestry [Forestry for Minecraft](forestry-A-1.6.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Railcraft [Railcraft](Railcraft_1.4.6-6.12.2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCore [RedPower](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerBase [RP Base](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerMachine [RP Machine](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCompat [RP Compat](RedPowerCompat-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWiring [RP Wiring](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLogic [RP Logic](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLighting [RP Lighting](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWorld [RP World](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerControl [RP Control](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion [Thermal Expansion](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Factory [Factory](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Energy [Energy](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Transport [Transport](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Transport [BC Transport](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Silicon [BC Silicon](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    TwilightForest [The Twilight Forest](twilightforest-1.14.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    XyCraft [XyCraft](xycraft-universal-1.4.6-0.9.44.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    GregTech_Addon [GregTech-Addon](GregTechMod_2.73c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2NuclearControl [Nuclear Control](IC2NuclearControl-1.4.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ModularForceFieldSystem [Modular ForceField System V2](ModularForceFieldSystemV2.2.8.2.14.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    OmniTools [OmniTools](OmniTools-2.2.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    SoulShards [SoulShards](SoulShards-v1.21-universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    StevesCarts [Steve's Carts](StevesCarts2.0.0.a41.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Thaumcraft [Thaumcraft](Thaumcraft3.0.1c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    TickThreading [TickThreading](TickThreading-1.4.6-1.0.0.290 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    TC [Traincraft](Traincraft-3.1.13_010.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|Core [WR-CBE Core](WR-CBE Core 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|Addons [WR-CBE Addons](WR-CBE Addons 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|RedPower [WR-CBE RedPower](WR-CBE RedPower 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    drceph.petrogen [Petroleum Generator]([1.4.6]PetroGen-1.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BinnieCore [Binnie Core](extrabees-1.4.9.6-prerelease.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ExtraBees [Extra Bees](extrabees-1.4.9.6-prerelease.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    fihgu's Core Mod [fihgu's Core Mod](fihgus Core Mod%282.1.2%29 %281%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    fihgu's Protection Mod [fihgu's Protection Mod](fihgus Protection Mod%282.1.2%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    fihgu's Teleport Mod [fihgu's Teleport Mod](fihgus Teleport Mod%282.1.2%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IronChest [Iron Chest](ironchest-universal-1.4.6-4.5.1.203.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    MiscPeripherals [MiscPeripherals](miscperipherals-2.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    AdvancedSolarPanel [Advanced Solar Panels](mod_AdvancedSolarPanels_3_3_2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    GraviSuite [Gravitation Suite](mod_zGraviSuite_1_6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ObsidiPlates [Obsidian Pressure Plates](obsidiplates-universal-1.2.0.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PortalGun [Portal Gun](portalgun1.4.6v2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge Details: 1.4.6 (Bukkit API version 1.4.5-R0.2)
Plugins Loaded:WorldBorder v1.6.1: Enabled, Vault v1.2.22-b277: Enabled, ScheduledAnnouncer2 v2.5.2 - For 1.4: Enabled, ClearLag v1.7.0: Enabled, PermissionsEx v1.19.5: Enabled, WorldEdit v5.4.5: Enabled and HawkEye v1.1.0: Enabled
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 3223 (180488 bytes; 0 MB) allocated, 3063 (171528 bytes; 0 MB) used
    Player Count: 4 / 35; [iq['BMAco1'/4597, l='Terrabit', x=-209.50, y=63.85, z=-716.50], iq['DarkyFox132'/16679, l='Terrabit', x=-210.64, y=68.64, z=-711.78], iq['nxsupert'/34515, l='Terrabit', x=250.92, y=67.00, z=-42.49], iq['Misserdk'/31587, l='Terrabit', x=2814.14, y=74.00, z=-46.50]]
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)

**Comment by keepcalm** [comment]
Trainmod issue!

```
java.lang.NoClassDefFoundError: org/lwjgl/input/Keyboard
at src.train.common.api.AbstractWorkCart.pressKeyClient(AbstractWorkCart.java:55)
at src.train.common.api.AbstractWorkCart.j_(AbstractWorkCart.java:29)
at src.train.common.entity.rollingStock.EntityMailWagen_DB.j_(EntityMailWagen_DB.java:161)
at yc.a(World.java:2295)
at in.b(WorldServer.java:656)
at iv.a(NetServerHandler.java:239)
at eb.a(SourceFile:136)
at cg.b(TcpConnection.java:454)
at iv.d(NetServerHandler.java:136)
at iw.b(NetworkListenThread.java:57)
at ht.b(SourceFile:30)
at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
at ho.r(DedicatedServer.java:270)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
at fy.run(SourceFile:849)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.input.Keyboard
at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:93)
at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
... 16 more
```

I see no keepcalms...
