### ISSUE TITLE
permissions,working

### ISSUE THREAD

**Issue by xTsukuyomix** [keepcalm/BukkitForge#253]
well i found out that groupmanager and pex permission to not be enabling for some plugins, however plugins do obey the file permissions.yml from bukkit it self.
i tested and well permissions set there, get enabled for comands
like towny comands,

**Comment by HypnoTherapist** [comment]
can you elaborate further?  are you still using a permissions plugin? what does your bukkit permissions.yml look like. what plugins work now because of that?

**Comment by xTsukuyomix** [comment]
sorry for the not so clear response,
at this moment, this way fix "towny using permissions" issue, towny is still nonfunctional, you can not claim more land beside making home block, however it open a place for other plugins like shop plugins.
at this moment i am using a plugin called commandshop, without using bukkitpermission, you can not buy or sell without OP. with this , users can buy and sell. about permissions yes i am still using GroupManager for handling the rest of plugins. 
here a useful link http://wiki.bukkit.org/Permissions.yml
i think we could manage these nodes with GM but it don't explain how to.

**Comment by SpoonsJTD** [comment]
Dupe
