### ISSUE TITLE
bukkitforge not forwarding perms (honeypot plugin)

### ISSUE THREAD

**Issue by shakey2** [keepcalm/BukkitForge#254]
I try using group manager to give myself permissions to use honeypot command using the nodes on the honeypot bukkit page, but its just giving me permission errors. I also tried Pex but I can't seem to get that to give me any permissions. Also none of the essentials.build nodes seem work with group manager.

**Comment by xTsukuyomix** [comment]
if you are using essentials.build.  Make sure you disable Build from groups on worlds settings. you will see like "Build: true" make it false and it will obey essentials.build

**Comment by MatadorPants** [comment]
Has anyone gotten Essentials GroupManager or PEX to work correctly? Neither seem to work whatsoever for me.

**Comment by l1nuxfre4k** [comment]
had major issues with it.
I got YAPP to semi work on my server with some smaller issues still, but would rather have pex or bperm.
Seems to be an issue with Essentials+ other perm plugins, its like essentials dont give out perm even if pex or bperm says the user have.
Tried multiple solutions with no luck, on new servers.

**Comment by shakey2** [comment]
Tsukuyomix all that does is make it so that rank can't destroy/place any blocks

**Comment by xTsukuyomix** [comment]
not really, if you make build : false and you add like what i use
- -essentials.build.interact.30208
- essentials.build.\*  

what it does? it prevent the players from using mining lasers with build : true this nodes get ignored and player can use mining laser.
of course player with build.\* will be able of use all other items that arent blacklisted like air xD

**Comment by shakey2** [comment]
I tried that they didn't have permission to build at all.

**Comment by shakey2** [comment]
nvm fixed it, was missing a line. Still doesn't fix honeypot unfortunately :(

**Comment by SpoonsJTD** [comment]
Dupe
