### ISSUE TITLE
Mix of issues/bugs im experencing, Mindcrack v7+ bukkitforge + pex/bperm + essentials

### ISSUE THREAD

**Issue by l1nuxfre4k** [keepcalm/BukkitForge#255]
Hi all :)
Ok im having major issues with permissions on my server.
I´ve tried setting up a fresh test server with mindcrack and bukkitforge and only plugins are ess+pex(also tested bperm)
I set it up as it should, pex and bperm says i got permissions but essentials refuse to work with them....
15.01 18:38:08 [Server] INFO [com.earth2me.essentials.Essentials] [Essentials] checking if Humbug911 has essentials.mail - false
Those errors i keep getting whatever command i try from essentials, commands from other plugins work fine.

Anybody got suggestions? because im clueless why this is so fucked up for me :p
had issues with the group manager also so donno what to do to get a working plugin for perms...
I´ve been looking into switching from essentials, but cant find a working alternative, anybody knows one?

**Comment by MatadorPants** [comment]
It's been reported repeatedly that permissions are not working correctly at this time. We'll have to wait until keepcalm gets back for it to be fixed.

**Comment by SpoonsJTD** [comment]
Dupe
