### ISSUE TITLE
crash with bukkit4vanilla-1.4.5-2

### ISSUE THREAD

**Issue by Mceonith** [keepcalm/BukkitForge#26]
Crash report with using bukkit4vanilla-1.4.5-2. the Server Loads up great, but the minute you break or place a block this is the crash report. I tried using the blockbreak in with the coremods, and the second crash report happens immediately.

hopefully this was done correctly
[spoiler]
    ---- Minecraft Crash Report ----
    // This doesn't make any sense!

```
Time: 12/17/12 12:05 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: iq.h(F)Laob;
        at keepcalm.mods.bukkit.forgeHandler.PlayerUtilities.getTargetBlock(PlayerUtilities.java:17)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.playerSaysHai(ForgeEventHandler.java:220)
        at net.minecraftforge.event.ASMEventHandler_17_ForgeEventHandler_playerSaysHai_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:28)
        at ir.a(ItemInWorldManager.java:386)
        at iv.a(NetServerHandler.java:579)
        at fl.a(SourceFile:58)
        at cg.b(TcpConnection.java:455)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:701)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:597)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:496)
        at fy.run(SourceFile:856)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.4.5
        Operating System: Windows 7 (x86) version 6.1
        Java Version: 1.7.0_09, Oracle Corporation
        Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
        Memory: 453913912 bytes (432 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
        JVM Flags: 2 total; -Xms512M -Xmx1024M
        AABB Pool Size: 3989 (223384 bytes; 0 MB) allocated, 2655 (148680 bytes; 0 MB) used
        Suspicious classes: FML and Forge are installed
        IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 63
        FML: MCP v7.23 FML v4.5.62.495 Minecraft Forge 6.4.2.446 8 mods loaded, 8 mods active
        mcp [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
        FML [Forge Mod Loader] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
        Forge [Minecraft Forge] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
        Bukkit4Vanilla [Bukkit For Vanilla] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
        mod_CodeChickenCore [CodeChicken Core] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
        mod_NotEnoughItems [Not Enough Items] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
        BlockBreak [Block Break Event] (bukkit4vanilla-1.4.5-2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
        Forestry [Forestry for Minecraft] (forestry-A-1.6.2.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
        Bukkit4Vanilla Details: ~~NULL~~
        Profiler Position: N/A (disabled)
        Vec3 Pool Size: 899 (50344 bytes; 0 MB) allocated, 707 (39592 bytes; 0 MB) used
        Player Count: 1 / 20; [iq['Mceonith'/319, l='world', x=-173.72, y=65.00, z=235.04]]
        Is Modded: Definitely; Server brand changed to 'fml'
        Type: Dedicated Server (map_server.txt)
```

[/spoiler]

The following is with the blockbreak blockbreak-1.4.5-0

[spoiler]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 12/17/12 6:17 AM
Description: Exception in server tick loop

cpw.mods.fml.common.DuplicateModsFoundException
    at cpw.mods.fml.common.Loader.identifyDuplicates(Loader.java:374)
    at cpw.mods.fml.common.Loader.identifyMods(Loader.java:335)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:457)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:344)
    at ho.c(DedicatedServer.java:64)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:457)
    at fy.run(SourceFile:856)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.4.5
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.7.0_09, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 464314200 bytes (442 MB) / 518979584 bytes (494 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 2 total; -Xms512M -Xmx1024M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.23 FML v4.5.62.495 Minecraft Forge 6.4.2.446 9 mods loaded, 0 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) 
    FML [Forge Mod Loader](coremods) 
    Forge [Minecraft Forge](coremods) 
    Bukkit4Vanilla [Bukkit For Vanilla](coremods) 
    mod_CodeChickenCore [CodeChicken Core](coremods) 
    mod_NotEnoughItems [Not Enough Items](coremods) 
    BlockBreak [Block Break Event](blockbreak-1.4.5-0.jar) 
    BlockBreak [Block Break Event](bukkit4vanilla-1.4.5-2.jar) 
    Forestry [Forestry for Minecraft](forestry-A-1.6.2.7.jar) 
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)
[/spoiler]

**Comment by soulgriever** [comment]
is this before or after commit https://github.com/keepcalm/BukkitForge/commit/0b16802521218f58c36d0a9b0039112eaa4d9f23 I think he fixed this in recent code change just hasnt updated the distribute yet

**Comment by Mceonith** [comment]
Honestly don't know.. i grabbed the file from https://github.com/keepcalm/BukkitForge/downloads and the blockbreak was https://github.com/downloads/keepcalm/BlockBreak/blockbreak-1.4.5-0.jar so not sure if these are after or before.

**Comment by keepcalm** [comment]
Yes, I fixed it, I'm just testing this new version. I'll release it in the next hour.
