### ISSUE TITLE
Summary of known bugs - READ ME FIRST

### ISSUE THREAD

**Issue by keepcalm** [keepcalm/BukkitForge#27]
This issue is a list of known bugs.

MAKE SURE YOU ARE USING THE LATEST BUILD FROM [JENKINS](http://build.aegisgaming.org/job/BukkitForge) BEFORE POSTING AN ISSUE!

**1.4.6-x**
- **WorldEdit**
  - //regen doesn't work. And probably never will. Sorry ;)

**Comment by Wolftein** [comment]
Fixed everything!

**Comment by Ev3rM0r3** [comment]
Worldedit does not copy/paste elorams half blocks.  In 1.2.5 I was able to do this with worldedit.  Is there any chance you could update the functionality to match there current build?

**Comment by mmis1000** [comment]
damage value over 16 seems will support again with worldedit 5.4.6
It may make rp block support again in 1.4.6
Now just wait for it to release.
