### ISSUE TITLE
[Factions 1.8] player move event issue? 

### ISSUE THREAD

**Issue by Bucky420** [keepcalm/BukkitForge#275]
im shrue you can test it for your self but load up factions and make a few factions and claims ... safezones do it for shure ... when you move chunks and then stop it will say your in a safezone chunk or another persons faction this happens every time you change chunks and then stop in a chunk ... i plan on decompiling factions and just removing this bit of code ;\ as it is very anoying

**Comment by SpoonsJTD** [comment]
Keepcalm, after doing some testing, it looks like Forge fires three types of PlayerMoveEvents: 1) while the player is moving old and now are what you would expect, 2) while the player is sitting still, old and now are the user's current location, and 3) when the player stops after moving, old is the current location, now is (0,0,0). 

It's 3 that is messing up things like Factions and Towny that have areas.

The following guard seems to fix it for me, but I don't know if it'll break something else:

```

                    if( ev.newX == 0 && ev.newY == 0 && ev.newZ == 0 )
        {
            // Invalid move event
            return;
        }


                                   Bukkit.getPluginManager().callEvent(bev);

```

**Comment by keepcalm** [comment]
Thanks @SpoonsJTD :D
