### ISSUE TITLE
Duplicates of all plugins being created on load

### ISSUE THREAD

**Issue by charlieTheBotDev** [keepcalm/BukkitForge#277]
I'm not sure if this is intentional and I've missed something or if I've broken something but now whenever I start the server all my plugins get duplicated with ported_ at the start, doubling the space needed for my plugins.

Do I need both copies of all the plugins? If not, does this mean I can delete the plugin.jar and just keep the ported_ version?

**Comment by ruifung** [comment]
The ported_ plugins are created automatically by the built in SRG Remapper.

**Comment by charlieTheBotDev** [comment]
Does that mean I can delete the original ones?

**Comment by keepcalm** [comment]
Yep, but it won't load them, so it doesn't really matter.
