### ISSUE TITLE
[Essentials] AFK no more

### ISSUE THREAD

**Issue by Malcanteth** [keepcalm/BukkitForge#278]
Before r50 I used r30 and it left only one way to appear as "active" player - chat, silent players were marked es AFK and kicked afret timeout. r50 changed the thing a lot - now i can never be AFK, even when I use /afk command, I get back to "active" state immediately.

I still use the Essentials port downloaded from here.

**Comment by dedo1911** [comment]
I had this problem with r30. Updated right now @ r60 and still having the same issue.

**Comment by shakey2** [comment]
Use the official essentials from the bukkit website. Not sure if it fixes that but keepcalm made it so you don't need the ported version of anything anymore except for the PEX port.

**Comment by dedo1911** [comment]
Still same issue with latest everything.

**Comment by Malcanteth** [comment]
r80: fixed
