### ISSUE TITLE
BiomeGenBase Warning

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#28]
I'm assuming this is the fix you applied for the previous issue, so instead of crashing it spits out an error. I typed /jumpto with extra biomes installed. Didn't crash anything, just reporting it in case it isn't known. 

18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[59] - The Biome missing is Woodlands
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[58] - The Biome missing is Wasteland
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[57] - The Biome missing is Tundra
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[56] - The Biome missing is Temperate Rainforest
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[55] - The Biome missing is Snowy Rainforest
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[54] - The Biome missing is Snow Forest
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[53] - The Biome missing is Shrubland
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[52] - The Biome missing is Savanna
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[51] - The Biome missing is Lush Redwoods
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[50] - The Biome missing is Redwood Forest
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[49] - The Biome missing is Rainforest
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[48] - The Biome missing is Pine Forest
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[47] - The Biome missing is Mountain Taiga
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[46] - The Biome missing is Mountain Ridge
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[45] - The Biome missing is Mountainous Desert
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[44] - The Biome missing is Mini Jungle
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[43] - The Biome missing is Meadow
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[42] - The Biome missing is Marsh
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[41] - The Biome missing is Ice Wasteland
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[40] - The Biome missing is Green Swamplands
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[39] - The Biome missing is Green Hills
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[38] - The Biome missing is Glacier
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[37] - The Biome missing is Forested Island
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[36] - The Biome missing is Forested Hills
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[35] - The Biome missing is Extreme Jungle
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[34] - The Biome missing is Birch Forest
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[33] - The Biome missing is Autumn Woods
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[32] - The Biome missing is Alpine
18.12 08:46:17 [Server] WARNING Missing Biome mapping for BiomeGenBase[20] - The Biome missing is Extreme Hills Edge

**Comment by keepcalm** [comment]
Yea, not worried about that. I am working on a solution. But for now, just ignore it ;)
