### ISSUE TITLE
[TARDIS] Problem with TARDIS Plugin (Attempt to register while not enabled)

### ISSUE THREAD

**Issue by zambony** [keepcalm/BukkitForge#284]
TARDIS plugin says it can't find support for this version of CraftBukkit.
Version of BukkitForge - 1.4.7-60
Version of Forge - 471
Error log from console: http://pastebin.com/De9nvtQ0
Forge Modloader Server-0.log: http://pastebin.com/S122pqMt
Cause: Starting up the server, refuses to load. Commands are listed, but upon the usage of /plugins you can see that 'TARDIS' is in red. Doesn't work, simple as that.

**Comment by keepcalm** [comment]
That FML log doesn't mention tardis. Try changing the CB version in BukkitForge.cfg

**Comment by zambony** [comment]
I attempted to change it to S:bukkitVersionString=git-BukkitForge-1.4.6-R0.3-b2586. But that didn't work. I probably am doing it wrong though. The plugin always gives me the same error in the console though, and it's meant for CB 1.4.6-R0.3
Also, this Forge log mentions tardis. It's server log 1. http://pastebin.com/Y4b7AFk5

**Comment by zambony** [comment]
The plugin creator updated the plugin, but even that didn't work. Here is a screenshot of the error. Seems a bit different to me. http://puu.sh/1QiDu

**Comment by alexbegt** [comment]
I fixed this a bit

**Comment by alexbegt** [comment]
Fixed
