### ISSUE TITLE
Worldedit Issue, Important For Us T.T

### ISSUE THREAD

**Issue by UGLHong** [keepcalm/BukkitForge#285]
java.lang.NoClassDefFoundError: net/minecraft/server/Block

whenever i do any worldedit command that need to set block or replace block.
im using build #62 of your Bukkit Forge Mods and also tested with your ported worldedit 5.4.5 and also original worldedit 5.4.5.

keepcalm please save my world, save my day T.T thanks alot !

**Comment by keepcalm** [comment]
Use the latest build and use WE 5.5 - I've tested them.

**Comment by lohtonghong** [comment]
Thanks !
