### ISSUE TITLE
"PlayerCommandPreprocess" Event

### ISSUE THREAD

**Issue by lihad** [keepcalm/BukkitForge#287]
Judging by the code, I take you all haven't gotten to this one yet.  But just in case, Im posting it as an issue.  Would be great for plugins such as MCDocs to get this running.  Thanks :)

**Comment by keepcalm** [comment]
Look in ForgeEventHandler.java, line 553-ish

**Comment by lihad** [comment]
Ah! There it is, thank you for that.  However, it looks like it may not be working as intended then.  The following test never prints anything to console.  Running build 61.

@EventHandler
    public void onPlayerCommandPreprocess(PlayerCommandPreprocessEvent event){
        System.out.println("OnCommandPre"+event.getMessage());
}

**Comment by SpoonsJTD** [comment]
Try now
