### ISSUE TITLE
[OpenInv] Plugins not loading?

### ISSUE THREAD

**Issue by Wolfgunner359** [keepcalm/BukkitForge#288]
I'm currently trying to use OpenInv, a bukkit plugin.
On the console it comes up with some BukkitForge stuff

[BukkitForge]Loaded plugins:
OpenInv- Enabled: false
PermissionsEx- enabled: true
Modifyworld-enabled: true
MyHome-enabled: true
ChatManager-enabled:true

Note: - I'm running a FTB server
        - It also creates ported_(plugin_name) under plugins, including the disabled plugins.
Any idea why it's been disabled / not working?

[OpenInv] Enabling OpenInv v1.9.6
2013-01-20 17:37:12 [INFO] [OpenInv] Your version of CraftBukkit is not supported.
2013-01-20 17:37:12 [INFO] [OpenInv] Please look for an updated version of OpenInv
[OpenInv] Disabling OpenInv v1.9.6

**Comment by keepcalm** [comment]
Nope. Does it say anything?

ported_(plugin_name) is plugins which have been run through the auto-porter (to make sure it's compatible with BukkitForge). You can safely delete the other plugin files.

**Comment by Wolfgunner359** [comment]
Hmm, nothing really. I'm using the latest version of the plugin available.
What did you mean by "Does it say anything", what were you referring to?

**Comment by Wolfgunner359** [comment]
I just found something that is odd...
Minecraft.OpenInv : Your version of CraftBukkit is not supported.
then I get Minecraft.OpenInv : Please look for an updated version of OpenInv.
I'm using latest version of Bukkit forge (63) and using latest version of OpenInv.......

**Comment by keepcalm** [comment]
In BukkitForge.cfg, there's an option which lets you set the CraftBukkit version. Change the 3000 to the build of CB it is for.

**Comment by Wolfgunner359** [comment]
If by that you mean 
"general {
    # The CraftBukkit version to pretend to be" 
It's set at
S:BukkitVersionString=git-BukkitForge-1.4.5-R1.0-b3000 jnks
(Really: BukkitForge for MC 1.4.6)

I tried with the 1.4.5 versions, yet no success...

I don't see there being a problem with the plugin as it works fine for me on vanilla...
Thanks for your help! Hope to hear back soon!

Note: it is not solved.

**Comment by SpoonsJTD** [comment]
Look at the OpenInv code and see what version it needs to be. If that doesn't work, check with the OpenInv people about creating a config to allow for disabling the version check.

**Comment by Wolfgunner359** [comment]
aight, thanks for the help! Keep up the good work!
