### ISSUE TITLE
[Base-GetItemOnCursor] InventoryClickEvent & CraftItemEvent NPE Issue

### ISSUE THREAD

**Issue by lihad** [keepcalm/BukkitForge#289]
When 'InventoryClickEvent' or 'CraftItemEvent' calls 'getItemOnCursor()', an NPE occurs.

**Comment by SpoonsJTD** [comment]
Plugin? log? steps to reproduce?

**Comment by SpoonsJTD** [comment]
I believe this is fixed, please check.
