### ISSUE TITLE
Worldedit Issues

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#29]
If you try to use a wooden axe to select regions, nothing happens. If you type //pos1, it spits out

First position set to null. 

Does the same for pos2 and doesn't make a selection. 

Also tried to make a sphere out of stone. 

18.12 08:55:12 [Server] INFO    at fy.run(SourceFile:856)
18.12 08:55:12 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
18.12 08:55:12 [Server] INFO    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
18.12 08:55:12 [Server] INFO    at ho.r(DedicatedServer.java:252)
18.12 08:55:12 [Server] INFO    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:696)
18.12 08:55:12 [Server] INFO    at ht.b(SourceFile:30)
18.12 08:55:12 [Server] INFO    at iw.b(NetworkListenThread.java:55)
18.12 08:55:12 [Server] INFO    at iv.d(NetServerHandler.java:82)
18.12 08:55:12 [Server] INFO    at cg.b(TcpConnection.java:451)
18.12 08:55:12 [Server] INFO    at cv.a(SourceFile:44)
18.12 08:55:12 [Server] INFO    at iv.a(NetServerHandler.java:681)
18.12 08:55:12 [Server] INFO    at iv.d(NetServerHandler.java:715)
18.12 08:55:12 [Server] INFO    at x.a(CommandHandler.java:81)
18.12 08:55:12 [Server] INFO    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:96)
18.12 08:55:12 [Server] INFO    at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52)
18.12 08:55:12 [Server] INFO    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:197)
18.12 08:55:12 [Server] INFO    at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1339)
18.12 08:55:12 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:425)
18.12 08:55:12 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:509)
18.12 08:55:12 [Server] INFO    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:172)
18.12 08:55:12 [Server] INFO    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:241)
18.12 08:55:12 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:522)
18.12 08:55:12 [Server] INFO    at java.lang.reflect.Method.invoke(Method.java:601)
18.12 08:55:12 [Server] INFO    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18.12 08:55:12 [Server] INFO    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
18.12 08:55:12 [Server] INFO    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18.12 08:55:12 [Server] INFO    at com.sk89q.worldedit.commands.GenerationCommands.sphere(GenerationCommands.java:204)
18.12 08:55:12 [Server] INFO    at com.sk89q.worldedit.WorldEdit.getBlockPattern(WorldEdit.java:608)
18.12 08:55:12 [Server] INFO    at com.sk89q.worldedit.WorldEdit.getBlock(WorldEdit.java:549)
18.12 08:55:12 [Server] INFO    at com.sk89q.worldedit.WorldEdit.getBlock(WorldEdit.java:355)
18.12 08:55:12 [Server] INFO    at com.sk89q.worldedit.WorldEdit.getBlock(WorldEdit.java:414)
18.12 08:55:12 [Server] INFO    at com.sk89q.worldedit.bukkit.BukkitWorld.isValidBlockType(BukkitWorld.java:872)
18.12 08:55:12 [Server] INFO java.lang.NoClassDefFoundError: net/minecraft/server/Block
18.12 08:54:57 [Server] INFO    ... 32 more
18.12 08:54:57 [Server] INFO    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
18.12 08:54:57 [Server] INFO    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
18.12 08:54:57 [Server] INFO    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:34)
18.12 08:54:57 [Server] INFO    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:40)
18.12 08:54:57 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.Block
18.12 08:54:57 [Server] INFO    at fy.run(SourceFile:856)
18.12 08:54:57 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
18.12 08:54:57 [Server] INFO    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
18.12 08:54:57 [Server] INFO    at ho.r(DedicatedServer.java:252)
18.12 08:54:57 [Server] INFO    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:696)
18.12 08:54:57 [Server] INFO    at ht.b(SourceFile:30)
18.12 08:54:57 [Server] INFO    at iw.b(NetworkListenThread.java:55)
18.12 08:54:57 [Server] INFO    at iv.d(NetServerHandler.java:82)
18.12 08:54:57 [Server] INFO    at cg.b(TcpConnection.java:451)
18.12 08:54:57 [Server] INFO    at cv.a(SourceFile:44)
18.12 08:54:57 [Server] INFO    at iv.a(NetServerHandler.java:681)
18.12 08:54:57 [Server] INFO    at iv.d(NetServerHandler.java:715)
18.12 08:54:57 [Server] INFO    at x.a(CommandHandler.java:81)
18.12 08:54:57 [Server] INFO    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:96)
18.12 08:54:57 [Server] INFO    at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52)
18.12 08:54:57 [Server] INFO    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:197)
18.12 08:54:57 [Server] INFO    at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1339)
18.12 08:54:57 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:425)
18.12 08:54:57 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:509)
18.12 08:54:57 [Server] INFO    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:172)
18.12 08:54:57 [Server] INFO    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:241)
18.12 08:54:57 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:522)
18.12 08:54:57 [Server] INFO    at java.lang.reflect.Method.invoke(Method.java:601)
18.12 08:54:57 [Server] INFO    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18.12 08:54:57 [Server] INFO    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
18.12 08:54:57 [Server] INFO    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18.12 08:54:57 [Server] INFO    at com.sk89q.worldedit.commands.GenerationCommands.sphere(GenerationCommands.java:204)
18.12 08:54:57 [Server] INFO    at com.sk89q.worldedit.WorldEdit.getBlockPattern(WorldEdit.java:608)
18.12 08:54:57 [Server] INFO    at com.sk89q.worldedit.WorldEdit.getBlock(WorldEdit.java:549)
18.12 08:54:57 [Server] INFO    at com.sk89q.worldedit.WorldEdit.getBlock(WorldEdit.java:355)
18.12 08:54:57 [Server] INFO    at com.sk89q.worldedit.WorldEdit.getBlock(WorldEdit.java:414)
18.12 08:54:57 [Server] INFO    at com.sk89q.worldedit.bukkit.BukkitWorld.isValidBlockType(BukkitWorld.java:872)
18.12 08:54:57 [Server] INFO java.lang.NoClassDefFoundError: net/minecraft/server/Block

Tried to use /butcher

18.12 09:01:26 [Server] INFO    at fy.run(SourceFile:856)
18.12 09:01:26 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
18.12 09:01:26 [Server] INFO    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
18.12 09:01:26 [Server] INFO    at ho.r(DedicatedServer.java:252)
18.12 09:01:26 [Server] INFO    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:696)
18.12 09:01:26 [Server] INFO    at ht.b(SourceFile:30)
18.12 09:01:26 [Server] INFO    at iw.b(NetworkListenThread.java:55)
18.12 09:01:26 [Server] INFO    at iv.d(NetServerHandler.java:82)
18.12 09:01:26 [Server] INFO    at cg.b(TcpConnection.java:451)
18.12 09:01:26 [Server] INFO    at cv.a(SourceFile:44)
18.12 09:01:26 [Server] INFO    at iv.a(NetServerHandler.java:681)
18.12 09:01:26 [Server] INFO    at iv.d(NetServerHandler.java:715)
18.12 09:01:26 [Server] INFO    at x.a(CommandHandler.java:81)
18.12 09:01:26 [Server] INFO    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:96)
18.12 09:01:26 [Server] INFO    at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52)
18.12 09:01:26 [Server] INFO    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:197)
18.12 09:01:26 [Server] INFO    at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1339)
18.12 09:01:26 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:425)
18.12 09:01:26 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:509)
18.12 09:01:26 [Server] INFO    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:172)
18.12 09:01:26 [Server] INFO    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:241)
18.12 09:01:26 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:522)
18.12 09:01:26 [Server] INFO    at java.lang.reflect.Method.invoke(Method.java:601)
18.12 09:01:26 [Server] INFO    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18.12 09:01:26 [Server] INFO    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
18.12 09:01:26 [Server] INFO    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18.12 09:01:26 [Server] INFO    at com.sk89q.worldedit.commands.UtilityCommands.butcher(UtilityCommands.java:395)
18.12 09:01:26 [Server] INFO    at com.sk89q.worldedit.bukkit.BukkitWorld.killMobs(BukkitWorld.java:625)
18.12 09:01:26 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.getLivingEntities(BukkitWorld.java:685)
18.12 09:01:26 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntity.getEntity(BukkitEntity.java:101)
18.12 09:01:26 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.<init>(BukkitPlayer.java:108)
18.12 09:01:26 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntityHuman.<init>(BukkitEntityHuman.java:47)
18.12 09:01:26 [Server] INFO    at org.bukkit.permissions.PermissibleBase.<init>(PermissibleBase.java:30)
18.12 09:01:26 [Server] INFO    at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:151)
18.12 09:01:26 [Server] INFO    at org.bukkit.permissions.PermissibleBase.isOp(PermissibleBase.java:37)
18.12 09:01:26 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.isOp(BukkitPlayer.java:119)
18.12 09:01:26 [Server] INFO java.lang.NullPointerException
18.12 09:01:12 [Server] INFO    at fy.run(SourceFile:856)
18.12 09:01:12 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
18.12 09:01:12 [Server] INFO    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
18.12 09:01:12 [Server] INFO    at ho.r(DedicatedServer.java:252)
18.12 09:01:12 [Server] INFO    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:696)
18.12 09:01:12 [Server] INFO    at ht.b(SourceFile:30)
18.12 09:01:12 [Server] INFO    at iw.b(NetworkListenThread.java:55)
18.12 09:01:12 [Server] INFO    at iv.d(NetServerHandler.java:82)
18.12 09:01:12 [Server] INFO    at cg.b(TcpConnection.java:451)
18.12 09:01:12 [Server] INFO    at cv.a(SourceFile:44)
18.12 09:01:12 [Server] INFO    at iv.a(NetServerHandler.java:681)
18.12 09:01:12 [Server] INFO    at iv.d(NetServerHandler.java:715)
18.12 09:01:12 [Server] INFO    at x.a(CommandHandler.java:81)
18.12 09:01:12 [Server] INFO    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:96)
18.12 09:01:12 [Server] INFO    at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52)
18.12 09:01:12 [Server] INFO    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:197)
18.12 09:01:12 [Server] INFO    at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1339)
18.12 09:01:12 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:425)
18.12 09:01:12 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:509)
18.12 09:01:12 [Server] INFO    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:172)
18.12 09:01:12 [Server] INFO    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:241)
18.12 09:01:12 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:522)
18.12 09:01:12 [Server] INFO    at java.lang.reflect.Method.invoke(Method.java:601)
18.12 09:01:12 [Server] INFO    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18.12 09:01:12 [Server] INFO    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
18.12 09:01:12 [Server] INFO    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18.12 09:01:12 [Server] INFO    at com.sk89q.worldedit.commands.UtilityCommands.butcher(UtilityCommands.java:395)
18.12 09:01:12 [Server] INFO    at com.sk89q.worldedit.bukkit.BukkitWorld.killMobs(BukkitWorld.java:625)
18.12 09:01:12 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.getLivingEntities(BukkitWorld.java:685)
18.12 09:01:12 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntity.getEntity(BukkitEntity.java:101)
18.12 09:01:12 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.<init>(BukkitPlayer.java:108)
18.12 09:01:12 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntityHuman.<init>(BukkitEntityHuman.java:47)
18.12 09:01:12 [Server] INFO    at org.bukkit.permissions.PermissibleBase.<init>(PermissibleBase.java:30)
18.12 09:01:12 [Server] INFO    at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:151)
18.12 09:01:12 [Server] INFO    at org.bukkit.permissions.PermissibleBase.isOp(PermissibleBase.java:37)
18.12 09:01:12 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.isOp(BukkitPlayer.java:119)
18.12 09:01:12 [Server] INFO java.lang.NullPointerException
18.12 09:01:07 [Server] INFO    at fy.run(SourceFile:856)
18.12 09:01:07 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
18.12 09:01:07 [Server] INFO    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
18.12 09:01:07 [Server] INFO    at ho.r(DedicatedServer.java:252)
18.12 09:01:07 [Server] INFO    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:696)
18.12 09:01:07 [Server] INFO    at ht.b(SourceFile:30)
18.12 09:01:07 [Server] INFO    at iw.b(NetworkListenThread.java:55)
18.12 09:01:07 [Server] INFO    at iv.d(NetServerHandler.java:82)
18.12 09:01:07 [Server] INFO    at cg.b(TcpConnection.java:451)
18.12 09:01:07 [Server] INFO    at cv.a(SourceFile:44)
18.12 09:01:07 [Server] INFO    at iv.a(NetServerHandler.java:681)
18.12 09:01:07 [Server] INFO    at iv.d(NetServerHandler.java:715)
18.12 09:01:07 [Server] INFO    at x.a(CommandHandler.java:81)
18.12 09:01:07 [Server] INFO    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:96)
18.12 09:01:07 [Server] INFO    at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52)
18.12 09:01:07 [Server] INFO    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:197)
18.12 09:01:07 [Server] INFO    at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1339)
18.12 09:01:07 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:425)
18.12 09:01:07 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:509)
18.12 09:01:07 [Server] INFO    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:172)
18.12 09:01:07 [Server] INFO    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:241)
18.12 09:01:07 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:522)
18.12 09:01:07 [Server] INFO    at java.lang.reflect.Method.invoke(Method.java:601)
18.12 09:01:07 [Server] INFO    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18.12 09:01:07 [Server] INFO    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
18.12 09:01:07 [Server] INFO    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18.12 09:01:07 [Server] INFO    at com.sk89q.worldedit.commands.UtilityCommands.butcher(UtilityCommands.java:395)
18.12 09:01:07 [Server] INFO    at com.sk89q.worldedit.bukkit.BukkitWorld.killMobs(BukkitWorld.java:625)
18.12 09:01:07 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.getLivingEntities(BukkitWorld.java:685)
18.12 09:01:07 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntity.getEntity(BukkitEntity.java:101)
18.12 09:01:07 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.<init>(BukkitPlayer.java:108)
18.12 09:01:07 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntityHuman.<init>(BukkitEntityHuman.java:47)
18.12 09:01:07 [Server] INFO    at org.bukkit.permissions.PermissibleBase.<init>(PermissibleBase.java:30)
18.12 09:01:07 [Server] INFO    at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:151)
18.12 09:01:07 [Server] INFO    at org.bukkit.permissions.PermissibleBase.isOp(PermissibleBase.java:37)
18.12 09:01:07 [Server] INFO    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.isOp(BukkitPlayer.java:119)
18.12 09:01:07 [Server] INFO java.lang.NullPointerException
18.12 09:01:01 [Server] INFO [PLAYER_COMMAND] jamy1016: /townyadmin 
18.12 09:00:45 [Server] INFO [PLAYER_COMMAND] jamy1016: /townyadmin 
18.12 09:00:27 [Server] INFO [PLAYER_COMMAND] jamy1016: /plot set bacon

**Comment by soulgriever** [comment]
perhaps the forge version of world edit?

**Comment by keepcalm** [comment]
Ya, you might want to try ForgeEssentials: (http://www.minecraftforum.net/topic/1592223-).

The issue is that WorldEdit access internal Bukkit classes, and these aren't compatible with mine. So if you're _absolutely_ desperate, I will port it, but FE will probably be more stable ;)

**Comment by xKillerbees** [comment]
I have been, it's missing a lot of features and has been in and out of working. So until it has all of the features I wanted, I was going to use this.

**Comment by keepcalm** [comment]
I applaud your efforts, and wish you luck... But I'll port it soon. Just go to get this vanishing code working.

**Comment by futhermukker** [comment]
I am having the same issues as the OP. I would tried the Essentials port you provided, cannot get it to work. So I am just letting you know I TOO would like a worldEdit port is you ever get time to do one. Awesome Plugin!

sorry for posting here (probably a better place to post this, but since this is a WorldEdit issue I figured this would be ok)

thank you.

**Comment by kotlerman** [comment]
Hello! I am having same problems. And ForgeEssentials can't help. Please, port WorldEdit!
Another good mod to port is Factions. When I try to launch it, it says that I don't have GSON (but it is in 'lib').

Thanks!

**Comment by keepcalm** [comment]
@kotlerman, can you post a new issue with the logs from factions?

**Comment by xKillerbees** [comment]
Still not working with the ported worldedit. I try to set a wand like you've always been able to, it refuses to set pos's. Then when I try to do them manually, it returns position null.

**Comment by futhermukker** [comment]
I concur. WorldEdit is still not functioning. everything the above poster wrote holds true.

**Comment by keepcalm** [comment]
Ok. I will experiment further. Does the sphere work?

**Comment by xKillerbees** [comment]
Tried

29.12 23:30:06 [Server] INFO    at fy.run(SourceFile:849)
29.12 23:30:06 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
29.12 23:30:06 [Server] INFO    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
29.12 23:30:06 [Server] INFO    at ho.r(DedicatedServer.java:270)
29.12 23:30:06 [Server] INFO    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
29.12 23:30:06 [Server] INFO    at ht.b(SourceFile:30)
29.12 23:30:06 [Server] INFO    at iw.b(NetworkListenThread.java:57)
29.12 23:30:06 [Server] INFO    at iv.d(NetServerHandler.java:136)
29.12 23:30:06 [Server] INFO    at cg.b(TcpConnection.java:454)
29.12 23:30:06 [Server] INFO    at cu.a(SourceFile:44)
29.12 23:30:06 [Server] INFO    at iv.a(NetServerHandler.java:734)
29.12 23:30:06 [Server] INFO    at iv.d(NetServerHandler.java:768)
29.12 23:30:06 [Server] INFO    at x.a(CommandHandler.java:82)
29.12 23:30:06 [Server] INFO    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:117)
29.12 23:30:06 [Server] INFO    at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52)
29.12 23:30:06 [Server] INFO    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:197)
29.12 23:30:06 [Server] INFO    at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1339)
29.12 23:30:06 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:425)
29.12 23:30:06 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:509)
29.12 23:30:06 [Server] INFO    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:172)
29.12 23:30:06 [Server] INFO    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:241)
29.12 23:30:06 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:522)
29.12 23:30:06 [Server] INFO    at java.lang.reflect.Method.invoke(Method.java:601)
29.12 23:30:06 [Server] INFO    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
29.12 23:30:06 [Server] INFO    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
29.12 23:30:06 [Server] INFO    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
29.12 23:30:06 [Server] INFO    at com.sk89q.worldedit.commands.GenerationCommands.sphere(GenerationCommands.java:204)
29.12 23:30:06 [Server] INFO    at com.sk89q.worldedit.WorldEdit.getBlockPattern(WorldEdit.java:608)
29.12 23:30:06 [Server] INFO    at com.sk89q.worldedit.WorldEdit.getBlock(WorldEdit.java:549)
29.12 23:30:06 [Server] INFO    at com.sk89q.worldedit.WorldEdit.getBlock(WorldEdit.java:355)
29.12 23:30:06 [Server] INFO    at com.sk89q.worldedit.WorldEdit.getBlock(WorldEdit.java:414)
29.12 23:30:06 [Server] INFO    at com.sk89q.worldedit.bukkit.BukkitWorld.isValidBlockType(BukkitWorld.java:872)
29.12 23:30:06 [Server] INFO java.lang.NoClassDefFoundError: net/minecraft/server/Block

**Comment by keepcalm** [comment]
I've decided that the best route for WE is to just create a mod that will depend on BukkitForge. It will be something I do in the background alongside BukkitForge. So it might be slow.

**Comment by keepcalm** [comment]
WE works now, execpt for //regen!

**Comment by futhermukker** [comment]
The wand still doesn't seem to work, nor does the hpos1 and hpos2 commands. (they still give the "selection null" error. I tried the version you have linked on your main page. Not sure if it is the latest or not. Just thought you should know.

keep up the good work, and thank you.

**Comment by Manawyrm** [comment]
Works just fine, here!

Please use the current build from jenkins and the modified worldedit!

**Comment by futhermukker** [comment]
Thank you Manawyrm for the answer to my problem. My mistake was not grabbing the newest BukkitForge from the jenkins. Works good now. Now I just have to find a working version of WorldEditCUI. 

AND... Thank you keepcalm for your WONDERFUL plugins. :)
