### ISSUE TITLE
No Main Manifest Attribute

### ISSUE THREAD

**Issue by eisterman** [keepcalm/BukkitForge#291]
starting the server with this string:

```
           java -Xms1G -Xmx1G -jar minecraft_server.jar nogui
```

or any other string java command, the server tells me:

```
           no main manifest attribute, in minecraft_server.jar
```

I think it's easy to fix ... at least I hope

**Comment by keepcalm** [comment]
Use a forge server, and put BukkitForge in coremods.

**Comment by eisterman** [comment]
Ops... i forgot then :P
