### ISSUE TITLE
[Enjin] minecraft plugin gets ported and stops working

### ISSUE THREAD

**Issue by Overload1252** [keepcalm/BukkitForge#293]
The tittle tells it all, after latest build it keeps making the plugin stop working, it used to work without porting and now bukkitforge ports it automaticaly

**Comment by SpoonsJTD** [comment]
Can you post the log that shows why it is failing to load?

**Comment by Overload1252** [comment]
Never mind, my bad it was. I found custom build of it at bukkit that seems to work just fine. Sorry again.
For those of you who encountered same prob: http://is.gd/kVBOTi
