### ISSUE TITLE
Pex do not work proberly

### ISSUE THREAD

**Issue by blade88** [keepcalm/BukkitForge#294]
I have a problem that Pex not work proberly
I become no errors in the console!

ok my problem is...
when i give a rank the "_" permission than it dont works...
he sayd me that i have no permissions for evrything!
and i cant placed/break blocks with the permission "_" or "modifyworld.*"
only as op i can place/break blocks.
pls help :+1:

**Comment by SpoonsJTD** [comment]
Dupe - permissions
