### ISSUE TITLE
Little Question

### ISSUE THREAD

**Issue by UGLHong** [keepcalm/BukkitForge#296]
Hey i wonder if your bukkitforge can include some chunk unloading technique to unload chunks because my server chunk dont seems to unload themself. I think forge doesn't unload chunk and this has caused my server has 20K loaded chunk with only 18 player. Correct me if im wrong. Help me i need info on unloading chunk thanks alot !!! really appreciate if you provide me with useful info ~

**Comment by SpoonsJTD** [comment]
Dupe - chuckunloading is captured in other issues.
