### ISSUE TITLE
Towny

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#30]
Appears that towny isn't registering you so you aren't able to use any of the commands. No error is spitting out.

**Comment by xKillerbees** [comment]
Might be in relation to the other issue report about permissions.

**Comment by keepcalm** [comment]
Try using /bexec <command>

**Comment by keepcalm** [comment]
Actually, I know why, fixing it now

**Comment by xKillerbees** [comment]
This is still an issue with the latest everything.

**Comment by keepcalm** [comment]
Ok, I think the problem is aliases - try using /bexec, that might help.

**Comment by xKillerbees** [comment]
That command does nothing.

**Comment by keepcalm** [comment]
/bexec <command>? - ie /bexec towny = /towny, but it will run with the name given.

I need it because forge doesn't pass the name used to a command.

**Comment by xKillerbees** [comment]
Still refuses to register me. So I am unable to do anything. I have tried every possible command and variation. 

I even checked the towny permissions and everything is default and correct. I am using the latest of everything.
