### ISSUE TITLE
Bukkit plugins stop responding.

### ISSUE THREAD

**Issue by frostmute** [keepcalm/BukkitForge#300]
Using BukkitForge-1.4.7-63

This is kind of a weird issue... 

I am using only WorldEdit and Essentials bukkit plugins.  Plugins work great the first time you join the server, and they will continue to work for the duration of the visit. However, if you disconnect and re-connect to the server, all of the bukkit plugins do not appear to load for you upon re-join.  It does not matter how long you wait to dis-connect/re-connect, the result is always the same.

The motd from essentials does not display and none of the commands related to either plugin work. The world edit wand does not function, etc.  It basically acts/looks as if there were no plugins present at all.  

If you re-start the server, and re-join, everything works again.... until you disconnect. The server has to be restarted to force the plugins to work every time you disconnect.

No errors in the server log, at all.

**Comment by shakey2** [comment]
Try latest build.

**Comment by charlieTheBotDev** [comment]
I was literally about to say 'I have this issue too using build 65' then you posted. Then I look and see we're on build 70 already :O you guys rule :3

**Comment by frostmute** [comment]
I'm still able to reproduce the issue on build #70.

**Comment by mmis1000** [comment]
still happen in #75 
keepcalm seems haven't look on this issue

**Comment by frostmute** [comment]
FIXED in 1.4.7-80

Thanks!
