### ISSUE TITLE
[Physical Shop] Not working Properly

### ISSUE THREAD

**Issue by Axuix** [keepcalm/BukkitForge#307]
When right clicking with Gold ingots in your hand ( to Buy what the shop is selling ) it will take all of your gold and if you select anything in your inventory after that, it will delete everything you have.

**Comment by SpoonsJTD** [comment]
Item removing and adding have been fixed. Please retry.

**Comment by Axuix** [comment]
The inventory is no longer wiped when buying or selling. Here is what happens now:
- When Buying > The inventory does not update. ie. Your x amount of gold remains the same, and no new items appear And when you click on your gold that you bought with, it will remain the same, but the items you bought appear.

-When Selling > The inventory also does not update. When you sell it will not update until you again click on your gold. The x amount of items you sold does not change, but you recieve the gold.

I'm trying to make this as clear as possible, please let me know if more detail is needed.

Thanks, and keep up the great work!
