### ISSUE TITLE
[Safe Creeper & Essentials] Creeper Exploding Problems

### ISSUE THREAD

**Issue by jrusboldt** [keepcalm/BukkitForge#308]
Information:
Issue occurs on BukkitForge build 80
Only have two plugins installed: "Safe Creeper" and "Essentials"
This is all on the "Mindcrack" mod pack launched through the "Feed the Beast" launcher

The problem that I'm getting is Creepers not exploding properly. What I want is to make it so creepers explode, harm players, but don't destroy the land. Here's what happens:

With Safe Creeper and Essentials:
Creepers get ready to explode and then just pause right before exploding. They then just sit there and don't do anything.

With only Essentials:
Creepers do nonstop explosions, but don't harm players or the land.

With only Safe Creeper:
Same issue as if it was with Safe Creeper and Essentials

With Neither Plugin:
Creepers explode the way they should in Vanilla Minecraft

Here's a pastebin link to the console errors I receive with Safe Creeper and Essentials installed: http://pastebin.com/B8yAJNn8

I hope I have provided enough information to help you figure out what's wrong.

Thanks! :D

**Comment by ghost** [comment]
Same behavior with worldguard (block creeper destroy blocks) Creeper explode, blocks not destroyed, but creeper still sit on place.

**Comment by lihad** [comment]
When the event is cancelled, the entity is not removed.
