### ISSUE TITLE
[Base-getWorld()] Loading Issue NPE Version 79-80

### ISSUE THREAD

**Issue by lihad** [keepcalm/BukkitForge#309]
This issue could be occurring earlier than 79, I couldnt test any others as the Jenkins won't allow me any jars earlier than the noted.  The following NPE comes on startup when loading plugins. It will generally happen to about half the loaded plugins. does not occur on version 70.

When a plugin calls Bukkit.getServer().getWorld(worldName) during startup, the plugin breaks; NPE

**Comment by keepcalm** [comment]
I see no error O.o

**Comment by SpoonsJTD** [comment]
I have a dozen plug-ins loading, and I don't see this. Can you tell us what plugin or provide a log?

**Comment by lihad** [comment]
Yah, I'll see if I can give you all a more detailed descript very soon

**Comment by lihad** [comment]
Im not getting this issue with 83/84 any longer, im going to close this.
