### ISSUE TITLE
Im have not permissions to this command?

### ISSUE THREAD

**Issue by Thornas88** [keepcalm/BukkitForge#31]
Hello 

I have a problem and i need help.

One of my Admin has the permissions to set Warps /spawn, or /reload
But im an Admin too and i cant do this and i am op.
We havent  PermissionsEX or anything else.

Greetings Thornas

**Comment by Wolftein** [comment]
And i don't have permission for any command, and i'm not using any permission plugin being op :/

**Comment by keepcalm** [comment]
Strange. I think the issue is that I wasn't lowercase-ing names before I checked the ops list.

**Comment by Thornas88** [comment]
I checked the op list and i am op. My other Admins have the same problem, only one Admin haven´t this problems. But the configuration hasn´t not change.

**Comment by keepcalm** [comment]
yes, but in the op list, is your username lowercase?

**Comment by Thornas88** [comment]
no and i join with my second acc of my server an give him op permissions and by him works all? Strange

**Comment by Thornas88** [comment]
an another bug: when the server is longer on. Can we no craft Mod Items. After a restart works all.

**Comment by keepcalm** [comment]
Can you post a new issue with the logs? I don't see why this would happen, but I'll look into it.

And a temporary fix for the ops thingy is to change all the names in ops.txt to lowercase.

**Comment by Thornas88** [comment]
i am can invite you to show you the problems mod on my server.

**Comment by soulgriever** [comment]
my username is "soulgriever" all lowercase and I havent had this issue, hope it helps in identifing the problem

**Comment by Thornas88** [comment]
okay the lowercasing names are op and the another not? this ist the problem?

My Op:

BlackwingDave (first acc)
Nefala
BashingBob

no op

lowercaseing op

thornas88(second acc)
chakratos

are op

**Comment by keepcalm** [comment]
Yes, that's the problem. I derped that up, but I've fixed it  now. So for now change, for example, BlackwingDave to blackwingdave in the ops list. Sorry about that...
