### ISSUE TITLE
[WE] "//regen" never worked.

### ISSUE THREAD

**Issue by Beelzaboss** [keepcalm/BukkitForge#310]
Hello there guys/girls

I just want to report this problem, that //regen is not working.

also Keepclam u replied to this "https://github.com/keepcalm/BukkitForge/issues/292" that u stated it's fixed, but it's still not :smile:

**Comment by Bucky420** [comment]
workd for me do /rg i dont use that other command :P

**Comment by BubblyLemon** [comment]
I also just tested out //regen on build 84 and it did not work for me.

**Comment by eagl3s1ght** [comment]
I asked Keepcalm about this and if I understood it right, Forge doesn't support this kind of regeneration of the world yet. Hopefully Forge implements it soon :)

**Comment by secondfry** [comment]
//regen working for me correctly.
Forge 518, 534. BukkitForge 252, 255.

**Comment by eagl3s1ght** [comment]
This can be closed for sure, it has been working a long time. Not sure how @SpoonsJTD missed it. :dancer:
