### ISSUE TITLE
[Base-Inventory] Build 80: Inventory can not be dragged.

### ISSUE THREAD

**Issue by PsychoPenguinX** [keepcalm/BukkitForge#311]
As an OP, anytime I tried to rearrange my inventory, drop items, or use NEI, clicking anything gave me either a full stack or infinite of each item. Items could not be dropped or destroyed as a result. A server restart and tekkit relog did not help, but reverting to build 79 fixed the issue. No other users were on to test this with different permissions.

**Comment by SpoonsJTD** [comment]
This is odd because the change that triggered build 80 doesn't look like anything that would affect base behavior. I can't test right now, is anyone else experiencing this?

**Comment by shakey2** [comment]
I'm not having this problem but it seems inventory sorting with inv tweaks is broken for me in build 80. Not sure if it's related...

**Comment by SpoonsJTD** [comment]
I can't reproduce this as op - inventory was fine and sorting worked with inv tweaks, will try as non-op.

**Comment by SpoonsJTD** [comment]
Can't reproduce as a non-op either?

**Comment by PsychoPenguinX** [comment]
I just redownloaded build 80 and everything worked fine. I'm guessing I just had a bad download; sorry for the false alarm. Consider this closed.
