### ISSUE TITLE
[WorldEdit] does not detect custom block

### ISSUE THREAD

**Issue by kozlek** [keepcalm/BukkitForge#312]
To start, I can thanks you a lot for your mod, Forge really need this great work :-)

I'm using custom block like ones of the Twilight Forest or Extrabiomes XL, and world edit do not detect them so, for example, I can't use //set 1380:11 (I.D. of balsa wood)

I'm on build #80 with worldedit 5.5 from bukkit dev.

Thanks a lot if someone can help me !

EDIT: it only happens when block ID are > 255

**Comment by keepcalm** [comment]
Dupe of #317
