### ISSUE TITLE
[SonicScrewdriver] NBTBase not found.

### ISSUE THREAD

**Issue by zambony** [keepcalm/BukkitForge#313]
ISSUE: Upon starting the server with the plugin SonicScrewdriver, I get this issue in the console. http://pastebin.com/zW9HVPR1 It is also in the Forge log
BukkitForge version 1.4.7 build 80
Forge version 504
Symptoms: I log in and put the items in the crafting bin as instructed but the plugin will not give me my item.

**Comment by SpoonsJTD** [comment]
The class it's trying to load doesn't exist there. The version you are using is likely out of date.
