### ISSUE TITLE
[Group manager][Build 80] issues with worlds and group manger :\

### ISSUE THREAD

**Issue by Bucky420** [keepcalm/BukkitForge#314]
on the new version how world work have changed cause now groupmanager make the right files 
but when doing manuadd myname owner  and then do mansave ... it doesn't show up in any config file ... wich explained why tags dont work even if there all the same in every folder ...

**Comment by SpoonsJTD** [comment]
I don't quite follow, codydbgt. Are you looking in config files or perms files?

**Comment by charlieTheBotDev** [comment]
I'm not sure but I think I had the same issue. I have a folder with my world name then 'links' to the folder with the names nether, the_end and overworld. Groupmanager sees the links as folders and I have one set of permissions files for all my worlds :D 
I'm not sure what these links actually are but I created them with WinSCP really easily and it works perfectly.
Screenshot: 
http://imgur.com/8wZaJtF

This also works with other plugins as well :)

**Comment by Bucky420** [comment]
umm the permissoin folder in the /plugin/groupmanager/world folder .... im going to do further testing

**Comment by Bucky420** [comment]
the world is Overworld as the default world tested on build 80 with latest version of essentials and groupmanager .... this issue is closed ... be shure to change all your world names in your player dat folders in essensitials to the Overworld

the world folder is located at /plugins/groupmanager/world/Overworld 

essentials data files 
lastlocation:
  world: Overworld
  x: -13.300000011920925
  y: 80.0
  z: -800.3000000119209
  yaw: -199.35889
  pitch: 25.04996

homes:
  home:
    world: Overworld
    x: -15.015387295175282
    y: 79.0
    z: -805.3268818562915
    yaw: 25.041046
    pitch: -3.1500366
