### ISSUE TITLE
/reloload all and can not craft Mod Items

### ISSUE THREAD

**Issue by Thornas88** [keepcalm/BukkitForge#32]
Here is a Another bug. When i make a reload can i can´t craft Mod items. But after a restart can i craft everything.

**Comment by soulgriever** [comment]
I dont think this is fixable as it was an issue in tekkit as well I simply think its due to certain parts of forge and bukkit not playing nice

**Comment by xKillerbees** [comment]
This is not an issue with this, it's an issue with that command. My advice is just don't use it. Any time you hear about this command, a coder or dev will tell you not to use it, just to reboot.

**Comment by keepcalm** [comment]
But in this instance I can try and fix it. I'll have a look, but no garuntees...
