### ISSUE TITLE
[Citadel] javax/persistence/PersistenceException

### ISSUE THREAD

**Issue by rourke750** [keepcalm/BukkitForge#320]
http://pastebin.com/uffhxk1d

Seems like the only error.

**Comment by SpoonsJTD** [comment]
Does it have a lib dependency?

**Comment by rourke750** [comment]
It should be a standalone plugin

**Comment by rourke750** [comment]
It uses mysql if that helps.

**Comment by SpoonsJTD** [comment]
V3.2 doesn't seem to have a plugin.yml file so the plugin won't even load for me. The version your log indicates you are using is out of date and is for MC 1.3.2. Talk to the Citadel author.

**Comment by rourke750** [comment]
?use this version
 https://www.dropbox.com/s/131yvvzmb6blnnw/New%20WinRAR%20ZIP%20archive.zip
