### ISSUE TITLE
[Base-ClassNotFoundException: qc] Exception on Startup <Versions 82 & 84>

### ISSUE THREAD

**Issue by lihad** [keepcalm/BukkitForge#322]
Im running an up-to-date mindcrack server.  Version 70 works fine, but the following exceptions occur on startup for 82 and 84 (The only 2 recent versions I have tested against). Of course, reverting back to 70 after launch allows startup with no issue.

http://pastebin.com/PjdwJtyR

**Comment by SpoonsJTD** [comment]
This sounds like a bad download and/or server build. I am running MindCrack v7 with current BukkitForge build with no issues.

**Comment by lihad** [comment]
Kinda what I was thinking too, but since it only breaks with changes to BukkitForge versions, figured I would throw it out there.  Rebuilding my Mindcrack v7 now

**Comment by lihad** [comment]
Yup, build went sour.  Shweet!
