### ISSUE TITLE
[WorldEdit] Not working in Nether/ Other worlds

### ISSUE THREAD

**Issue by BubblyLemon** [keepcalm/BukkitForge#324]
Any commands that alter blocks do not work in the Nether, or in Twilightforest.

//set for example will say 0 blocks edited.

In the twilight, it said that X blocks were edited, but they did not appear to be edited.

Build 84

**Comment by kozlek** [comment]
Yes I have the same issue 
In fact, the block are edited... in the overworld !

**Comment by kozlek** [comment]
#228

**Comment by SpoonsJTD** [comment]
This should be fixed. Please retry.

**Comment by Oliverj102** [comment]
I am having the same issue, running on version 252 of bukkit forge
