### ISSUE TITLE
[Pex] prefix problem

### ISSUE THREAD

**Issue by mi000731** [keepcalm/BukkitForge#334]
When I use PermissionsEx or Other Permissions plugin
Can't No support "prefix"or "Nick"
The player name alway No Change
Can you fix it?
Thanks a lot!!

**Comment by Tampa** [comment]
Can confirm chatmanager of latest pex isnt working, prefix nor suffix show up. Either you need to port the whole pex package or you allow bukkitforge to use it.

**Comment by SpoonsJTD** [comment]
Pex is not supported.
