### ISSUE TITLE
[CreativeMode] Can't turn on creative mode.

### ISSUE THREAD

**Issue by Ragsy** [keepcalm/BukkitForge#336]
Using build 89, can't use command /gamemode <#> <name>, won't deliver the command to the server, isn't even showing up in the server log.

**Comment by eagl3s1ght** [comment]
Using build 90, /gamemode <#> works fine.

**Comment by shakey2** [comment]
Don't use # tag when referencing build numbers, you are needlessly linking to other unrelated issues.
