### ISSUE TITLE
[SimpleIRC] Messages ingame not posting in IRC

### ISSUE THREAD

**Issue by darkvirus** [keepcalm/BukkitForge#341]
I have found with all chat plugins [xServer] [SimpleIRC] [BukkitLink] that none of them will pick up the chat in FTB. But they will pickup the joins/disconnects.

I have tested this on a tekkit and vanilla server, and both servers report joins/disconnects and player chat.

Any help would be appreciated

**Comment by keplersj** [comment]
If you're trying to get IRC on your server I would't recommend using a plugin but rather an actual ForgeMod.

Here's ForgeIRC: http://www.minecraftforum.net/topic/1475847-146-forgeirc-v1014-soul-shards-v126-and-recipe-remover-v11-updated-122013/

If you'd rather use the plugin though it would help if you posted your ForgeLog-0 using gist.github.com

**Comment by darkvirus** [comment]
https://gist.github.com/4611830 

There you go.

If you look at line 3303 i join the server.
Then it uses PRIVMSG to announce that i joined the game to IRC
i say test ingame 4 times and nothing happens
Then i disconnect and it uses PRIVMSG to tell IRC i left the game.

Here is a screenshot also.

http://iforce.co.nz/i/wmkhsyk1.wqw.png 

Also please note, if i talk in the IRC server it is also posting the message into the game chat

**Comment by darkvirus** [comment]
i am using forge IRC for this server now.
