### ISSUE TITLE
[Base-getWorld()][b90] Bukkit thinks player is always in "Overworld"/D'synced players

### ISSUE THREAD

**Issue by lihad** [keepcalm/BukkitForge#345]
Bukkit thinks player is always in "Overworld", no matter what world the player is actually in.

As a test, I did:

player.sendMessage("World: "+player.getLocation().getWorld().getName()+" X:"+player.getLocation().getX()+" Y:"+player.getLocation().getY()+" Z:"+player.getLocation().getZ());

which is registered by a command.  And in all cases, no matter what world the player is in, always returns "Overworld" for the players world.

 Continuing on to this, in some cases, players actually received coords of the World Spawn Location instead of their current location.  And trying to ./home for those players which are in this state resulted in them getting placed back at the world spawn no matter where they set their home, or where they currently existed.

**Comment by mmis1000** [comment]
same problem with #324 and #228

**Comment by SpoonsJTD** [comment]
I believe this was fixed a while ago.
