### ISSUE TITLE
[Base-getPlayer(name)][b90] getPlayer(name) is null if not completely lower case.

### ISSUE THREAD

**Issue by lihad** [keepcalm/BukkitForge#346]
Further progress from:  https://github.com/keepcalm/BukkitForge/issues/306

The following :

if(Bukkit.getServer().getPlayer(name) != null){
return true;
}else{
return false;
}

is true if a player is online AND their name (which is string argument 'name' above) is in complete lower-case, whether their name actually has upper-case or not. 

I.E.  Passing 'Lihad' would return false.  Passing 'lihad' would return true. My name in game is 'Lihad'

**Comment by SpoonsJTD** [comment]
case sensitive naming was fixed
