### ISSUE TITLE
[ArsMagicaMOD] When I try to use it on SMP it crash!

### ISSUE THREAD

**Issue by erictfkc** [keepcalm/BukkitForge#347]
ArsMagica_RC_5.32.272  version
if this mod not to support by bukkitforge?
or it conflict with it?

**Comment by keplersj** [comment]
We need logs to know if the compatibility issue is with BukkitForge or ArsMagica

**Comment by dedo1911** [comment]
Tested and working with latest bukkitforge + latest forge. But, if you're using RedPower (as me) and/or Thermal Expansion you need to customize items id by changing them in the config files.
This mod is NOT compatibile with AdvancedAlloys for IC2, Condensed Blocks and Optifine.
