### ISSUE TITLE
[RedPower] crash

### ISSUE THREAD

**Issue by mi000731** [keepcalm/BukkitForge#348]
I use RedPowerCore-2.0pr6 but crash

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 1/23/13 4:25 PM
Description: Exception while updating neighbours

java.lang.IndexOutOfBoundsException: Index: 1, Size: 3
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at yc.q(World.java:2800)
    at com.eloraam.redpower.core.TubeLib.isConSide(TubeLib.java:40)
    at com.eloraam.redpower.core.TubeLib.getConnections(TubeLib.java:74)
    at com.eloraam.redpower.core.TubeLib$RouteFinder.find(TubeLib.java:128)
    at com.eloraam.redpower.core.TubeLib.findRoute(TubeLib.java:298)
    at com.eloraam.redpower.core.TubeLib.addToTubeRoute(TubeLib.java:320)
    at com.eloraam.redpower.core.MachineLib.handleItem(MachineLib.java:220)
    at com.eloraam.redpower.machine.TileMachine.handleItem(TileMachine.java:50)
    at com.eloraam.redpower.machine.TileBreaker.drainBuffer(TileBreaker.java:138)
    at com.eloraam.redpower.machine.TileBreaker.onBlockNeighborChange(TileBreaker.java:130)
    at com.eloraam.redpower.core.BlockExtended.a(BlockExtended.java:94)
    at yc.m(World.java:819)
    at yc.h(World.java:801)
    at yc.f(World.java:741)
    at yc.e(World.java:699)
    at com.eloraam.redpower.machine.TileBreaker.onBlockNeighborChange(TileBreaker.java:128)
    at com.eloraam.redpower.core.BlockExtended.a(BlockExtended.java:94)
    at yc.m(World.java:819)
    at yc.h(World.java:798)
    at yc.f(World.java:741)
    at yc.e(World.java:699)
    at com.eloraam.redpower.machine.TileBreaker.onBlockNeighborChange(TileBreaker.java:128)
    at com.eloraam.redpower.core.BlockExtended.a(BlockExtended.java:94)
    at com.eloraam.redpower.core.RedPowerLib.notifyBlock(RedPowerLib.java:40)
    at com.eloraam.redpower.core.RedPowerLib.updateCurrent(RedPowerLib.java:742)
    at com.eloraam.redpower.machine.TileRedstoneTube.onBlockNeighborChange(TileRedstoneTube.java:87)
    at com.eloraam.redpower.core.BlockMultipart.a(BlockMultipart.java:30)
    at yc.m(World.java:819)
    at yc.h(World.java:800)
    at alv.l(BlockRedstoneWire.java:106)
    at alv.a(BlockRedstoneWire.java:421)
    at yc.m(World.java:819)
    at yc.h(World.java:798)
    at alv.l(BlockRedstoneWire.java:106)
    at alv.a(BlockRedstoneWire.java:421)
    at com.eloraam.redpower.core.RedPowerLib.notifyBlock(RedPowerLib.java:40)
    at com.eloraam.redpower.core.RedPowerLib.updateCurrent(RedPowerLib.java:742)
    at com.eloraam.redpower.machine.TileRedstoneTube.onBlockNeighborChange(TileRedstoneTube.java:87)
    at com.eloraam.redpower.core.BlockMultipart.a(BlockMultipart.java:30)
    at yc.m(World.java:819)
    at yc.h(World.java:797)
    at alv.l(BlockRedstoneWire.java:106)
    at alv.a(BlockRedstoneWire.java:421)
    at com.eloraam.redpower.core.RedPowerLib.notifyBlock(RedPowerLib.java:40)
    at com.eloraam.redpower.core.RedPowerLib.updateIndirectNeighbors(RedPowerLib.java:53)
    at com.eloraam.redpower.core.TileExtended.updateBlockChange(TileExtended.java:86)
    at com.eloraam.redpower.logic.TileLogicPointer.timerUpdate(TileLogicPointer.java:140)
    at com.eloraam.redpower.logic.TileLogicPointer.g(TileLogicPointer.java:274)
    at yc.h(World.java:2151)
    at in.h(WorldServer.java:516)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:680)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at yc.q(World.java:2800)
    at com.eloraam.redpower.core.TubeLib.isConSide(TubeLib.java:40)
    at com.eloraam.redpower.core.TubeLib.getConnections(TubeLib.java:74)
    at com.eloraam.redpower.core.TubeLib$RouteFinder.find(TubeLib.java:128)
    at com.eloraam.redpower.core.TubeLib.findRoute(TubeLib.java:298)
    at com.eloraam.redpower.core.TubeLib.addToTubeRoute(TubeLib.java:320)
    at com.eloraam.redpower.core.MachineLib.handleItem(MachineLib.java:220)
    at com.eloraam.redpower.machine.TileMachine.handleItem(TileMachine.java:50)
    at com.eloraam.redpower.machine.TileBreaker.drainBuffer(TileBreaker.java:138)
    at com.eloraam.redpower.machine.TileBreaker.onBlockNeighborChange(TileBreaker.java:130)
    at com.eloraam.redpower.core.BlockExtended.a(BlockExtended.java:94)

-- Block being updated --
Details:
    Source block type: ID #0
    Block type: ID #763 (tile.rpmachine2 // com.eloraam.redpower.machine.BlockMachine)
    Block data value: 1 / 0x1 / 0b0001
    Block location: World: (736,96,-16767), Chunk: (at 0,6,1 in 46,-1048; contains blocks 736,0,-16768 to 751,255,-16753), Region: (1,-33; contains chunks 32,-1056 to 63,-1025, blocks 512,0,-16896 to 1023,255,-16385)
Stacktrace:
    at yc.m(World.java:819)
    at yc.h(World.java:801)
    at yc.f(World.java:741)
    at yc.e(World.java:699)
    at com.eloraam.redpower.machine.TileBreaker.onBlockNeighborChange(TileBreaker.java:128)
    at com.eloraam.redpower.core.BlockExtended.a(BlockExtended.java:94)

-- Block being updated --
Details:
    Source block type: ID #0
    Block type: ID #763 (tile.rpmachine2 // com.eloraam.redpower.machine.BlockMachine)
    Block data value: 1 / 0x1 / 0b0001
    Block location: World: (736,96,-16765), Chunk: (at 0,6,3 in 46,-1048; contains blocks 736,0,-16768 to 751,255,-16753), Region: (1,-33; contains chunks 32,-1056 to 63,-1025, blocks 512,0,-16896 to 1023,255,-16385)
Stacktrace:
    at yc.m(World.java:819)
    at yc.h(World.java:798)
    at yc.f(World.java:741)
    at yc.e(World.java:699)
    at com.eloraam.redpower.machine.TileBreaker.onBlockNeighborChange(TileBreaker.java:128)
    at com.eloraam.redpower.core.BlockExtended.a(BlockExtended.java:94)
    at com.eloraam.redpower.core.RedPowerLib.notifyBlock(RedPowerLib.java:40)
    at com.eloraam.redpower.core.RedPowerLib.updateCurrent(RedPowerLib.java:742)
    at com.eloraam.redpower.machine.TileRedstoneTube.onBlockNeighborChange(TileRedstoneTube.java:87)
    at com.eloraam.redpower.core.BlockMultipart.a(BlockMultipart.java:30)

-- Block being updated --
Details:
    Source block type: ID #55 (tile.redstoneDust // alv)
    Block type: ID #750 (tile.rpwire // com.eloraam.redpower.base.BlockMicro)
    Block data value: 9 / 0x9 / 0b1001
    Block location: World: (732,96,-16763), Chunk: (at 12,6,5 in 45,-1048; contains blocks 720,0,-16768 to 735,255,-16753), Region: (1,-33; contains chunks 32,-1056 to 63,-1025, blocks 512,0,-16896 to 1023,255,-16385)
Stacktrace:
    at yc.m(World.java:819)
    at yc.h(World.java:800)
    at alv.l(BlockRedstoneWire.java:106)
    at alv.a(BlockRedstoneWire.java:421)

-- Block being updated --
Details:
    Source block type: ID #55 (tile.redstoneDust // alv)
    Block type: ID #55 (tile.redstoneDust // alv)
    Block data value: 14 / 0xE / 0b1110
    Block location: World: (732,95,-16763), Chunk: (at 12,5,5 in 45,-1048; contains blocks 720,0,-16768 to 735,255,-16753), Region: (1,-33; contains chunks 32,-1056 to 63,-1025, blocks 512,0,-16896 to 1023,255,-16385)
Stacktrace:
    at yc.m(World.java:819)
    at yc.h(World.java:798)
    at alv.l(BlockRedstoneWire.java:106)
    at alv.a(BlockRedstoneWire.java:421)
    at com.eloraam.redpower.core.RedPowerLib.notifyBlock(RedPowerLib.java:40)
    at com.eloraam.redpower.core.RedPowerLib.updateCurrent(RedPowerLib.java:742)
    at com.eloraam.redpower.machine.TileRedstoneTube.onBlockNeighborChange(TileRedstoneTube.java:87)
    at com.eloraam.redpower.core.BlockMultipart.a(BlockMultipart.java:30)

-- Block being updated --
Details:
    Source block type: ID #55 (tile.redstoneDust // alv)
    Block type: ID #750 (tile.rpwire // com.eloraam.redpower.base.BlockMicro)
    Block data value: 9 / 0x9 / 0b1001
    Block location: World: (728,96,-16763), Chunk: (at 8,6,5 in 45,-1048; contains blocks 720,0,-16768 to 735,255,-16753), Region: (1,-33; contains chunks 32,-1056 to 63,-1025, blocks 512,0,-16896 to 1023,255,-16385)
Stacktrace:
    at yc.m(World.java:819)
    at yc.h(World.java:797)
    at alv.l(BlockRedstoneWire.java:106)
    at alv.a(BlockRedstoneWire.java:421)
    at com.eloraam.redpower.core.RedPowerLib.notifyBlock(RedPowerLib.java:40)
    at com.eloraam.redpower.core.RedPowerLib.updateIndirectNeighbors(RedPowerLib.java:53)
    at com.eloraam.redpower.core.TileExtended.updateBlockChange(TileExtended.java:86)
    at com.eloraam.redpower.logic.TileLogicPointer.timerUpdate(TileLogicPointer.java:140)
    at com.eloraam.redpower.logic.TileLogicPointer.g(TileLogicPointer.java:274)

-- Tile entity being ticked --
Details:
    Name: RPLgPtr // com.eloraam.redpower.logic.TileLogicPointer
    Block type: ID #0
    Block data value: Unknown? (Got -1)
    Block location: World: (730,96,-16763), Chunk: (at 10,6,5 in 45,-1048; contains blocks 720,0,-16768 to 735,255,-16753), Region: (1,-33; contains chunks 32,-1056 to 63,-1025, blocks 512,0,-16896 to 1023,255,-16385)
Stacktrace:
    at yc.h(World.java:2151)
    at in.h(WorldServer.java:516)

-- Affected level --
Details:
    Level name: world
    All players: 16 total; [ServerPlayer['3billy'/835, l='world', x=472.90, y=72.00, z=1002.25], ServerPlayer['mi000731'/1044, l='world', x=499.83, y=72.00, z=1033.00], ServerPlayer['fien'/1046, l='world', x=517.98, y=91.00, z=944.63], ServerPlayer['chihag'/1176, l='world', x=496.34, y=72.00, z=1033.02], ServerPlayer['letea255'/1379, l='world', x=796.87, y=62.00, z=1213.69], ServerPlayer['tiara52000'/3093, l='world', x=500.76, y=72.00, z=1030.13], ServerPlayer['asd1010'/4725, l='world', x=516.16, y=75.00, z=935.70], ServerPlayer['aaaa6284'/4737, l='world', x=502.24, y=72.00, z=1031.44], ServerPlayer['Dictionary'/4841, l='world', x=497.07, y=72.00, z=1036.46], ServerPlayer['teddy1234'/6341, l='world', x=530.69, y=79.11, z=935.34], ServerPlayer['perdvct25'/6614, l='world', x=502.16, y=72.00, z=1035.07], ServerPlayer['gjvu'/7224, l='world', x=472.29, y=72.00, z=1050.45], ServerPlayer['joer'/10697, l='world', x=515.07, y=75.00, z=941.77], ServerPlayer['doisy'/964, l='world', x=503.76, y=72.00, z=1047.16], ServerPlayer['a30032549'/13564, l='world', x=500.50, y=72.50, z=1024.50], ServerPlayer['wujunyen'/13724, l='world', x=124.61, y=71.00, z=1375.23]]
    Chunk stats: ServerChunkCache: 1682 Drop: 0
    Level seed: 2611726147852031506
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (500,73,1024), Chunk: (at 4,4,0 in 31,64; contains blocks 496,0,1024 to 511,255,1039), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
    Level time: 38962053 game time, 39240469 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 73186 (now: false), thunder time: 86873 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:680)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

-- System Details --
Details:
    Minecraft Version: 1.4.7
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_11, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 9275395120 bytes (8845 MB) / 22011707392 bytes (20992 MB) up to 22011707392 bytes (20992 MB)
    JVM Flags: 23 total; -XX:ParallelGCThreads=16 -XX:UseSSE=16 -Xmx22G -Xms22g -Xmn15g -Xss17g -XX:PermSize=1g -XX:MaxPermSize=22g -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:GCTimeRatio=19 -Xnoclassgc -XX:+DisableExplicitGC -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSPermGenSweepingEnabled -XX:+UseCMSCompactAtFullCollection -XX:CMSFullGCsBeforeCompaction=0 -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=70 -XX:SoftRefLRUPolicyMSPerMB=0 -XX:LargePageSizeInBytes=4m
    AABB Pool Size: 15110 (846160 bytes; 0 MB) allocated, 7241 (405496 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 63
    FML: MCP v7.26 FML v4.7.10.524 Minecraft Forge 6.6.0.499 87 mods loaded, 87 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    LainCraft [LainCraft](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Familiars_API [Familiars API](Familiars_API_1.4.6a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    fihgu's Core Mod [fihgu's Core Mod](minecraft_server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RubeAurora [Mr. Rube's Aurora Mod](AuroraRubealis_v100_For_146.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge [BukkitForge](BukkitForge-1.4.7-90.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BlockBreak [Block Break Event](BukkitForge-1.4.7-90.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    jammyfurniture [Jammy Furniture Mod](1.4.6_Jammy_Furniture_Mod_V4.0-nickCN.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    HarkenScythe_Core [侚朸眳蟑-犖趙](1.4.6HarkenScythe_v1.1.2Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Core [BuildCraft](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Energy [BC Energy](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ExtrabiomesXL [ExtrabiomesXL](ExtrabiomesXL-universal-1.4.6-3.7.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forestry [Forestry for Minecraft](forestry-A-1.6.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2 [IndustrialCraft 2](industrialcraft-2_1.112.170-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    drceph.petrogen [Petroleum Generator]([1.4.6]PetroGen-1.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    LoginMessage [LoginMessage]([forge_universal][1.4.6]LoginMessage_v0.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    AdvancedMachines [IC2 Advanced Machines Addon](AdvancedMachines_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    AdvancedPowerManagement [Advanced Power Management](AdvancedPowerManagement-1.1.55-IC2_1.112.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_AnimalBikes [mod_AnimalBikes](animalbike.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    MinecraftWero [Bacon Mod](Bacon_Mod_v2.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BasicComponents [Basic Components](BasicComponents_v1.2.1.318.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BattleTowers [Battle Towers](BattleTowers_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Factory [BC Factory](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BCIC2Crossover [BC-IC2 Crossover Mod](BCIC2crossover 2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Builders [BC Builders](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Transport [BC Transport](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Silicon [BC Silicon](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ChargePads [Charge Pads](chargepads-universal-2.3.0.58.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CM [Compact Mobs](CompactMobs-v1.2.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CompactSolars [Compact Solar Arrays](compactsolars-universal-1.4.6-3.2.0.21.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CustomSpawner [DrZhark's CustomSpawner](CustomMobSpawner_1.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CustomNpcs [CustomNpcs 1.4.5](CustomNPCs_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    DamageIndicatorsMod [Damage Indicators](DamageIndicators[1.4.6]2.2.7.1.zip.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    denLib [denLib](denLib-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    EurysCore [Eurys Mod Core](EurysCore_2.0.0.3[1].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BinnieCore [Binnie Core](extrabees-1.4.9.4-prerelease.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ExtraBees [Extra Bees](extrabees-1.4.9.4-prerelease.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Familiars_DefaultMobPack [DefaultMobPack](Familiars_DefaultMobPack_1.4.6a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Familiars_ExtendedFamPack [ExtendedFamPack](Familiars_ExtendedFamPack_1.4.6a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    fihgu's Protection Mod [fihgu's Protection Mod](fihgu's Protection Mod%282.1.2%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    fihgu's AutoCommand Mod [fihgu's AutoCommand Mod](fihgu_'s AutoCommand Mod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    LegendaryBeasts [Legendary Beasts](Forge_LegendaryBeastsAlpha1.4.6.0[1].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2NuclearControl [Nuclear Control](IC2NuclearControl-1.4.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    InfernalMobs [Infernal Mobs](InfernalMobs_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    InfestationModFML [InfestationModFML](infestation-0.2.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_Infestation [mod_Infestation](infestation-0.2.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IronChest [Iron Chest](ironchest-universal-1.4.6-4.5.1.199[1].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    LiquidUU [Liquid UU-Matter](LiquidUU-0.7.10-universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    LogisticsPipes|Main [Logistics Pipes](LogisticsPipes-MC1.4.6-0.6.9.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    MCProtect [MCProtect](MCProtect.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    minechem [MineChem](MineChem-2.0.0pr2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    MFReloaded [Minefactory Reloaded](MineFactoryReloaded_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    MFR_CompatGrass [MFR Grass Fertilizer Addon](MineFactoryReloaded_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    AdvancedSolarPanel [Advanced Solar Panels](mod_AdvancedSolarPanels_3_3_2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ModularForceFieldSystem [Modular ForceField System V2](ModularForceFieldSystemV2.2.8.2.13.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    MoreCraftRecipe [MoreCraftRecipe](MoreCraftRecipe_V1.7.0_For_MC1.4.6-universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Mystcraft [Mystcraft](mystcraft-uni-1.4.6-0.9.5.00[1].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Paintball [Paintball](Paintball.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PamHCBase [Pam's HarvestCraft Base](Pam's HarvestCraft Base 1.01 %28MC 1.4.6%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PowerConverters [Power Converters](PowerConverters_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Mark-Crops [Magic Crops](PowerCrystalsCore_1.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ProjectZulu|Core [Project Zulu Core](ProjectZuluCompletev0.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ProjectZulu|Blocks [Project Zulu Block and Items](ProjectZuluCompletev0.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ProjectZulu|Mobs [Project Zulu Mobs](ProjectZuluCompletev0.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ProjectZulu|World [Project Zulu World](ProjectZuluCompletev0.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Railcraft [Railcraft](Railcraft_1.4.6-6.12.1.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RecipeRemover [Recipe Remover](reciperemover-v1.1-universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCore [RedPower](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerBase [RP Base](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerMachine [RP Machine](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCompat [RP Compat](RedPowerCompat-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWiring [RP Wiring](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLogic [RP Logic](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLighting [RP Lighting](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWorld [RP World](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerControl [RP Control](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    SeasonsMod [The Seasons Mod](Seasons_Mod_v1.7.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    StevesCarts [Steve's Carts](StevesCarts2.0.0.a40[1].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Thaumcraft [Thaumcraft](Thaumcraft3.0.1c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    TC [Traincraft](Traincraft-3.1.13_010.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    snyke7_Transformers [Transformers](Transformers v1.7a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    UsefulFood [UsefulFood](usefulfood_v1.2.3-universal_cn.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WiduXChristmas2012 [WiduX's Christmas 2012](WiduX's%20Christmas.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ZAMod [Zombie Awareness](Zombie Awareness v1.81 Mod for MC v1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    MSC [Mob Spawn Controls](Forge_MobSpawnControlsv1.4.6.0[1].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge Details: 1.4.6 (Bukkit API version 1.4.5-R0.2)
Plugins Loaded:AutoCleaner v1.3.1: Enabled, PerformanceMonitor v1.7.0: Enabled, SimpleHelpTickets v1.3.3: Enabled, Reloader v3.0.0: Enabled, PermissionsEx v1.19.5: Enabled, NoobResponse v3.0: Enabled, Simple Prefix v2.2.1: Enabled, mcMMO v1.3.14-b1258: Enabled, CoreProtect v1.72: Enabled and PrefixedPlayerlist v1.1.5: Enabled
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 6462 (361872 bytes; 0 MB) allocated, 5870 (328720 bytes; 0 MB) used
    Player Count: 16 / 101; [ServerPlayer['3billy'/835, l='world', x=472.90, y=72.00, z=1002.25], ServerPlayer['mi000731'/1044, l='world', x=499.83, y=72.00, z=1033.00], ServerPlayer['fien'/1046, l='world', x=517.98, y=91.00, z=944.63], ServerPlayer['chihag'/1176, l='world', x=496.34, y=72.00, z=1033.02], ServerPlayer['letea255'/1379, l='world', x=796.87, y=62.00, z=1213.69], ServerPlayer['tiara52000'/3093, l='world', x=500.76, y=72.00, z=1030.13], ServerPlayer['asd1010'/4725, l='world', x=516.16, y=75.00, z=935.70], ServerPlayer['aaaa6284'/4737, l='world', x=502.24, y=72.00, z=1031.44], ServerPlayer['Dictionary'/4841, l='world', x=497.07, y=72.00, z=1036.46], ServerPlayer['teddy1234'/6341, l='world', x=530.69, y=79.11, z=935.34], ServerPlayer['perdvct25'/6614, l='world', x=502.16, y=72.00, z=1035.07], ServerPlayer['gjvu'/7224, l='world', x=472.29, y=72.00, z=1050.45], ServerPlayer['joer'/10697, l='world', x=515.07, y=75.00, z=941.77], ServerPlayer['doisy'/964, l='world', x=503.76, y=72.00, z=1047.16], ServerPlayer['a30032549'/13564, l='world', x=500.50, y=72.50, z=1024.50], ServerPlayer['wujunyen'/13724, l='world', x=124.61, y=71.00, z=1375.23]]
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)

**Comment by ghost** [comment]
I think that is not issue related to bukkitforge

**Comment by mi000731** [comment]
but no use Bukkitforge no crash....

**Comment by dedo1911** [comment]
I got Redpower with bukkitforge and everything works perfectly. I think that the problem is some kind of incompatibility with some other mods. try to take them off and leave just redpower and the server. if it works, youre sure that the problem is related to other mods. if not, try to get a brand new minecraft_server.jar inject it forge universal, the latest version. and latest bukkitforge/redpower and everything. as i told you, i got everything working. so redpower is not the problem.

**Comment by SpoonsJTD** [comment]
Not reproduceable.
