### ISSUE TITLE
Inventory issues with shop plugins

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#349]
Server seems to not check players inventory with shop plugins specifically, chestshop. Can buy just fine, but when you try to sell despite having 500 of the item.. in this case dirt, in your inventory (not enough items to sell)

**Comment by Bucky420** [comment]
to be more pecice it i don't think hes got around to working on inventory stuff ... for me the only way you can make a working shop is if you interact with the hand cause you can clear the hand and or detect the item in it no problem at all but with something like chest shop you can just sit there selling diamonds or what ever and it wont take it out of your inventory....  now i don't know why /ci works ... clearinvintory (essentials command) in theroy chest shop should properly remove the item if /ci works but i rely dont know LOL

**Comment by Sageavatar** [comment]
Chestshop will also not pull items from a chest being sold from. It says that the chest is 'out of stock' regardless of how full the chest is. I have used item id's and Chestshop fulfills the sign correctly with both the item name and my name. I'd liek to confirm that you can buy from Adminshops fine.

**Comment by SpoonsJTD** [comment]
Chestshop is fixed.
