### ISSUE TITLE
Player coordinates are misreported to Bukkit plugins

### ISSUE THREAD

**Issue by kenneaal** [keepcalm/BukkitForge#350]
Intermittently, players are reported as being at the wrong coordinates to Bukkit plugins. They might be at +200 +60 +200, while the server reports them as being at 10 60 0. Apparently, this may be related to respawning, as the coordinates that are reported to Essentials are the spawn coordinates. Relogging fixes the issue. Some examples of commands affected by the bug:
- /position - shows the same coordinates constantly, even though you moved
- /sethome - Sets your home to the locked coordinates
- /tp - Other players attempting to teleport to you end up at the 'locked' coordinates rather than your real position.

http://vvcap.net/db/3jcXRUoDxiz5Uq4kRnMN.htp displays one player experiencing this bug.
BF build 91, autoported latest version of Essentials, Direwolf20 pack.

**Comment by kenneaal** [comment]
Testing has shown that this is indeed related to respawning. Reproduction:
- Set a spawnpoint with Essentials
- Move away from spawn
- Do /position - see that the position is correct vs. the client's coordinates as reported by minimap
- Die
- After respawning, do /position - see that it is the same as spawn coordinates.
- Move away from your spawnpoint
- Do /position again - the position will be unchanged, and not the same as minimap coords.

**Comment by lihad** [comment]
https://github.com/keepcalm/BukkitForge/issues/345 - Similar Issue.  Love the detail kenneaal!

**Comment by SpoonsJTD** [comment]
Devnote: I suspect this is similar to the bug causing reconnects to break certain features. The player object may need to be reset in the cache during death/respawn.

**Comment by kenneaal** [comment]
Awesome Keepcalm fix in build 97. Coordinates now reported correctly and interworld teleportation fixed. :)
