### ISSUE TITLE
Exception getting block type in world

### ISSUE THREAD

**Issue by TempestCraft** [keepcalm/BukkitForge#351]
This keeps crashing my server, it goes away and then comes back, this is the first time in about 20 days that it has happened again

http://pastebin.com/uKnZ5tqi

Im using build 91 of bukkitforge

**Comment by xfloh22** [comment]
delete the region the bug is in, that should fix it. it worked for me

**Comment by keepcalm** [comment]
Update, should be fixed.

**Comment by SpoonsJTD** [comment]
If not fixed, reopen.
