### ISSUE TITLE
Essentials Groupmanager NOT saving users

### ISSUE THREAD

**Issue by enterprise12nx** [keepcalm/BukkitForge#353]
Essentials groupmanager is not saving users in the "Users" file under
\Tekkit_Lite_Server_0.5.2\plugins\GroupManager\worlds\overworld\users

Whenever i promote them after restart they are back to default

**Comment by charlieTheBotDev** [comment]
I found that using the console to change the group settings (using commands) didn't work at all for me, have you tried using the commands in game?
Also, I've noticed that if you don't do /mansave it doesn't always save the group file.

**Comment by enterprise12nx** [comment]
yes everything works fine except it wont put the ppl in the user file

**Comment by charlieTheBotDev** [comment]
You could try this:

Promote the users
Delete the file from the server in the overworld folder
Use the /mansave command
Check that the file has been re-created and has the users in it.

I noticed that if the users are in the default group it doesn't save them to file (as they have the default permissions so they don't need to be saved) so make sure the default isn't set for more than one group as well.

**Comment by enterprise12nx** [comment]
hmm i could try, i have upgraded from Tekkit Classic, i ran for 4 months did all my own coding, 
whats also weird is i have 1 world Overworld
but groupmanager saves - Main -Overworld -nether -the_end

I dont see the_end or nether in the files but i assume its -1Dim and 1Dim?

**Comment by enterprise12nx** [comment]
The recent build seems to have fixed it! thanks for helping!
My Server: 24.46.189.96:25565
UPTIME: 2:30-10pm Eastern Time Zone 
if you wanna see :D

**Comment by Sageavatar** [comment]
Are permissions working using groupmanager?

**Comment by keepcalm** [comment]
Yep. Use the latest dev builds

**Comment by Sageavatar** [comment]
Confirmed working! keepcalm you're a badass!

**Comment by SpoonsJTD** [comment]
You may have to use gm mirror's to get per-world permissions to work, but they will work.
