### ISSUE TITLE
[CommandParameters] won't work properly

### ISSUE THREAD

**Issue by niklas-heer** [keepcalm/BukkitForge#358]
The @p, @a and @r parameters don't resolve the traget player name. The console always says "Player not found". If you type in the players name by hand the command is executed like it should.

**Comment by keplersj** [comment]
Any log errors?

**Comment by SpoonsJTD** [comment]
I suspect this is due to the Preprocessing event for commands not being fired. We've tried enabling the command events, but apparently while fixing some things, it breaks other working commands so it is currently disabled.

**Comment by SpoonsJTD** [comment]
Preprocessing was added, please recheck.

**Comment by zuch0698o** [comment]
I can confirm issue still present any hope for us?
