### ISSUE TITLE
PermissionsEX problems and plugin issues

### ISSUE THREAD

**Issue by Tampa** [keepcalm/BukkitForge#367]
Running build 109, Pex from github, chatmanager and modifyworld from main Pex download.
1. inheritance isn't working for some reason.
2. all bukkit. permission nodes are ignored, i can't op myself even with all permissions given( tried .\* and '*')
3. chatmanager is not displaying prefix or suffix and ranged chat completely disables chat
4. modifyworld doesn't work with blocks past id 256

permissions: http://pastebin.com/M7yGsKBk
Server info: http://two66.com/?page_id=46

**Comment by SpoonsJTD** [comment]
Dupes of #339, among others. Also, one problem per issue post, please. You can group related symptoms for a given plugin issue, but issues are hard to close if they contain lots of different problems.
