### ISSUE TITLE
[WorldEdit]Snapshots don't work

### ISSUE THREAD

**Issue by interfect** [keepcalm/BukkitForge#369]
I've configured WorldEdit to look for snapshots in the "backup" directory, and ran the command recommended by the Wiki to create a snapshot:

```
zip -v backup/`date "+%Y-%m-%d-%H-%M-%S"`.zip -r world
```

When I run /snap list, WorkdEdit reports that there are no snapshots.

This may be related to BukkitForge's decision to name worlds as integers; my overworld internally seems to be named "0" and not "world". I've tried putting the zip in the "world" directory under backups. I've tried changing the name of the top-level zip folder to "0", and putting it under "world". I've tried putting the zip under "0" inside the backup directory. I've tried putting the zip in the root of the backup directory. Nothing seems to work.

**Comment by SpoonsJTD** [comment]
Bukkitforge didn't 'decide' to name worlds as integers, we follow the convention set by MC. Plugins that assume they know what the folder structure is get confused.

**Comment by interfect** [comment]
So this would be a bug in the plugin, then?
