### ISSUE TITLE
Client crash with Build #115

### ISSUE THREAD

**Issue by orangeguy** [keepcalm/BukkitForge#371]
install BukkitForge#115 clientside.When do crafting in SMP ,client got crash.
Here is the crash report.

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 13-1-26 下午1:20
Description: Updating screen events

java.lang.NullPointerException
    at keepcalm.mods.bukkit.bukkitAPI.BukkitPlayerCache.getBukkitPlayer(BukkitPlayerCache.java:15)
    at keepcalm.mods.bukkit.forgeHandler.BukkitCraftingHandler.onCrafting(BukkitCraftingHandler.java:61)
    at cpw.mods.fml.common.registry.GameRegistry.onItemCrafted(GameRegistry.java:314)
    at sq.a(SlotCrafting.java:118)
    at rq.a(SourceFile:166)
    at ayo.a(PlayerControllerMP.java:461)
    at avf.a(GuiContainer.java:620)
    at codechicken.nei.forge.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
    at codechicken.nei.forge.GuiContainerManager.handleMouseClick(GuiContainerManager.java:587)
    at avf.a(GuiContainer.java:461)
    at aul.d(SourceFile:127)
    at avf.d(GuiContainer.java:722)
    at aul.m(SourceFile:111)
    at net.minecraft.client.Minecraft.l(Minecraft.java:1511)
    at net.minecraft.client.Minecraft.J(Minecraft.java:846)
    at net.minecraft.client.Minecraft.run(Minecraft.java:771)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at keepcalm.mods.bukkit.bukkitAPI.BukkitPlayerCache.getBukkitPlayer(BukkitPlayerCache.java:15)
    at keepcalm.mods.bukkit.forgeHandler.BukkitCraftingHandler.onCrafting(BukkitCraftingHandler.java:61)
    at cpw.mods.fml.common.registry.GameRegistry.onItemCrafted(GameRegistry.java:314)
    at sq.a(SlotCrafting.java:118)
    at rq.a(SourceFile:166)
    at ayo.a(PlayerControllerMP.java:461)
    at avf.a(GuiContainer.java:620)
    at codechicken.nei.forge.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
    at codechicken.nei.forge.GuiContainerManager.handleMouseClick(GuiContainerManager.java:587)
    at avf.a(GuiContainer.java:461)
    at aul.d(SourceFile:127)
    at avf.d(GuiContainer.java:722)
    at aul.m(SourceFile:111)

-- Affected screen --
Details:
    Screen name: avz

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [ClientPlayer['chengzi'/61967, l='MpServer', x=386.82, y=68.62, z=21.96]]
    Chunk stats: MultiplayerChunkCache: 961
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (108,64,232), Chunk: (at 12,4,8 in 6,14; contains blocks 96,0,224 to 111,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 1036386 game time, 1094254 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 30 total; [ClientPlayer['chengzi'/61967, l='MpServer', x=386.82, y=68.62, z=21.96], qc['爬行者'/62094, l='MpServer', x=444.50, y=65.00, z=68.50], qc['爬行者'/62099, l='MpServer', x=440.30, y=17.00, z=39.50], qd['末影人'/61978, l='MpServer', x=365.66, y=41.00, z=-25.88], oy['鸡'/61979, l='MpServer', x=367.42, y=73.00, z=-26.41], qn['骷髅'/61976, l='MpServer', x=445.69, y=13.00, z=8.36], qn['骷髅'/61977, l='MpServer', x=430.93, y=20.00, z=32.50], pe['羊'/61982, l='MpServer', x=406.06, y=63.00, z=-33.88], pe['羊'/61983, l='MpServer', x=436.15, y=64.00, z=-30.94], qp['蜘蛛'/61980, l='MpServer', x=438.13, y=41.00, z=-11.75], qc['爬行者'/62100, l='MpServer', x=441.84, y=17.00, z=39.50], pe['羊'/61981, l='MpServer', x=387.97, y=74.00, z=-47.97], pe['羊'/61970, l='MpServer', x=382.22, y=68.00, z=-4.38], oy['鸡'/61971, l='MpServer', x=384.53, y=68.00, z=-7.41], BT_EntityBackItem['未知'/27, l='MpServer', x=386.82, y=68.62, z=21.96], qc['爬行者'/61968, l='MpServer', x=372.50, y=22.00, z=9.50], qc['爬行者'/61969, l='MpServer', x=408.25, y=51.00, z=17.04], qr['僵尸'/61974, l='MpServer', x=405.50, y=31.00, z=-30.50], qn['骷髅'/61975, l='MpServer', x=444.84, y=13.00, z=8.59], pe['羊'/61972, l='MpServer', x=369.61, y=70.00, z=-16.56], qr['僵尸'/61973, l='MpServer', x=432.50, y=18.00, z=24.97], pe['羊'/61992, l='MpServer', x=419.84, y=64.00, z=-55.69], pe['羊'/61985, l='MpServer', x=321.53, y=69.00, z=-28.53], pe['羊'/61984, l='MpServer', x=367.03, y=74.00, z=-41.03], pe['羊'/61987, l='MpServer', x=375.38, y=73.00, z=-53.81], pe['羊'/61986, l='MpServer', x=445.41, y=67.00, z=-32.83], pe['羊'/61991, l='MpServer', x=402.50, y=68.00, z=-45.11], pe['羊'/61990, l='MpServer', x=401.63, y=77.00, z=-46.40], qn['骷髅'/62000, l='MpServer', x=346.53, y=26.00, z=21.13], qr['僵尸'/62001, l='MpServer', x=341.50, y=26.00, z=16.50]]
    Retry entities: 0 total; []
Stacktrace:
    at ayp.a(WorldClient.java:439)
    at net.minecraft.client.Minecraft.b(Minecraft.java:2401)
    at net.minecraft.client.Minecraft.run(Minecraft.java:787)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.4.7
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_10, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 111750648 bytes (106 MB) / 502005760 bytes (478 MB) up to 2112618496 bytes (2014 MB)
    Mod Pack: Unknown / None
    LiteLoader Mods: 1 loaded mod(s)
          - Macro / Keybind Mod version 0.9.8
    JVM Flags: 3 total; -Xincgc -Xms512m -Xmx2048m
    AABB Pool Size: 2265 (126840 bytes; 0 MB) allocated, 2 (112 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.26a FML v4.7.19.536 Minecraft Forge 6.6.0.505 Optifine OptiFine_1.4.6_HD_U_B5汉化：sy 18 mods loaded, 18 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    LainCraft [LainCraft](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BukkitForge [BukkitForge](BukkitForge-1.4.7-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BlockBreak [Block Break Event](BukkitForge-1.4.7-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    settingsapi [SettingsAPI](SettingsAPI-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    3ditems [3DItems](3DItems-1.6.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_ArmorStatusHUD [ArmorStatusHUD]([1.4.6]ArmorStatusHUDv1.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_ReiMinimap [mod_ReiMinimap]([1.4.6]ReiMinimap_v3.2_06_CN%28sy%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_BackTools [mod_BackTools](BackTools1.4.6v1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_ChatBubbles [mod_ChatBubbles](ChatBubbles146b_4185077.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    craftguide [CraftGuide](CraftGuide-1.6.5.12_CN%28sy%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    DamageIndicatorsMod [Damage Indicators](DamageIndicators[1.4.6]2.3.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    kirsybuuDoubleDoorMod [Double Door Mod](doubledoor-forge-v4.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_InvTweaks [Inventory Tweaks](InvTweaks-1.50-1.4.7_CN%28sy%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BukkitForge Details: 1.4.6 (Bukkit API version 1.4.5-R0.2)
Plugins Loaded:[No plugins loaded yet]
    LWJGL: 2.4.2
    OpenGL: AMD Radeon HD 6570 GL version 4.2.11762 Compatibility Profile Context, ATI Technologies Inc.
    Is Modded: Definitely; Client brand changed to 'forge,fml'
    Type: Client (map_client.txt)
    Texture Pack: Better_Minecraft_V1.3_-_by_Zapper49.zip
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 917 (51352 bytes; 0 MB) allocated, 17 (952 bytes; 0 MB) used

**Comment by SpoonsJTD** [comment]
Pretty sure we'd notice if clients were still crashing from players crafting.
