### ISSUE TITLE
[Core Protect]Inconsistent Logging And Unable To Rollback

### ISSUE THREAD

**Issue by UGLHong** [keepcalm/BukkitForge#372]
I used mysql to store the data logged. No error display but it just don't rollback even it says rollback started. The logging record seems to be inconsistent, partly were logged and partly will just show no block changes found although i just change it afew minutes ago. 

Using Core Protect version 1.72
http://dev.bukkit.org/server-mods/coreprotect/files/37-core-protect-v1-72/

**Comment by gccruz** [comment]
I can confirm this.

**Comment by ghost** [comment]
I recommend using hawkeye for now but to be honest, it should be able to pick up the block changes, but rollback isnt going to be to be recommended due to it being unstable in BF itself.

**Comment by krisdestruction** [comment]
I'll switch it to a MySQL database soon, but rollback seems to be working for me.

**Comment by ghost** [comment]
Try out the Coreprotect 1.6.3, it seems to work perfect for me despite running a 1.7.4 FTB server. It logs stuff, undoes stuff and all that. 

http://dev.bukkit.org/server-mods/coreprotect/files/33-core-protect-v1-63/

Edit: I admittedly got no clue about mysql but it works without it.

**Comment by krisdestruction** [comment]
I'm using v1.75 and it's working perfectly.

**Comment by ghost** [comment]
Hrm, didn't do squat for me yesterday on the 187 build. May have been updated with BF190 or its the MysQL difference? Never used MysQL. (Or Mindcrack modpack? Not sure how that affects things.) It didn't log at all, nor undid things till I switched to 1.6.3. 

Just threw it out there in case folks have the same problem, it fixed it for me. :P

Edit; 1.6.3 CP still working great with build 190. Haven't tested the other one on this build.

**Comment by keepcalm** [comment]
Fix: use CP 1.63
