### ISSUE TITLE
BukkitForge-1.4.5-3.jar no go

### ISSUE THREAD

**Issue by Mceonith** [keepcalm/BukkitForge#38]
tried to download the jar file from the raw link, go to run this jar and get "no main manifest attribute" i thought i had this file already running once, but hd went down so had to grab it again, am i doing something wrong or am i mistaking this for a prev build that was up and running?

**Comment by keepcalm** [comment]
Use Jenkins: http://build.aegisgaming.org/job/BukkitForge

**Comment by Mceonith** [comment]
tried the jenkins build and got the same thing

On Sat, Dec 22, 2012 at 6:20 AM, keepcalm notifications@github.com wrote:

> Use Jenkins: http://build.aegisgaming.org/job/BukkitForge
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/keepcalm/BukkitForge/issues/38#issuecomment-11636238.

## 

Michael Donovan
(603) 991-8983 cell

**Comment by keepcalm** [comment]
Intriguing. Might be an issue with ant. For a temporary fix, try replacing META-INF/MANIFEST.MF with [this one](https://github.com/keepcalm/BukkitForge/raw/master/META-INF/MANIFEST.MF)

**Comment by keepcalm** [comment]
Ok, fixed it now - starts up fine with latest forge. Just tested

**Comment by Mceonith** [comment]
am i doing something wrong? i download it.. i use a "batch file" to start the jar file and still get that same error.. something i'm missing? the line i use to start it with is "java -Xms512M -Xmx1024M -jar BukkitForge-1.4.6-6.jar
pause"

**Comment by keepcalm** [comment]
It's a coremod, run the server or the client with it in coremods.

**Comment by Mceonith** [comment]
OH.. i thought this iwas like the bukkit4vanillia type thing .. my bad lol
