### ISSUE TITLE
[Essentials] Essentials does not detect dimensions/worlds

### ISSUE THREAD

**Issue by kozlek** [keepcalm/BukkitForge#380]
When I try a /spawn in the nether or a Mystcraft Age, I'm teleported to the spawn point of the nether/Mystcraft Age and not to the real world :-(
Same problem with /home

**Comment by BubblyLemon** [comment]
I also have been having this issue.

**Comment by xfloh22** [comment]
the issue has been here since the very beginning. i think it might be forge fighting with bukkit

**Comment by kozlek** [comment]
Yes of course but this a very important fonction. In fact it's the only thing I need to complety use bukkit plugins...
Essentials bug, worldedit bug .... Very bad for a production server :-(
But I keep some hope and I know this will be fix one day :-)
I found some other solutions with mcpcplus but this build convert the world save : yes the issue is fix but the world is unusable with a classic forge server :-(

**Comment by kozlek** [comment]
Essentials tp/spawn works now !!!
I dont try worldedit but thanks you for this great work :-)

**Comment by kozlek** [comment]
But /sethome in the nether still doesn't work.

**Comment by gravypod** [comment]
Yes, this is being fixed shortly @Tberdy. If you attempt to use the minecraft /tp command it doesnt let you tp inter-dimensions. We are attempting to come up with a way to solve this problem

**Comment by SpoonsJTD** [comment]
This should be fixed in latest build.

**Comment by Obliviator** [comment]
Issue is not fixed...
