### ISSUE TITLE
Crash w/ build 126 on ChunkLoadEvent

### ISSUE THREAD

**Issue by gccruz** [keepcalm/BukkitForge#381]
---- Minecraft Crash Report ----
// There are four lights!

Time: 1/26/13 2:45 PM
Description: Exception getting block type in world

java.lang.NullPointerException
    at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.getWorld(BukkitChunk.java:54)
    at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:12)
    at org.bukkit.event.world.ChunkLoadEvent.<init>(ChunkLoadEvent.java:14)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.chunkLoadEvent(ForgeEventHandler.java:489)
    at net.minecraftforge.event.ASMEventHandler_114_ForgeEventHandler_chunkLoadEvent_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at zz.c(Chunk.java:1086)
    at im.c(ChunkProviderServer.java:150)
    at im.d(ChunkProviderServer.java:166)
    at yc.e(World.java:524)
    at yc.a(World.java:407)
    at yc.c(World.java:436)
    at akz.b(SourceFile:63)
    at in.g(WorldServer.java:420)
    at in.b(WorldServer.java:180)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:668)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.getWorld(BukkitChunk.java:54)
    at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:12)
    at org.bukkit.event.world.ChunkLoadEvent.<init>(ChunkLoadEvent.java:14)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.chunkLoadEvent(ForgeEventHandler.java:489)
    at net.minecraftforge.event.ASMEventHandler_114_ForgeEventHandler_chunkLoadEvent_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at zz.c(Chunk.java:1086)
    at im.c(ChunkProviderServer.java:150)
    at im.d(ChunkProviderServer.java:166)
    at yc.e(World.java:524)

-- Requested block coordinates --
Details:
    Found chunk: true
    Location: World: (95,29,-740), Chunk: (at 15,1,12 in 5,-47; contains blocks 80,0,-752 to 95,255,-737), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
Stacktrace:
    at yc.a(World.java:407)
    at yc.c(World.java:436)
    at akz.b(SourceFile:63)
    at in.g(WorldServer.java:420)
    at in.b(WorldServer.java:180)

-- Affected level --
Details:
    Level name: world
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 107 Drop: 0
    Level seed: 6008216163577690620
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 0 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:668)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

-- System Details --
Details:
    Minecraft Version: 1.4.6
    Operating System: Linux (amd64) version 2.6.32-042stab055.16
    Java Version: 1.7.0_03, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 237961528 bytes (226 MB) / 2102984704 bytes (2005 MB) up to 4824432640 bytes (4600 MB)
    JVM Flags: 1 total; -Xmx5176M
    AABB Pool Size: 4083 (228648 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    FML: MCP v7.25 FML v4.6.17.515 Minecraft Forge 6.5.0.489 58 mods loaded, 58 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge [BukkitForge](BukkitForge-1.4.7-126.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BlockBreak [Block Break Event](BukkitForge-1.4.7-126.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2 [IndustrialCraft 2](industrialcraft-2_1.112.170-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    AdvancedMachines [IC2 Advanced Machines Addon](AdvancedMachines_4.7a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ChickenChunks [ChickenChunks](ChickenChunks 1.2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ComputerCraft [ComputerCraft](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CCTurtle [ComputerCraft Turtles](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    EnderStorage [EnderStorage](EnderStorage 1.3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ExtrabiomesXL [ExtrabiomesXL](ExtrabiomesXL-universal-1.4.7-3.8.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    factorization [Factorization](Factorization-0.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Core [BuildCraft](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Builders [BC Builders](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Energy [BC Energy](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Factory [BC Factory](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forestry [Forestry for Minecraft](forestry-A-1.7.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Railcraft [Railcraft](Railcraft_1.4.6-6.13.1.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCore [RedPower](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerBase [RP Base](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerMachine [RP Machine](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCompat [RP Compat](RedPowerCompat-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWiring [RP Wiring](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLogic [RP Logic](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLighting [RP Lighting](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWorld [RP World](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerControl [RP Control](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion [Thermal Expansion](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Factory [Factory](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Energy [Energy](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Transport [Transport](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Transport [BC Transport](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Silicon [BC Silicon](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    TwilightForest [The Twilight Forest](twilightforest-1.14.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    XyCraft [XyCraft](xycraft-universal-1.4.6-0.9.44.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    GregTech_Addon [GregTech-Addon](GregTechMod_2.75b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2NuclearControl [Nuclear Control](IC2NuclearControl-1.4.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ModularForceFieldSystem [Modular ForceField System V2](ModularForceFieldSystemV2.2.8.2.14.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    OmniTools [OmniTools](OmniTools-2.2.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PortalGun [Portal Gun](PortalGun1.4.7v2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    SoulShards [SoulShards](SoulShards-v1.26-universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    StevesCarts [Steve's Carts](StevesCarts2.0.0.a42.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Thaumcraft [Thaumcraft](Thaumcraft3.0.1c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    TC [Traincraft](Traincraft-3.1.13_010.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|Core [WR-CBE Core](WR-CBE Core 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|Addons [WR-CBE Addons](WR-CBE Addons 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|RedPower [WR-CBE RedPower](WR-CBE RedPower 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    drceph.petrogen [Petroleum Generator]([1.4.6]PetroGen-1.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BinnieCore [Binnie Core](extrabees-1.4.9.12-prerelease.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ExtraBees [Extra Bees](extrabees-1.4.9.12-prerelease.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IronChest [Iron Chest](ironchest-universal-1.4.7-4.5.2.213.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    MiscPeripherals [MiscPeripherals](miscperipherals-2.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    AdvancedSolarPanel [Advanced Solar Panels](mod_AdvancedSolarPanels_3_3_2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    GraviSuite [Gravitation Suite](mod_zGraviSuite_1_6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ObsidiPlates [Obsidian Pressure Plates](obsidiplates-universal-1.2.0.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge Details: 1.4.6 (Bukkit API version 1.4.5-R0.2)
Plugins Loaded:GroupManager v2.0 (2.9.6) (Phoenix): Enabled, PTweaks v5.5: Enabled, WorldEdit v5.5.1: Enabled, Permissions v3.1.6: Enabled, TreeFeller v0.0.1: Enabled, UltraLogger v1.7.1: Enabled, Vault v1.2.20-b264: Enabled, Votifier v1.9: Enabled, WorldGuard v5.7: Enabled, Essentials v2.9.6: Enabled, EssentialsProtect v2.9.6: Enabled, EssentialsSpawn v2.9.6: Enabled, FrogAnnounce v2.1.1: Enabled, EssentialsGeoIP v2.9.6: Enabled, EssentialsChat v2.9.6: Enabled and EssentialsAntiBuild v2.9.6: Enabled
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 630 (35280 bytes; 0 MB) allocated, 492 (27552 bytes; 0 MB) used
    Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)

**Comment by SpoonsJTD** [comment]
This is no longer an issue.
