### ISSUE TITLE
setHelmet results in NPE

### ISSUE THREAD

**Issue by vemacs** [keepcalm/BukkitForge#384]
When running Essentials' /hat command, or when logging in using xAuth, I get:
[INFO] [STDERR]     at org.bukkit.craftbukkit.inventory.CraftInventoryPlayer.setHelmet(CraftInventoryPlayer.java:66)

**Comment by tuxtard** [comment]
I also experience this. When an authentication plugin wants to take away the inventory of the guest player, or bring it back, this error appears and the inventory is lost.

**Comment by gravypod** [comment]
Please launch minecraft with the no gui argument and get us that full output. That would help us fix this issue

**Comment by vemacs** [comment]
Appears to be fixed.

**Comment by vemacs** [comment]
Actually, there still is an NPE:
2013-02-09 13:18:35 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2013-02-09 13:18:35 [INFO] [STDERR]     at org.bukkit.craftbukkit.inventory.Craf
tInventoryPlayer.setHelmet(CraftInventoryPlayer.java:70)

setHelmet seems to work fine though, but when running /logout in xAuth, we get this.
