### ISSUE TITLE
PlayerMoveEvent cancelling not working

### ISSUE THREAD

**Issue by vemacs** [keepcalm/BukkitForge#386]
```
@EventHandler(priority = EventPriority.MONITOR)
public void onPlayerMoveEvent(PlayerMoveEvent event) {
    if (event.isCancelled() || event.getPlayer() == null) {
        return;
    }
    Player player = event.getPlayer();
    if(player.getState().isFrozen() == true){
        return;
    }
    event.setCancelled(true);
}
```

The above code doesn't do anything. Players can still move.
I'm using Build #137.
It works fine on Spigot #396.

**Comment by Bucky420** [comment]
ya ... there are a lot of issues with the player move event ... i don't think its finished yet or he has yet to patch it up

**Comment by gravypod** [comment]
You should not me cancelling on EventPriority.MONITOR. Try on EventPriority.HIGHEST
