### ISSUE TITLE
Vanish No Packet not working.

### ISSUE THREAD

**Issue by gccruz** [keepcalm/BukkitForge#391]
This plugin will not create a config file, nor will it allow any commands to work. It shows up in the Help menu. No error is outputed. 

http://dev.bukkit.org/server-mods/vanish/

**Comment by Bucky420** [comment]
true .. thoe i use sworn patrol

**Comment by gccruz** [comment]
How well does it work? I see its abandoned.

**Comment by SpoonsJTD** [comment]
Dupe of #330. Until version check is disabled, nothing we can do.
