### ISSUE TITLE
[Essentials][PEX] /home /spawn not working

### ISSUE THREAD

**Issue by FFID** [keepcalm/BukkitForge#393]
with 136 build and above do not work Essentials commands /spawn and /home. Says you do not have access for this command. But with 129 build everything works fine. configuration files have not changed.

**Comment by ghost** [comment]
you need to make sure that the spawnplugin is in there. also /home does work on build #154

**Comment by keepcalm** [comment]
You need to switch away from PEX. Fastest way is to go onto #bukkitforge on irc.esper.net and type `|pex2gm`.
You'll find a modifyworld replacement as well.
