### ISSUE TITLE
[Permissions + Essential + WorldEdit] Build 149

### ISSUE THREAD

**Issue by gpremier** [keepcalm/BukkitForge#395]
Hey there,

I just updated to build 149 and it's seem Essentials and WorldEdit permissions are not working anymore with PermissionsEx. But, WorldGuard's still working fine.

I haven't any crash report. Everything seem to get loaded but permissions won't work on these plugins.

Essentials : Can't use any commands. Alway get "You do not have access to..."
EssentialsAntiBuild : Can't build anything. Alway get "You do not have access to..."
WorldEdit : Can't use it. Alway get "You do not have permission..."
WorldGuard : Working very good.

As the owner of my server, my permission node is simple : '*'

I've try many build yesterday. I got this problem since build 137. For now I'm keeping Build 97 who is the stable one for me.

I hope this problem can be solved. Thank in advance. Have a nice day.

**Comment by keepcalm** [comment]
Sorry, PEX is not going to be supported anymore. We suggest changing to any plugin that isn't PermissionsEx for permissions.

If you use PEX you can use http://pex2gm.cgw.me/ to convert your permissions file and http://gravypod.com:8111/viewLog.html?buildId=lastSuccessful&buildTypeId=bt14&tab=artifacts&guest=1 to replace ModifyWorld. We recommend GroupManager over any other (PermissionsEx in particular) permissions plugins. For a list of reasons why, please read http://bit.ly/QBTtcQ
