### ISSUE TITLE
Teleporting creates Nether Portal

### ISSUE THREAD

**Issue by ruifung** [keepcalm/BukkitForge#399]
using build 168, teleporting (Same dimension or cross dimension) creates a Nether Portal.

**Comment by Maxander** [comment]
Same with build 174 when using essentials spawn home and other teleport commands.
Creates a netherportal at your original preteleport position.

**Comment by Maximuscr31** [comment]
I am having the same issue. It is becoming quit the problem with version 174

**Comment by Malcanteth** [comment]
r187, works fine

**Comment by ruifung** [comment]
Confirm fixed.
