### ISSUE TITLE
Crashing when crafting in multiplayer

### ISSUE THREAD

**Issue by xChickens** [keepcalm/BukkitForge#409]
If I log onto another multiplayer server, when I try to craft an item, the game crashes.
Pastebin: http://pastebin.com/bj39w9dr

**Comment by keepcalm** [comment]
Looks like a bug where it's being called on the client. Check you're on the latest.

**Comment by xChickens** [comment]
Updated it, and I still get the exact error. Seems like something wrong between Nei and Bukkit Forge? I reinstalled also.

**Comment by xChickens** [comment]
Fixed
