### ISSUE TITLE
[COMMAND] VariableTriggers - Custom Commands Don't Work

### ISSUE THREAD

**Issue by Lostferret** [keepcalm/BukkitForge#411]
Every Aspect of Variable triggers seems to work except for Custom Commands

I will script a simple command and when entered in-game all I get is a "Unknown Command: try /help..." etc.

Is this your end or theirs?

EDIT: Variable triggers 1.2.2, BukkitForge r187 (though It hasn't worked on past versions either)

**Comment by keepcalm** [comment]
This is my end. When I enable the event that it needs though, all commands break.

**Comment by Lostferret** [comment]
Alright, Please post when this is fixed, it's the only thing keeping me from updating to Lite and FTB.  Thanks so much and awesome work

**Comment by SpoonsJTD** [comment]
This should be resolved.
