### ISSUE TITLE
[builds 180-190] Any one else having issues with sign colors??? in 

### ISSUE THREAD

**Issue by Bucky420** [keepcalm/BukkitForge#417]
i use essentials for sign colors when you try to do a sign color it just puts a ?! when i get around to it ill see if it outputs any errors to console

**Comment by keepcalm** [comment]
Update, you're almost 100 builds behind.

**Comment by Bucky420** [comment]
LOOOZ i ment 180-190

**Comment by SpoonsJTD** [comment]
Dupe dupe dupity dupe.
