### ISSUE TITLE
[PermissionsEx] Build #190 - Permissions not working.

### ISSUE THREAD

**Issue by darkvirus** [keepcalm/BukkitForge#418]
I have permissions in SQL

Typing 'pex user bob' in console shows

bob is member of Admin

But i cannot place blocks, or break blocks.

Permission in SQL for user is 

Group : Admin
Permission : *
World : overworld

No errors in forgelog or console, and none of the versions of pex i have used output anything when 'pex toggle debug' is used(it says debug activated, but no debug messages are generated), when made an OP via console, everything works.

**Comment by Sageavatar** [comment]
I have this issue no matter what permissions manager I use. As far as I'm aware _no_ permissions work. I have not tried editing the permissions.yml for tekkit lite directly as of yet.

**Comment by darkvirus** [comment]
Sage - Try using version #91 - its what im using at the moment and pex works (mostly), but a few other bugs ie: cross world TP doesnt work.

**Comment by Nintendofreaker** [comment]
I tried PermissionsBukkit, and it works very well. Get the latest download in this link: http://forums.bukkit.org/threads/admn-dev-permissionsbukkit-v1-6-official-default-groups-plugin-1-2-5-r3-0.26785/

If you want my Premade permissions config.yml, here it is:
http://www.mediafire.com/?i1cpssi1fccfy4y

**Comment by ghost** [comment]
PermissionsEx is never going to be supported by BukkitForge. http://bit.ly/QBTtcQ
