### ISSUE TITLE
Promission problem and commands do not work

### ISSUE THREAD

**Issue by HonorLee-cn** [keepcalm/BukkitForge#42]
Hi~

I am using the newest BukkitForge 1.4.5 - 3,but no one command work

i just use Essentials on my server ,and no GroupManager

when i use commands like /fly or /exp,the console panel shows success,but it doesn't work in game

And i have enabled the Coreprotect as well,it shows "You do not have promission to use that command" when i use "/co i" or "coreprotect"

is there some thing wrong?

**Comment by HonorLee-cn** [comment]
finally i have tried the BukkitForge 1.4.5-3 with clear Minecraft - forge server,no more mods and plugins except ess.

but the commands still can not work,just like '/sethome' & '/home',it shows up 'Home set' and will Teleportation in 3sec. and nothing happend,very strange

**Comment by keepcalm** [comment]
Try adding [this file](https://github.com/keepcalm/BukkitForge/blob/master/lib/guava10-renamed.jar?raw=true) to your mods folder. It should fix some commands (and use [jenkins](http://build.aegisgaming.org/job/BukkitForge) builds)

**Comment by HonorLee-cn** [comment]
I have tried and it's can be used on 1.4.6,but only some commands like "/home" "/sethome" "top" worked well,that's a good news,but it is very sad that i have to use Minecraft 1.4.5 as my server~~hope bukkitforge more stronger in the future.

Well ~ i have read your codes of blockbreak and learend the asm handle part of it,that's a cool way to fix onbreak event which has been lost in forge.

It will be prety awesome to complete these events like onBlockPlace,onItemUse,onItemDrop… :)

**Comment by keepcalm** [comment]
Thanks :D I'm aware of some commands misbehaving, and I'm now going to start the task of going through the code and fixing it.
