### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by forrestdemars** [keepcalm/BukkitForge#428]
I am no not sure exactly what is going on...but this is the error I get

[2/1/2013 11:55:11 PM] Michael Italiano: 01.02 21:54:49 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.getName(BukkitPlayer.java:119)
01.02 21:54:49 [Server] INFO java.lang.NullPointerException
01.02 21:54:49 [Server] INFO WARNING: Internal task failed: 
01.02 21:54:49 [Server] INFO at fy.run(SourceFile:849)
01.02 21:54:49 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
01.02 21:54:49 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:588)
01.02 21:54:49 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
01.02 21:54:49 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
01.02 21:54:49 [Server] INFO at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
01.02 21:54:49 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:28)

**Comment by SpoonsJTD** [comment]
What version of BukkitForge? Does this happen with latest version?
