### ISSUE TITLE
MOTD Plugins not working

### ISSUE THREAD

**Issue by SpiritedDusty** [keepcalm/BukkitForge#44]
When using essentials or any plugin that displays a message on login isn't working. Ussally it will say "Welcome to the server" or something like that but it doesn't show anything message at all. When typing /motd manually works. It gives no errors but it just shows nothing to the user at all.

Forge: 4.6.12.511
BukkitForge: 1.4.6-6

**Comment by Thornas88** [comment]
this works to 50% show "Promissions problem ..."

Setspawn and spawn commands not work

and group manager and Essentials chat not work.

**Comment by SpiritedDusty** [comment]
Well permissions, setspwan, and spawn are working for me. Essentials chat doesn't show my rank.

**Comment by ghost** [comment]
The plugins can read ,but I can't use all the command of its

**Comment by keepcalm** [comment]
I thought I fixed this, bukkit has so many login events it's not funny (I need to find the right one...)

**Comment by keepcalm** [comment]
Fixed, use the build in dist while jenkins is down
