### ISSUE TITLE
[WorldGuard][RedPower] redstone signals acting up inside a region.

### ISSUE THREAD

**Issue by Stickky** [keepcalm/BukkitForge#440]
just thought id post this, it may not be a BukkitForge problem but its here just in case.
deployers wont deploy a bucket of water/lava inside a WG region. dispensers will deploy inside a region but only with a redstone torch but not a timer.
these both work fine outside the region. filters seem fine with timers and torches inside or out of a region.

**Comment by NNickey** [comment]
I have exactly the same problem. Block ids arent working properly..

**Comment by mafe9191** [comment]
i have found solution at the problem  /region addowner (nameregion) [redpower] and the red power work perfectly

**Comment by EDSman11** [comment]
Wow, it actually works! That's awesome thanks! I just hope nobody named
[redpower] gets on my server :P jk we have a whitelist
