### ISSUE TITLE
[Essentials Latest] GEOIP Error and /back Still not working

### ISSUE THREAD

**Issue by enterprise12nx** [keepcalm/BukkitForge#442]
I installed the latest Essentials including GeoIP and i get an error about it, it has forge mod loader pieces in it i believe.

/back on death still does not work, they have ther perms.
also using /back ur always looking up/down

**Comment by gccruz** [comment]
it seems to work find for me. I'm running the latest Essentials and build 201 Bukkitforge

**Comment by enterprise12nx** [comment]
im using this version: http://dev.bukkit.org/server-mods/essentials/
i get errors from GeoIP unless it was just fixed maybe? i will try again
