### ISSUE TITLE
monodim TP: CraftWorld{name=overworld} > CraftWorld{name=overworld}

### ISSUE THREAD

**Issue by forrestdemars** [keepcalm/BukkitForge#445]
My console is spammed by this message everytime someone uses an essentials teleport related command.

monodim TP: CraftWorld{name=overworld} > CraftWorld{name=overworld}

**Comment by ruifung** [comment]
Looks like a debug message..

**Comment by SpoonsJTD** [comment]
Will be fixed in latest build.
