### ISSUE TITLE
/kit doesn't work for players. (Essentials, simple kits,kit master, cobra kits)

### ISSUE THREAD

**Issue by gccruz** [keepcalm/BukkitForge#446]
/kit doesn't work in essentials or other plugins. If you make custom kits in essentials, they revert to originals default in config. Other plugins where you create kits in game, the revert to 0:0 air with qty of 0. This is with vanilla items and modded items. 

http://dev.bukkit.org/server-mods/simplekit/
http://dev.bukkit.org/server-mods/cobrakits/
http://dev.bukkit.org/server-mods/kitmaster/
http://dev.bukkit.org/server-mods/essentials/

**Comment by enterprise12nx** [comment]
Use essentials 2.9.6 or PREessentials (released yesterday)
kits work, make sure to add the kits while servers offline and then give the perm: essentials.kits.tools (tools being the kit name)
