### ISSUE TITLE
(mystcraft & towny) towny not registering mystcraft worls and spams client

### ISSUE THREAD

**Issue by darkcamo12** [keepcalm/BukkitForge#447]
server throws this error http://pastebin.com/QKQPbbVL
and spams the client with "world not registered"

any ideas would be helpful 

also i have noticed it registered twilight_forest just fine but none of the mystcraft ages

**Comment by Fureniku** [comment]
I think Towny allows you to disable on certain worlds. Try disabling any mystcraft worlds and see if it at least stops the error?

I've not used Mystcraft, just throwing an idea out there. :P

**Comment by ElgarL** [comment]
This will be caused by BF not generating either a WorldLoadEvent or a WorldInitEvent.

**Comment by kozlek** [comment]
Same issue for me :-(
It's not possible to disable Towny on mystcraft world because they aren't detected by the plugin...

**Comment by ghost** [comment]
I have a basic plugin I created at the moment just to monitor events and I can confirm that WorldInitEvent is not being thrown. I am in the process of making it better and monitoring more events. Will be using this w/ the Development Team to make sure all Events are being generated properly.

**Comment by ghost** [comment]
Use /townyadmin reload to fix this. Seems towny does not load new worlds automaticly when created which is not wierd actually.

**Comment by ElgarL** [comment]
It does, when the correct events are triggered. Wait for a fix to BF.

**Comment by darkcamo12** [comment]
new error as far as i can tell http://pastebin.com/m30Vcupu

**Comment by SpoonsJTD** [comment]
Please recheck, world stuff was reworked recently.

**Comment by alexbegt** [comment]
Fixed.
