### ISSUE TITLE
[Towny] Accept and Deny commands not registered

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#457]
Build: 209 (possible latest build aswell)
Plugin: Towny
Version: Latest
Problem:
Im using Towny with the questionar.jar so people get invites for when they are added to a town and they get the message to use either /accept or /deny in response.
The /accept and /deny give the standard minecraft error of a unknown command.
The /town accept and deny give a message: Towny unregistered command.

No errors on console.

**Comment by gravypod** [comment]
Did you restart the server, reloads dont work with BukkitForge yet

**Comment by ghost** [comment]
Multiple times even.
It does not matter if a town is just made or existing for more than a few days. The commands arent registered.
and towny reload does work (if you make a new mystcraft world for example)

**Comment by gravypod** [comment]
Ok, Ill ask elgar if he can pitch in on this error.

**Comment by ElgarL** [comment]
runs on PlayerCommandPreprocessEvent.

**Comment by gravypod** [comment]
@ElgarL added the PlayerCommandPreprocessEvent. Test now

**Comment by dwarvmater** [comment]
Nope, still doesn't work :(

**Comment by xKillerbees** [comment]
I can confirm this issue with 225.

**Comment by xKillerbees** [comment]
Along with 226, says unknown command.

**Comment by gravypod** [comment]
Ill post here when I think we fixed it.

**Comment by ElgarL** [comment]
This will need a new hook into Forge as forge will only pass registered commands in it's event. Bukkit needs a pre process command event to fire from Forge before the command has been validated.

**Comment by xKillerbees** [comment]
Any way to modify questioner or something to create a new command so people can invite?

**Comment by ElgarL** [comment]
Yes it could be done, but that's not the point of BukkitForge. BF is aimed at being a full Bukkit API implementation for Forge. As such it needs to operate in exactly the same manner.

**Comment by Ionaru** [comment]
A workaround is that you open the town with '/t toggle open', let the person in question join with '/t join [town]' and then close the town afterwards with '/t toggle open'.
I hope this helps.

**Comment by SpoonsJTD** [comment]
Preprocess was implemented properly and accept and join should work now.
