### ISSUE TITLE
Teleport based commands

### ISSUE THREAD

**Issue by Maximuscr31** [keepcalm/BukkitForge#46]
So I got permissions in and working other than any of the teleport based commands won't work. /home /spawn /tpa /tp /tphere unless the person is op. Otherwise it says teleporting in 2 seconds don't move. It never teleports and gives no errors. Any ideas?

**Comment by Wolftein** [comment]
Also after a while all of them stop working and spam NULL

**Comment by Wolftein** [comment]
This is fixed aswell!, close
