### ISSUE TITLE
WorldGuard Blacklist feature does not work

### ISSUE THREAD

**Issue by EDSman11** [keepcalm/BukkitForge#463]
I attempted to blacklist Tier 4 missiles on my Voltz server with WorldGuard's blacklist using the data value but I noticed that it did nothing. I then found out that using data values isn't going to be added into WorldGuard until version 6.0 comes out. I then decided to try and block something simple like acquiring tnt, but it still didn't work... Does anyone know if CreativeGuard or CreativeControl work as an alternative solution to this problem?

**Comment by FalconHunter** [comment]
ya part of my worldguard and essentials protect doesn't work like tnt prevention and fire spread the tnt still explodes and the fire still spreads for both world guard and essentials protect. its the most recent world guard.

**Comment by ghost** [comment]
Bump. Same issue with both

**Comment by SpoonsJTD** [comment]
Dupes of others.
