### ISSUE TITLE
TARDIS won't build

### ISSUE THREAD

**Issue by Taylor7500** [keepcalm/BukkitForge#474]
While trying the bukkitforge version of the TARDIS plugin (found here: http://files.electro-gaming.org/BukkitForge/), when trying to build a tardis (Redstone torch on top of Lapis block on top of Iron block) the blocks will be placed but the TARDIS won't build as a result - the blocks will just sit there and do nothing. The server is running Mindcrack, all of the forgeukkit configs are set on the default and it's the only plugin installed. The commands show up and everything, but the TARDIS won't build.

**Comment by EDSman11** [comment]
I seem to be able to build the TARDIS perfectly fine... The plugin runs normally with a few glitches along the way like when you move the tardis it just copys itself and u end up with 2 tardises one in the old location and one in the new. The interior you have to mine out but it builds perfectly fine...

Try using it with the latest version of BukkitForge is all I could recommend...

Btw, thanks for creating this ticket.. I'm a huge Doctor Who fan and I would have never known that this plugin existed without reading about it here...

**Comment by SpoonsJTD** [comment]
#419 Dupe.
