### ISSUE TITLE
New World stuck on Building Terrain

### ISSUE THREAD

**Issue by SpoonTheMan** [keepcalm/BukkitForge#479]
The game freezes on Building Terrain only with BukkitForge Installed, here's an error report:

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2/9/13 12:09 AM
Description: Exception in server tick loop

java.lang.NullPointerException
    at org.bukkit.craftbukkit.CraftChunk.getWorld(CraftChunk.java:70)
    at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:12)
    at org.bukkit.event.world.ChunkPopulateEvent.<init>(ChunkPopulateEvent.java:16)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.populateChunks(ForgeEventHandler.java:925)
    at net.minecraftforge.event.ASMEventHandler_48_ForgeEventHandler_populateChunks_Post.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at abb.a(ChunkProviderGenerate.java:613)
    at im.a(ChunkProviderServer.java:258)
    at zz.a(Chunk.java:1258)
    at im.c(ChunkProviderServer.java:153)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:310)
    at bdz.a(IntegratedServer.java:114)
    at bdz.c(IntegratedServer.java:137)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
    at fy.run(SourceFile:849)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.4.7
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_13, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 3498839248 bytes (3336 MB) / 3892314112 bytes (3712 MB) up to 5726666752 bytes (5461 MB)
    JVM Flags: 2 total; -Xmx6144M -Xms3072M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 69
    FML: MCP v7.26 FML v4.7.4.520 Minecraft Forge 6.6.0.497 Optifine OptiFine_1.4.6_HD_U_D3 38 mods loaded, 38 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MoreExplosives [More Explosives Mod](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_ReiMinimap [mod_ReiMinimap](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_TooManyItems [mod_TooManyItems](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BukkitForge [BukkitForge](BukkitForge-latest.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BlockBreak [Block Break Event](BukkitForge-latest.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GuiAPI [GuiAPI](GuiAPI-0.15.2-1.4.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AS_MultiMine [Multi Mine](MultiMine_1.4.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Epic Weapons [Epic Weapons]([SP&MP] Epic Weapons v 0.5.0 [1.4.6].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BattleTowers [Battle Towers](BattleTowers_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CustomSpawner [DrZhark's CustomSpawner](CustomMobSpawner 1.11.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CustomNpcs [CustomNpcs 1.4.5](CustomNPCs_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    DeathCounter [DeathCounter](DeathCounter1.4.7v2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MoCreatures [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v4.5.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    eplus [Enchanting Plus](EnchantingPlus-1.12.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FlansMod [Flan's Mod](Flans Mod 2.1.1 for Minecraft 1.4.7 Universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GraviGun [GraviGun](GravityGun1.4.7v1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    jammyfurniture [Jammy Furniture Mod](jammy-furniture-mod%28adg%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    lightWand [Light Wand](lightWand.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MagicYarn [Magic Yarn](MagicYarn_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Millenaire [Millénaire](millenaire4.1.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    multiCraftingTable [Multi Crafting Table](multiCraftingTable.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Mystcraft [Mystcraft](mystcraft-uni-1.4.6-0.9.5.00.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Paintball [Paintball](Paintball.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ParachuteMod [Parachute Mod](parachute-1.4.7-forge-497.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    PortalGun [Portal Gun](PortalGun1.4.7v3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RopesPlus [Ropes+](RopePlus_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    SecretRoomsMod [The SecretRoomsMod](SecretRoomsMod-universal-4.4.1.158.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    SuperSlopesCorners [SuperSlopes-Corners](SuperSlopes-4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    SuperSlopesIntCorners [SuperSlopes-IntCorners](SuperSlopes-4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    SuperSlopesSlopes [SuperSlopes-Slopes](SuperSlopes-4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AS_UpdateCheck [AtomicStryker Update Check Mod](UpdateCheckerMod_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    weaponmod [Balkon's WeaponMod](Weaponmod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AIBlock [AIBlock](Weather v1.3 Mod for MC v1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtendedRenderer [Extended Renderer](Weather v1.3 Mod for MC v1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WeatherMod [Weather and Tornadoes](Weather v1.3 Mod for MC v1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BukkitForge Details: BukkitForge null-null (with bukkit API version 1.4.7-R0.1)
Plugins Loaded:[Didn't get far enough to load plugins :/]
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'forge,fml'

**Comment by mmis1000** [comment]
remove the bukkitforge and don't install back until the world full generated
everything should work fine

**Comment by mmis1000** [comment]
same with issue #477
