### ISSUE TITLE
Factions Plugin Issue

### ISSUE THREAD

**Issue by kotlerman** [keepcalm/BukkitForge#48]
Factions plugin doesn't work.

Server Log:

> 2012-12-28 14:21:43 [INFO] [BukkitForge] Bukkit API for Vanilla, version 1.4.5-3 starting up...
> 2012-12-28 14:21:43 [INFO] [BukkitForge] This server is running Minecraft Server 1.4.5, using FML 4.5.2.459,
> MinecraftForge 6.4.1.410, MCP v7.23 version BukkitForVanilla 1.4.5-R0.2 (Implementing API version 1.4.5-R0.2)
> 2012-12-28 14:21:43 [INFO] [BukkitForge] Completing load...
> 2012-12-28 14:21:43 [INFO] [BukkitForge] Plugins are being loaded...
> 2012-12-28 14:21:43 [INFO] [com.massivecraft.factions.P] [Factions] Loading Factions v1.6.9.2
> 2012-12-28 14:21:43 [INFO] [BukkitForge] Loading PostWorld plugins...
> 2012-12-28 14:21:43 [INFO] [com.massivecraft.factions.P] [Factions] Enabling Factions v1.6.9.2
> 2012-12-28 14:21:43 [SEVERE] [BukkitForge] [Factions v1.6.9.2] GSON lib not found. Your CraftBukkit build is too old (< 1.3.2) or otherwise not compatible.
> 2012-12-28 14:21:43 [INFO] [BukkitForge] [Factions v1.6.9.2] Now I suicide!
> 2012-12-28 14:21:43 [INFO] [com.massivecraft.factions.P] [Factions] Disabling Factions v1.6.9.2
> 2012-12-28 14:21:43 [INFO] [BukkitForge] [Factions v1.6.9.2] Disabled
> 2012-12-28 14:21:43 [INFO] [BukkitForge] Going to load perms file: permissions.yml
> 2012-12-28 14:21:43 [INFO] [BukkitForge] Server permissions file permissions.yml is empty, ignoring it
> 2012-12-28 14:21:43 [INFO] [BukkitForge] Loaded plugins: 
> 2012-12-28 14:21:43 [INFO] [BukkitForge] Factions- Enabled: false

**Comment by keepcalm** [comment]
This probably has to do with me using the wrong version of GSON, I'll track down the version bukkit used and fix it today.
