### ISSUE TITLE
PermissionEx working wierd(maybe Essentials bug),World Border dont generating new chunk's.

### ISSUE THREAD

**Issue by fhntv24** [keepcalm/BukkitForge#480]
I have a few problems.
1.PermissionEx when i put permission to Essentials it's dont work,like all comand's dont work.(spawn,gm,warp,give,i,etc) only if you op they will work
2.World border cant gen. new chunk's without error-
2013-02-09 00:57:15 [INFO] [WorldBorder] [Fill] 959 more chunks processed (959 total with 942 skipped, ~0,1%) (free mem: 10433 MB)
2013-02-09 00:57:38 [INFO] [WorldBorder] [Fill] 0 more chunks processed (959 total with 942 skipped, ~0,1%) (free mem: 10449 MB)
that all what he say....to log/console

**Comment by squidicuzz** [comment]
PermissionsEx doesn't work with BukkitForge, use GroupManager.

See here about WorldBorder: #456

**Comment by fhntv24** [comment]
i downloaded PermissionsEx from github plugins list :/

**Comment by fhntv24** [comment]
from Keepcalm topic:BukkitForge Open Beta - now with PermissionsEx and loads of other stuff!

**Comment by fhntv24** [comment]
and Pex2GM dont work too :( ....why?

**Comment by chrisgward** [comment]
Pex2GM has been fixed

**Comment by chrisgward** [comment]
Sorry, have been doing a lot of work on it today XD

**Comment by fhntv24** [comment]
how about pex?

**Comment by chrisgward** [comment]
doubt it, but why would you need it when there's pex2gm?

**Comment by fhntv24** [comment]
beacos GM wasnt working for me,and it's for a few people better that GM

**Comment by chrisgward** [comment]
Try running your file through pex2gm again, I made a lot of changes to it including some bug fixes.

**Comment by vemacs** [comment]
PermissionsEX doesn't work properly with each new version of Bukkit, so I don't see why it would work with BukkitForge.

See https://docs.google.com/document/d/1BIgAU7senSG1hY0BjQAQFAnbuOqFhpln7ffN6pkOp4s/edit?pli=1

**Comment by fhntv24** [comment]
that is bug WITH BUKKIT FORGE PEX,not with bukkit pex.......

**Comment by vemacs** [comment]
BukkitForge is less stable than Bukkit, so how would PEX inject its bindings in, if the bindings aren't even implemented in BukkitForge?

Basically, PEX is an unstable and badly developed plugin, and should never be used unless you want extreme control over player events.

**Comment by gravypod** [comment]
@vemacs +1

**Comment by fhntv24** [comment]
yea i know,i'm using GroupManager,but i'm saying that about off. release of PEX FOR BUKKIT FORGE....so that is bug with OFF. bukkit forge

**Comment by vemacs** [comment]
Why do you need PEX anyways?

Don't you understand that it will NEVER be supported with BukkitForge?
