### ISSUE TITLE
Nothing happening

### ISSUE THREAD

**Issue by jackie1272** [keepcalm/BukkitForge#481]
So I think I'm making a mistake since I don't know how to do all of this and I'm stumbling through the dark. But BukkitForge is sitting in the coremods folder and nothing is happening. I installed both Forge and Bukkit so I would have the coremods and plugins folders, but when I start my server with either one nothing is different. Forge does nothing new and won't use Bukkit plugins and Bukkit does nothing new and doesn't use Forge mods. Forgive me if I'm mistaken but I thought BukkitForge was supposed to allow both somehow. I'll admit that I wish the BukkitForge installation help actually guided through the entire process from vanilla Minecraft and nothing else installed to the end result, but that's probably too much to ask.

**Comment by fhntv24** [comment]
installed bukkit?heh you need just install VANILA server with forge,without bukkit.delete plugins folder and if it's created plugins folder then all ok,and that was you.

**Comment by jackie1272** [comment]
So I did what you said. Then I downloaded "BukkitForge-master.zip" and extracted it into the "coremods" folder. I also placed the .zip and the unzipped file into the coremods folder in case I was not supposed to extract it. I do not see a plugin folder created (assuming it is supposed to be created in the same folder as forge, the server software from mojang, the coremods and mods folder, etc.

**Comment by fhntv24** [comment]
1.you need only to copy .jar files
2.download LATEST forge AND BukKitForge from Jankins(http://build.aegisgaming.org/job/BukkitForge/ ,http://files.minecraftforge.net/)
3.what you OS,how much you have RAM,what MC version(if installing latest version dont help)

if you want i can send to you my server with Forge,BukKitForge

**Comment by jackie1272** [comment]
Thank you, I was able to figure it out with your help.

**Comment by fhntv24** [comment]
np,that is not problem for me :D
