### ISSUE TITLE
[Chat] Messages not 'splitting'

### ISSUE THREAD

**Issue by DerpgonCz** [keepcalm/BukkitForge#482]
Hello, so the issue is when a plugin sends a player a chat message (via Player.sendMessage(String msg)) and if it is longer than 80 or somewhere around that it should split into more messages, but it just writes down part of the text.

The example shows loaded plugins (Look at WorldGuard (prints WorldGu), it is written only to the allowed lenght and not more - as it should)
![2013-02-10_11 52 54](https://f.cloud.github.com/assets/3275947/143135/4381514a-7370-11e2-81f9-6f3114a0b162.png)

**Comment by ghost** [comment]
Bump. I am having this same issue

**Comment by AlexMason** [comment]
I am having this issue as well, this is very cruicial to me and is not functioning.

Also I can confirm this effects forge's sendChatToPlayer method!  Seems to override default and not account for additional length.

**Comment by SpoonsJTD** [comment]
Fixed.
