### ISSUE TITLE
BukkitForge Issue

### ISSUE THREAD

**Issue by futhermukker** [keepcalm/BukkitForge#49]
Having an issue with your ports not working., mainly WorldEdit.
Here is a link to my server log: http://dl.dropbox.com/u/95441499/ForgeModLoader-server-1.log

hope this helps.

Thank you for this mod, your hard work is appreciated.

**Comment by keepcalm** [comment]
WorldEdit is very complicated, I may create a mod which will depend on BukkitForge that is WorldEdit. That seems to be easiest

**Comment by futhermukker** [comment]
I truly appreciate the fact that you are looking into this so in depth Anything you can do would be awesome, even if you don't do anything further because of the "complexities" of WorldEdit, I thank you anyway.

but... a WorldEdit like mod for BukkitForge sounds good too ;)

**Comment by Wolftein** [comment]
This is fixed too!, close
