### ISSUE TITLE
Commands not returning output to rcon

### ISSUE THREAD

**Issue by airminer** [keepcalm/BukkitForge#496]
Plugins don't return their output to the rcon connection they are sent from, they are just printed to the server log.

**Comment by ghost** [comment]
They are working for me. I am using buycraft and all Rcon commands are executed

**Comment by airminer** [comment]
I have tried Essentials and CraftBukkitUpToDate commands. All the forge commands work (for example the /bukkitfore one as well) but /help or /cbutd doesn't. They get interpreted, and the output is printed to the console, but not to the rcon.

**Comment by SpoonsJTD** [comment]
dupe
