### ISSUE TITLE
[Essentials] Signs

### ISSUE THREAD

**Issue by BrockWS** [keepcalm/BukkitForge#501]
When ever i try to use essentials signs ([Gamemode], &5This is purple) it changes to !?. I have enabled the signs in the config. and i only have essentials core plugins installed. It works fine with craftbukkit

**Comment by eagl3s1ght** [comment]
I have noticed this happens with ChestShop.
Are you sure it is not fixed after relog?

**Comment by BrockWS** [comment]
I only have essentials installed and no it does get fixed

**Comment by Sageavatar** [comment]
This is a duplicate of #213

**Comment by SpoonsJTD** [comment]
Signs are fixed except for Buy/Sell/Trade, captured in a another issue.
