### ISSUE TITLE
WorldEdit mod blocks

### ISSUE THREAD

**Issue by Ehrlingby** [keepcalm/BukkitForge#503]
It seems that both WorldEdit 5.5.x and 5.4.x aren't able to place 4095 block (non-vanilla blocks) with BukkitForge, where did the WorldEdit port go that actually worked?

**Comment by mmis1000** [comment]
It's fixed in current version of bf
Just without redpower2 blocks
It seems use tile entity to record some information
And thus cause it invalid in current version of we

**Comment by Ehrlingby** [comment]
Oh ok, brilliant. I'll test it out as soon as I get home.
