### ISSUE TITLE
Jenkins

### ISSUE THREAD

**Issue by fhntv24** [keepcalm/BukkitForge#507]
http://build.aegisgaming.org/job/BukkitForge dont work,saying "unknow host"

**Comment by eagl3s1ght** [comment]
@fhntv24 Jenkins is at http://build.technicpack.net:8080/job/BukkitForge/
It clearly says so in README.md: https://github.com/keepcalm/BukkitForge/blob/master/README.md

**Comment by dequis** [comment]
This isn't a fucking bug. Stop posting non-issues here. A server being down isn't a defect in the software. Also, what the guy before me said, wrong address. Use some forum or chat for this crap instead.

**Comment by enterprise12nx** [comment]
Calm down jeeze, people make mistakes ok?
you dont have to flip off

**Comment by ghost** [comment]
I think some people are just annoyed with the OP because almost all his posts in the BukkitForge issues have been like this.

**Comment by dequis** [comment]
(ノಠ益ಠ)ノ彡┻━┻
