### ISSUE TITLE
{BukkitForge} Washing not clean...

### ISSUE THREAD

**Issue by ElgarL** [keepcalm/BukkitForge#509]
I ran BF THREE times and my washing is still dirty!!!.

Please fix this as my current underwear is starting to smell a little.

**Comment by gravypod** [comment]
We need a new milestone created. "Code2CleanTrowsers". I'll get on a new fix as soon as I can!

**Comment by dequis** [comment]
I don't think we have implemented the bukkit events to clean underwear. Haven't confirmed though, but maybe it's only your underwear that will stay dirty. Sorry for that.

**Comment by gravypod** [comment]
@dequis this is unacceptable! Screw fixing bugs! We need research on this matter ASAP!

**Comment by gv1222** [comment]
You may not have enough allocated RAM. Try downloading more here: www.downloadmoreram.com

**Comment by ghost** [comment]
Have you installed the WashingMachine.jar into your plugins folder? I have it installed with Build 1337 and my boxers are so clean that I can see my face in them.

**Comment by gravypod** [comment]
I think there is a problem here, the ElgarL class extends Lazy..... Hmm, I will look into this bit.

**Comment by squidicuzz** [comment]
`Water.jar not found!!` `Detergent.jar not found!!`

**Comment by ElgarL** [comment]
So if I install WashingMachine.jar, Water.jar and Detergent.jar I should be able to see  7H3LaughingMan's face in my boxers?

**Comment by gravypod** [comment]
@ElgarL, are you sure you wont see your's? What about Jan.jar?

**Comment by SpoonsJTD** [comment]
Hahaha!

public (no) class Elgarl implements FunnyGuy, Comedian
