### ISSUE TITLE
Unknown Command / Two lines Only

### ISSUE THREAD

**Issue by StealthyBatman** [keepcalm/BukkitForge#512]
So here we go. I am running BukkitForge with Direwolf20 mod pack. Everything is going fine except a few things. It seems as if /pl is an unknown command. However, I can still do plugins but I can only see two lines of text, then it goes blank. There is 16 plugins installed but it only shows like 7 and 1/2 of them. Meaning it ends like "GroupMana" instead of "GroupManager"

Not sure what's going on.

**Comment by Ionaru** [comment]
I have the same issue, also I discovered that /list has the same problem.

**Comment by SpoonsJTD** [comment]
Dupe and is fixed. (Output truncated)
