### ISSUE TITLE
[Anti-Grief] Can't find working anti grief system.

### ISSUE THREAD

**Issue by charlieTheBotDev** [keepcalm/BukkitForge#518]
I've set up a new server and the IP was leaked by my Co-Owner. Now we have 17/20 player slots full regularly and I need anti-grief measures. I haven't been able to find anything for chest protection, I tried LWC because the 'working plugins' page said it works but it just errors all the time. I've also tried logblock but that doesn't work properly either, either not saving the block history or not working when you use the tools. I have also tried GriefPrevention but that does some weird stuff with the golden shovel.

Does anyone know of any working plugins for grief protection / chest protection?

**Comment by enterprise12nx** [comment]
Use Lockette for chest protection.
As for antigrief none currently working, i think he is trying to get coreprotect working, which also works best for tekkit lite/tekkit

**Comment by eagl3s1ght** [comment]
@Chazdude42 This really isn't a specific issue, and remember- this is an issue forum, not a support forum. Go to http://www.bukkitforge.com for that...

**Comment by enterprise12nx** [comment]
mehmeh its ok, i try to be on to help people while the developers worry about the big issues,

**Comment by eagl3s1ght** [comment]
@enterprise12nx Maybe we should let the people who actually run this thing decide if it's OK for off-topic posts, and until further notice we assume that it's not, considering the amount of open issues would be quite overwhelming if everyone who needed help with Bukkitforge/their server/finding a mod posted an issue on Github?

**Comment by enterprise12nx** [comment]
Well ok..i was just saying when there are off topic issues i will be there to help since i come on to check issues and help people when the Dev's arent their to respond but fine../=

**Comment by charlieTheBotDev** [comment]
Technically it is an issue as the anti-grief stuff isn't working but I do see your point, will post on the forums in future :)

**Comment by SpoonsJTD** [comment]
What eaglesight said.
