### ISSUE TITLE
Tekkit Customizer

### ISSUE THREAD

**Issue by GrahamCampbell** [keepcalm/BukkitForge#519]
Can you please confirm this plugin is mainly functional, if not completely functional, and add it to the wiki so other people are aware that this awesome plugin can be used.
I believe https://github.com/keepcalm/BukkitForge/commit/6dab396a2a6dd26f954379c9246342c1819ed98f should have fixed this plugin completely.

**Comment by charlieTheBotDev** [comment]
I'm using it on my server, I haven't found any issues with it yet. I'm not sure if the ban reasons are showing up correctly though, either that or my players can't read very well lol.

**Comment by GrahamCampbell** [comment]
They've been working recently for me. This plugin should at least make the mostly functional list?
