### ISSUE TITLE
[ArsMagica] Staff Creation

### ISSUE THREAD

**Issue by Eb-** [keepcalm/BukkitForge#522]
When enchanting a staff with a spell in Ars Magica 5.36.040, connected to a server running BukkitForge, sometimes clients will crash. This seems to vary computer to computer. Loading up singleplayer before multiplayer on client seems to fix the issue.

This is with BukkitForge installed on the client (Accidentally, I swear!) I'm not sure if this would cause any issues with the server.

Client Crash Log:
Important stuff starts on line 1413
http://paste.ubuntu.com/1676349/

**Comment by SpoonsJTD** [comment]
Please repost log, the paste is gone already.
