### ISSUE TITLE
[EssentialsSpawn] not loading, [ShowCaseStandalone] buy action, [BetterShops] buy action, [Essentials] signs, more in description

### ISSUE THREAD

**Issue by lynxeffect86** [keepcalm/BukkitForge#524]
hi there,

first love this mod thank you very much. Second i have been doing a lot of testing and i have a few updates if you wish to use them.
minecraft -  1.4.7
forge - 6.6.0.518
Bukkitforge - 235#

Working plugins
[BOSEconomy] - not found any problems with this
[TimedMessages] - not found any problems with this
[Ontime] - not found any problems
{EssentialsGeoIP] - took 2 server restart but it works

bugged plugins
[Essentials - chat] - seems to clip parts of long messages
[Essentials - spawn] - this plugin doesnt seem to load. and setting made in the essentials config for EssentialsSpawn do not work. setting spawns is bugged to in that you can set multiple spawns and spawn locations are in a random are of you spawn location (like vanilla Minecraft) 
[ShowCaseStandalone] - it seems to load but players can no buy from showcase items. it comes up with the showcase info, but the display item works.
[BetterShop] - able to make shop signs and shop chest but when a player clicks on the sign money is taken from there account but no item is given.
[SpawnControl] & [McSpawn] - cannot override minecrafts Spawn settings of random spawning
[GriefPrevention] - set one corner for player automatically so when the click the ground with there tool it attempts to crate a protection instead of defining the first corner. most clicks with the tool on a block give multiple messages (this area is unprotected x3, you have claim this area - first corner selected.....ect). if a player manages to claim an area it is not protected.   

Plugins that dont load
[ShopKeeper]

once again thank you for this wonderful mod. is i learn of any more plugins that are not listed here i will post them for you.

**Comment by SpoonsJTD** [comment]
All dupes. Thanks for summarizing.
