### ISSUE TITLE
Spawning Issues

### ISSUE THREAD

**Issue by Dreadcor** [keepcalm/BukkitForge#530]
When players first join a server with the spawn inside of a building they get placed on the roof. Pasting what spoons claim it might be.

"<SpoonsJTD> spawn is using an old safe spawn algorithm that doesnt let you spawn in buildings."

**Comment by charlieTheBotDev** [comment]
I'm having similar issues but instead of spawning directly above the spawn point the player spawns in a random location around the spawn. Not sure if it's related but I can't seem to stop it. The same thing happens on death.

**Comment by SpoonsJTD** [comment]
Dupe.
