### ISSUE TITLE
[Plugin Channels] [Worldedit] [CUI] Plugin channels don't work

### ISSUE THREAD

**Issue by airminer** [keepcalm/BukkitForge#535]
Worldedit CUI (litemod edition, from the voxel modpack) doesn't work on bukkitforge servers. (it works on plain bukkit servers)

**Comment by dequis** [comment]
damn, i'd like to test if this really is the 'plugin channels' feature not reaching BF or whatever, but the kind of debugging i want to do requires setting up a protocol parsing proxy and i'm lazy.

does anyone know if other bukkit plugins use the plugin channels feature?

**Comment by airminer** [comment]
LogWatch uses them too. Same result: works on a bukkit server with  a forge client, but not on a bukkitforge server. Here is a version of the plugin, which works on bukkitforge (had to change a single import because of guava10): https://dl.dropbox.com/u/25782050/minecraft/logwatch-v1.1.1-SNAPSHOT.jar

**Comment by steffengy** [comment]
A workaround for this issue (gets worldedit-CUI working): http://pastebin.com/DH2kYpQW

**Comment by dequis** [comment]
Sweet. May I ask why you choose to call it 'workaround' instead of 'fix'?

**Comment by steffengy** [comment]
Because I just made it work and at one part I was too lazy to apply a proper fix. (was late in the morning already)

**Comment by alexbegt** [comment]
@steffengy Please make your pastebin easy to read so i can check it out? or push it to your own protect please?

**Comment by dequis** [comment]
Have you considered downloading it and using git apply directly?

**Comment by steffengy** [comment]
already gave him the link to the commit ( if anyone still wants to look at it: https://github.com/steffengy/BukkitForge/commit/bdbae709f7f98fc7aa9da5a16edacab2fb235754 )

**Comment by dequis** [comment]
oh okay.
