### ISSUE TITLE
Item Frame is breakable in Factions SafeZone.

### ISSUE THREAD

**Issue by TinBritches** [keepcalm/BukkitForge#538]
I am running both up to date Factions 1.8 and bukkitforge-1.4.7-244

Players are able to break item frames inside claimed safezone and they are able to pick up the frame and item.

Seems this was an issue when the Item Frame was first introduced in version 1.4 to 1.4.5.

Any advice is greatly appreciated!
Thanks!

**Comment by TinBritches** [comment]
Just realized this is a duplicate of #531, it would have helped if they had a better description in their subject.

Sorry for the duplicate.

**Comment by Dreadcor** [comment]
Updated my submission . Sorry for the lack of info in the title.

**Comment by TinBritches** [comment]
Sorry if I sounded rude, I hope we can get these issues resolved =]
