### ISSUE TITLE
[Build 250] Internal Server Error | No Plugins | MindCrack FTB Server

### ISSUE THREAD

**Issue by AlexMason** [keepcalm/BukkitForge#543]
I am running a MindCrack FTB server when I start it and login its fine... for 10 seconds... then I get a kick saying Internal Server Error.  Try to login and it no longer works, keeps booting me with Internal Server Error.

I am running no plugins, just mindcrack...

Here is crash report:
http://pastebin.com/L1vZZe27

**Comment by agaricusb** [comment]
There were some recent changes to world feature generators in Forge, maybe related to or causing this issue?

**Comment by AlexMason** [comment]
I am not sure, thats why I am asking.

**Comment by gravypod** [comment]
Doesnt look like us and I wouldn't know how to fix it, sorry

**Comment by AlexMason** [comment]
Ok, well it is bukkit forge, it only happens on my mindcrack server, not on my direwolf20 server.  It occurs during packet exchange between client and server.  When I remove bukkitforge its fine, when I add it back in it causes errors.

I gave you what information I had...

**Comment by dequis** [comment]
Try 252! 251 fixes the decorating issue

**Comment by SpoonsJTD** [comment]
Yes, sorry, this was a temporary issue between builds.
