### ISSUE TITLE
[Build 252] Internal Server Error.

### ISSUE THREAD

**Issue by Rinelw** [keepcalm/BukkitForge#545]
I flew over some land and then it crashed, here is the crash report:
http://pastebin.com/x1wZcKyT

---- Minecraft Crash Report ----
// Oops.

Time: 26.02.13 18:06
Description: Exception while updating neighbours

java.lang.RuntimeException: Already decorating!!
    at zc.a(BiomeDecorator.java:195)
    at yy.a(BiomeGenBase.java:366)
    at zf.a(SourceFile:21)
    at abb.a(ChunkProviderGenerate.java:577)
    at im.a(ChunkProviderServer.java:258)
    at zz.a(Chunk.java:1248)
    at im.c(ChunkProviderServer.java:153)
    at im.d(ChunkProviderServer.java:166)
    at yc.e(World.java:524)
    at yc.d(World.java:516)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.blockBreakSomehow(ForgeEventHandler.java:629)
    at net.minecraftforge.event.ASMEventHandler_76_ForgeEventHandler_blockBreakSomehow_BlockDestroyEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at keepcalm.mods.events.ForgeEventHelper.onBlockBreak(ForgeEventHelper.java:322)
    at amq.a(Block.java)
    at zz.a(Chunk.java:721)
    at yc.a(World.java:554)
    at yc.c(World.java:532)
    at akz.l(SourceFile:32)
    at akz.a(SourceFile:25)
    at yc.m(World.java:822)
    at yc.h(World.java:801)
    at yc.f(World.java:744)
    at yc.d(World.java:718)
    at akf.b(BlockFire.java:210)
    at in.a(WorldServer.java:567)
    at in.b(WorldServer.java:178)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:669)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at zc.a(BiomeDecorator.java:195)
    at yy.a(BiomeGenBase.java:366)
    at zf.a(SourceFile:21)
    at abb.a(ChunkProviderGenerate.java:577)
    at im.a(ChunkProviderServer.java:258)
    at zz.a(Chunk.java:1248)
    at im.c(ChunkProviderServer.java:153)
    at im.d(ChunkProviderServer.java:166)
    at yc.e(World.java:524)
    at yc.d(World.java:516)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.blockBreakSomehow(ForgeEventHandler.java:629)
    at net.minecraftforge.event.ASMEventHandler_76_ForgeEventHandler_blockBreakSomehow_BlockDestroyEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at keepcalm.mods.events.ForgeEventHelper.onBlockBreak(ForgeEventHelper.java:322)
    at amq.a(Block.java)
    at zz.a(Chunk.java:721)
    at yc.a(World.java:554)
    at yc.c(World.java:532)
    at akz.l(SourceFile:32)
    at akz.a(SourceFile:25)

-- Block being updated --
Details:
    Source block type: ID #51 (tile.fire // akf)
    Block type: ID #11 (tile.lava // akz)
    Block data value: 6 / 0x6 / 0b0110
    Block location: World: (481,18,482), Chunk: (at 1,1,2 in 30,30; contains blocks 480,0,480 to 495,255,495), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
    at yc.m(World.java:822)
    at yc.h(World.java:801)
    at yc.f(World.java:744)
    at yc.d(World.java:718)
    at akf.b(BlockFire.java:210)

-- Block being ticked --
Details:
    Block type: ID #51 (tile.fire // akf)
    Block data value: 10 / 0xA / 0b1010
    Block location: World: (479,19,481), Chunk: (at 15,1,1 in 29,30; contains blocks 464,0,480 to 479,255,495), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
    at in.a(WorldServer.java:567)
    at in.b(WorldServer.java:178)

-- Affected level --
Details:
    Level name: world
    All players: 1 total; [iq['aerd222'/8771, l='world', x=336,50, y=68,01, z=429,23]]
    Chunk stats: ServerChunkCache: 1072 Drop: 0
    Level seed: 1696245279
    Level generator: ID 02 - largeBiomes, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (46,64,-1), Chunk: (at 14,4,15 in 2,-1; contains blocks 32,0,-16 to 47,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 753515 game time, 673108 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 10515 (now: false), thunder time: 108834 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:669)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

-- System Details --
Details:
    Minecraft Version: 1.4.7
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_13, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 750799248 bytes (716 MB) / 1107820544 bytes (1056 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 2 total; -Xmx2G -Xms1G
    AABB Pool Size: 1903 (106568 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 71
    FML: MCP v7.26a FML v4.7.22.539 Minecraft Forge 6.6.0.517 63 mods loaded, 63 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TreeCapitator [TreeCapitator]([1.4.6]TreeCapitator.Forge.1.4.6.r03.Uni.CoreMod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BukkitForge [BukkitForge](BukkitForge.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BlockBreak [Block Break Event](BukkitForge.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core [BuildCraft](buildcraft-A-3.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory [BC Factory](buildcraft-A-3.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport [BC Transport](buildcraft-A-3.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon [BC Silicon](buildcraft-A-3.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    APUnofficial [Additional Pipes](AdditionalPipes-2.1.3u40-1.4.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisCore [Immibis Core](immibis-core-52.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ComputerCraft [ComputerCraft](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CCTurtle [ComputerCraft Turtles](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion [Thermal Expansion](ThermalExpansion-2.2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OmniTools [OmniTools](OmniTools-3.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2 [IndustrialCraft 2](industrialcraft-2_1.115.208-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AdvancedRepulsionSystems [Advanced Repulsion Systems](adv-repulsion-systems-52.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AdvancedMachines [IC2 Advanced Machines Addon](AdvancedMachines_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AdvancedPowerManagement [Advanced Power Management](AdvancedPowerManagement-1.1.55-IC2_1.112.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders [BC Builders](buildcraft-A-3.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy [BC Energy](buildcraft-A-3.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CompactSolars [Compact Solar Arrays](compactsolars-universal-1.4.7-3.2.3.23.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DimensionalAnchors [Dimensional Anchors](dimensional-anchor-52.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EE3 [Equivalent Exchange 3](ee3-universal-pre1f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderStorage [EnderStorage](EnderStorage 1.3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization [Factorization](Factorization-0.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2NuclearControl [Nuclear Control](IC2NuclearControl-1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest [Iron Chest](ironchest-universal-1.4.7-4.5.4.217.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LogisticsPipes|Main [Logistics Pipes](LogisticsPipes-MC1.4.7-0.7.0.81.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowerCrystalsCore [PowerCrystals Core](PowerCrystalsCore_1.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFReloaded [MineFactory Reloaded](MineFactoryReloaded_2.0.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFReloaded|CompatExtraBiomes [MFR Compat: ExtraBiomes](MineFactoryReloaded_2.0.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFReloaded|CompatForestry [MFR Compat: Forestry](MineFactoryReloaded_2.0.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFReloaded|CompatIC2 [MFR Compat: IC2](MineFactoryReloaded_2.0.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFReloaded|CompatPams [MFR Compat: Pam's Mods](MineFactoryReloaded_2.0.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerCore [RedPower](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerBase [RP Base](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerWorld [RP World](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFReloaded|CompatRP2 [MFR Compat: RP2](MineFactoryReloaded_2.0.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFReloaded|CompatSoulShards [MFR Compat: SoulShards](MineFactoryReloaded_2.0.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mmmPowersuits [MachineMuse's Modular Powersuits](ModularPowersuits-0.2.0-42.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion|Factory [Factory](ThermalExpansion-2.2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NetherOres [Nether Ores](NetherOres_2.0.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion|Energy [Energy](ThermalExpansion-2.2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowerConverters [Power Converters](PowerConverters_2.1.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerMachine [RP Machine](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerCompat [RP Compat](RedPowerCompat-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerWiring [RP Wiring](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerLogic [RP Logic](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerLighting [RP Lighting](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerControl [RP Control](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    StevesCarts [Steve's Carts](StevesCarts2.0.0.a48.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion|NEI [NEI](ThermalExpansion-2.2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion|Transport [Transport](ThermalExpansion-2.2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    snyke7_Transformers [Transformers](Transformers v1.7b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Tubestuff [Tubestuff](tubestuff-52.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    weaponmod [Balkon's WeaponMod](Weaponmod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|Core [WR-CBE Core](WR-CBE Core 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|Addons [WR-CBE Addons](WR-CBE Addons 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|RedPower [WR-CBE RedPower](WR-CBE RedPower 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BukkitForge Details: BukkitForge null-null (with bukkit API version 1.4.7-R0.1)
Plugins Loaded:WorldBorder v1.6.1: Enabled, WorldEdit v5.5.1: Enabled, WorldGuard v5.7: Enabled, Essentials v2.9.6: Enabled, EssentialsProtect v2.9.6: Enabled and EssentialsSpawn v2.9.6: Enabled
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 1015 (56840 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 5; [iq['aerd222'/8771, l='world', x=336,50, y=68,01, z=429,23]]
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)

**Comment by SpoonsJTD** [comment]
"Already decorating" issue was a temporary bug introduced in 250 and fixed in 251.
