### ISSUE TITLE
[McMyAdmin] stopped reading online players

### ISSUE THREAD

**Issue by tonnic** [keepcalm/BukkitForge#549]
I THINK this is the right place, as McMyAdmin was working fine until the plugin was installed.. now the server can't see users online, etc.

**Comment by SpoonsJTD** [comment]
Any error or warning messages of any kind?

**Comment by tonnic** [comment]
Nope...

**Comment by tonnic** [comment]
Oops

**Comment by dequis** [comment]
Man this issue is weird. I was thinking it'd be the same as the rcon one, but #mcmyadmin tells me it's always just a wrapper that writes to the console.

Does it still happen with no plugins at all? Apparently it uses /list, which isn't changed by BF, but maybe one of your plugins does..

Are there other features from mcmyadmin that get broken by adding BF?

**Comment by tonnic** [comment]
I can do a /list and it shows the players...

**Comment by tonnic** [comment]
Didn't think backups were running, but they might be... I'll check tomorrow.

**Comment by tonnic** [comment]
backups are running fine.

**Comment by tonnic** [comment]
Also opened a ticket with McMyAdmin and they found said:
"The problem is that whatever mod you're using is messing around with the console output and isn't showing _who_ is logging in. You should raise a bug with the mod authors to fix this, otherwise there's nothing MCMA can do about it."

**Comment by dequis** [comment]
Dammit, that's useless. Can you try asking this person exactly what line of the console output is needed for this feature? They didn't mention that when i asked on irc.

**Comment by tonnic** [comment]
Waiting for a response.   The original post is at https://getsatisfaction.com/mcmyadmincommunity/topics/not_showing_online_users_still_shows_0_100?utm_content=reply_link&utm_medium=email&utm_source=reply_notification#reply_11477583

**Comment by dequis** [comment]
> 2013-03-04 17:42:03 [INFO] [/xx.xxx.xxx.xx:60086] logged in with entity id 1062390 at (6215.987009115607, 165.0, 14566.850656368935) 

You pasted this. Did you remove the player name before the obscured IP address? (And after the [INFO]) If not, this is the issue. If you removed it manually due to privacy, please clarify in the other thread, since it's likely he thinks this is the issue.

**Comment by dequis** [comment]
Okay, seems like you removed the player name, but you're missing "[Minecraft]", which is visible in my ftb mindcrack test server. Which modpack from FTB are you using, and what version? Include as many details as possible to let me get the same result.

By the way it seems you have a few nonstandard mods - are you COMPLETELY sure that adding bukkitforge breaks this?

**Comment by tonnic** [comment]
i didn't change anything and the users show now......

**Comment by dequis** [comment]
lolwhat. Do the messages say [Minecraft]?

**Comment by tonnic** [comment]
...not at all

17:45:53 CONSOLE: [INFO] User USERNAMEREMOVED connecting with mods [BiblioCraft, RedPowerWiring, DynamicElevators, kirsybuuDoubleDoorMod, TwilightForest, BuildCraft|Transport, OmniTools, RedPowerCompat, Backpack, ObsidiPlates, RedPowerLogic, ThermalExpansion|Energy, Thaumcraft, drceph.petrogen, Forestry, BinnieCore, AdvancedMachines, IronChest, BuildCraft|Energy, Railcraft, GregTech_Addon, MiscPeripherals, factorization, RedPowerLighting, mod_bspkrsCore, RedPowerBase, XyCraft, Lepko-EasyCrafting, ThermalExpansion, NetherOres, BuildCraft|Silicon, ThermalExpansion|Transport, GraviSuite, BuildCraft|Core, IC2NuclearControl, ThermalExpansion|Factory, MoCreatures, IC2, ExtraBees, SlimevoidLib, ExtrabiomesXL, ComputerCraft, AdvancedSolarPanel, TreeCapitator, BuildCraft|Factory, RedPowerMachine, SoulShards, RedPowerCore, CCTurtle, ChestTransporter, RedPowerControl, BuildCraft|Builders, RedPowerWorld]

**Comment by dequis** [comment]
Well uh. I dunno. Let's just assume it was some sort of weird mistake in your part and close the ticket. I believe that if you close it, you can reopen it at any time later.

**Comment by tonnic** [comment]
lol ok... i honestly didn't change anything....
