### ISSUE TITLE
Server crashes when going to 'Mining' World

### ISSUE THREAD

**Issue by charlieTheBotDev** [keepcalm/BukkitForge#559]
I created a mining world about a week ago for my players to go to and mine in. I was fixing some craters when suddenly the server crashed saying something about ticking entity. I thought it was just a bug at first but I tried to log in again and it crashed as soon as I got online, it was only for me, other players could login without it crashing. 

I edited my player.dat file to put me back in the main world and then tried to go back to the other world and sure enough, crashes. 

here's the crash report:

http://pastebin.com/9DiN5M1s

It looks to me like one of the pipes is broken but I don't understand enough about this kind of thing to know what it all means.

**Comment by Dreadcor** [comment]
you probably used world edit in an area where there were rp/rp2 items. When you world edit them out incorrectly you corrupt the chunk. For future reference.. Do //set air first before doing anything else.

**Comment by charlieTheBotDev** [comment]
Ohh yeah, I was using worldedit...

Is there any way to fix it so I can get back there?

**Comment by Dreadcor** [comment]
if its a mining world.. just reset it? Otherwise try using MC edit.

**Comment by charlieTheBotDev** [comment]
I tried mcedit in an attempt to save everyone's items that were in the world but it didn't work, had to reset. Thanks for the help :)
