### ISSUE TITLE
Essentials logout bug

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#57]
29.12 23:31:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
29.12 23:31:32 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:601)
29.12 23:31:32 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
29.12 23:31:32 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
29.12 23:31:32 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
29.12 23:31:32 [Server] INFO at com.earth2me.essentials.EssentialsPlayerListener.onPlayerQuit(EssentialsPlayerListener.java:135)
29.12 23:31:32 [Server] INFO at com.earth2me.essentials.User.dispose(User.java:205)
29.12 23:31:32 [Server] INFO at com.earth2me.essentials.OfflinePlayer.<init>(OfflinePlayer.java:42)
29.12 23:31:32 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.getOfflinePlayer(BukkitServer.java:1182)
29.12 23:31:32 [Server] INFO Caused by: java.lang.NullPointerException
29.12 23:31:32 [Server] INFO at fy.run(SourceFile:849)
29.12 23:31:32 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
29.12 23:31:32 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
29.12 23:31:32 [Server] INFO at ho.r(DedicatedServer.java:270)
29.12 23:31:32 [Server] INFO at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
29.12 23:31:32 [Server] INFO at ht.b(SourceFile:30)
29.12 23:31:32 [Server] INFO at iw.b(NetworkListenThread.java:57)
29.12 23:31:32 [Server] INFO at iv.d(NetServerHandler.java:136)
29.12 23:31:32 [Server] INFO at cg.b(TcpConnection.java:461)
29.12 23:31:32 [Server] INFO at iv.a(NetServerHandler.java:648)
29.12 23:31:32 [Server] INFO at gm.e(ServerConfigurationManager.java:228)
29.12 23:31:32 [Server] INFO at cpw.mods.fml.common.registry.GameRegistry.onPlayerLogout(GameRegistry.java:348)
29.12 23:31:32 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.PlayerTracker.onPlayerLogout(PlayerTracker.java:43)
29.12 23:31:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
29.12 23:31:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
29.12 23:31:32 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
29.12 23:31:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
29.12 23:31:32 [Server] INFO org.bukkit.event.EventException
29.12 23:31:32 [Server] SEVERE Could not pass event PlayerQuitEvent to Essentials v${build.number}
29.12 23:31:32 [Server] INFO Location for BukkitPlayer{name=xKillerbees} is Location{world=BukkitWorld{name=world},x=-53.52023568581325,y=100.82496577119834,z=81.34967492985965,pitch=25.20005,yaw=152.39963}

**Comment by keepcalm** [comment]
Squashed that on my local code base, trying to track down this login bug. I'll push it in a sec.
