### ISSUE TITLE
Where is Keepcalm?

### ISSUE THREAD

**Issue by Ionaru** [keepcalm/BukkitForge#579]
It's been 12 days since the last version of BukkitForge (255)
Issues keep building up and nothing is getting fixed, also in the Readme file it says:

keepcalm (confirmed Dead)
keepbot (keepcalm's bot, also confirmed Dead)

I don't know if this is a joke, but I think we'd all like some explanation of what is going on with the project.

**Comment by xfloh22** [comment]
well 256 came out yesterday and i think it was pushed by keepcalm, so he is definetly alive....

**Comment by SpoonsJTD** [comment]
That was not keepcalm.

**Comment by alexbegt** [comment]
That was 3 day ago spoon lol

**Comment by SpoonsJTD** [comment]
Right, I was just telling him, that was not Keepcalm who ran the 255 build.

**Comment by Ionaru** [comment]
So... where is he?

**Comment by keepcalm** [comment]
I'm dead? Thanks for telling me ;)
I'm really busy atm. Hopefully I'll be able to continue eventually, but idk when my business will stop.
So, I'm not dead. Just FYI.

**Comment by alexbegt** [comment]
Keepcalm, I need you to do something for me.

**Comment by Iasumonecara** [comment]
Since I found an active thread, should I repost my bug from your forums to github? I found the forum first and don't want to spam reports if it won't help anything. Already got feedback from plugin dev to boot.

**Comment by alexbegt** [comment]
Iasu, come on irc.esper.net #bukkitforge We can help you there to.
