### ISSUE TITLE
Towny Not Registering

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#58]
I know you keep trying to fix this, but with the newest build, it still isn't registering people so you can't use it. 

Everything on towny is out of box. Using the newest of Towny and BukkitForge. (build 16)

Will mention that voxelsniper now spits something in chat when I login when it didn't before. The normal login info.

**Comment by keepcalm** [comment]
yes, I am aware of this. Not sure why it's not working, I am going to inspect towny's code to see where it registers people. Might be pushing the wrong events so it doesn't register.

**Comment by xKillerbees** [comment]
Only thing I'm aware of is that it creates the player file when it does. So might be able to look for that bit to see how it pulls that.

**Comment by keepcalm** [comment]
No, it has to do with my (shameful) scheduler. I need to fix it, and then towny will work!

**Comment by xKillerbees** [comment]
Alright, looking forward to the commit so I can test more. Thanks

**Comment by xKillerbees** [comment]
Darn, can't test the fix, jenkins is down.

**Comment by keepcalm** [comment]
Heh, try looking in dist :P

**Comment by xKillerbees** [comment]
Registers now, thank you. Also fixed the motd/welcome message.
