### ISSUE TITLE
[TekkitCustomizer] Works, but no reason given when item taken (because its banned)

### ISSUE THREAD

**Issue by enterprise12nx** [keepcalm/BukkitForge#580]
So for those who know Tekkit Customizer, say you ban an item, if some1 trys to for example place it, the plugin would take it and give the reason you wrote down.

This doesnt work for me (no errors)

Crystal Chest (my coding)
- 181:5:Makes Lag
  (it takes the block but says it has no reason)
  Nuke (my coding)
- 237:*Massive world destruction
  (Same thing, even with asterik which bans whole ID value)

I posted this on the plugin authors curse page
i have a feeling maybe its bukkitforge but am checking with both, ty for your time!

AND WHERES KEEPCALM!

**Comment by Ionaru** [comment]
You got the format wrong, it should be:

ID:Sub-ID:Name:Reason

The name does not have to match the item, it's just a reference for yourself.

Example:
5:2:Type of wood:I hate wood
