### ISSUE TITLE
Will You Update To 1.5?

### ISSUE THREAD

**Issue by NevaehsRealm** [keepcalm/BukkitForge#589]
I know it's likely you'll be updating, I just wanted to know for sure.

PLEASE let me know.

Also it would be great to know about how long it'll be. Thanks :)

**Comment by alexbegt** [comment]
Please, Have you been on the irc?

**Comment by NevaehsRealm** [comment]
I'm sorry, no. I don't know how to use IRC.  can you just let me know here?

**Comment by alexbegt** [comment]
You'll see a branch 1.5 its being worked on by me.

**Comment by alexbegt** [comment]
http://jenkins.bukkitforge.com:8080/job/BukkitForge-1.5/ Our jenkins

**Comment by NevaehsRealm** [comment]
Do you any ETA?

**Comment by alexbegt** [comment]
Builds work but commands dont, and its kinda messed up likes what kind of eta you want

**Comment by NevaehsRealm** [comment]
As in commands don't work, commands for plug-ins won't work?

**Comment by alexbegt** [comment]
./gamemode does not work correct

**Comment by NevaehsRealm** [comment]
OK, will listeners on votifier work? Have they worked in past versions? Because I'm having trouble getting votifier to work..

**Comment by alexbegt** [comment]
What's up with them

**Comment by alexbegt** [comment]
Check http://jenkins.bukkitforge.com:8080/job/BukkitForge-1.5.1/

**Comment by alexbegt** [comment]
Use technic's jenkins!
