### ISSUE TITLE
Essentials SpawnPlayerListener

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#59]
Using the build from the git. 

30.12 01:40:41 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.block.BukkitBlock.<clinit>(BukkitBlock.java:465)
30.12 01:40:41 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 23
30.12 01:40:41 [Server] INFO at fy.run(SourceFile:849)
30.12 01:40:41 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
30.12 01:40:41 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:587)
30.12 01:40:41 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
30.12 01:40:41 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
30.12 01:40:41 [Server] INFO at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
30.12 01:40:41 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:23)
30.12 01:40:41 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VScheduler.mainThreadHeartbeat(B4VScheduler.java:345)
30.12 01:40:41 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
30.12 01:40:41 [Server] INFO at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$NewPlayerTeleport.run(EssentialsSpawnPlayerListener.java:153)
30.12 01:40:41 [Server] INFO at com.earth2me.essentials.Teleport.now(Teleport.java:218)
30.12 01:40:41 [Server] INFO at com.earth2me.essentials.Teleport.now(Teleport.java:234)
30.12 01:40:41 [Server] INFO at com.earth2me.essentials.Util.getSafeDestination(Util.java:350)
30.12 01:40:41 [Server] INFO at com.earth2me.essentials.Util.isBlockAboveAir(Util.java:404)
30.12 01:40:41 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.getBlockAt(BukkitWorld.java:209)
30.12 01:40:41 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.getBlock(BukkitChunk.java:96)
30.12 01:40:41 [Server] INFO java.lang.ExceptionInInitializerError
30.12 01:40:41 [Server] WARNING [com.earth2me.essentials.Essentials] [Essentials] Task #20 for Essentials v${build.number} generated an exception
30.12 01:40:41 [Server] INFO Adding biome mapping 32 Alpine at BiomeGenBase[32]

30.12 01:44:15 [Server] INFO at fy.run(SourceFile:849)
30.12 01:44:15 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
30.12 01:44:15 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:587)
30.12 01:44:15 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
30.12 01:44:15 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
30.12 01:44:15 [Server] INFO at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
30.12 01:44:15 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:23)
30.12 01:44:15 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VScheduler.mainThreadHeartbeat(B4VScheduler.java:345)
30.12 01:44:15 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
30.12 01:44:15 [Server] INFO at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$NewPlayerTeleport.run(EssentialsSpawnPlayerListener.java:153)
30.12 01:44:15 [Server] INFO at com.earth2me.essentials.Teleport.now(Teleport.java:218)
30.12 01:44:15 [Server] INFO at com.earth2me.essentials.Teleport.now(Teleport.java:234)
30.12 01:44:15 [Server] INFO at com.earth2me.essentials.Util.getSafeDestination(Util.java:350)
30.12 01:44:15 [Server] INFO at com.earth2me.essentials.Util.isBlockAboveAir(Util.java:404)
30.12 01:44:15 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.getBlockAt(BukkitWorld.java:209)
30.12 01:44:15 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.getBlock(BukkitChunk.java:96)
30.12 01:44:15 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class keepcalm.mods.bukkit.bukkitAPI.block.BukkitBlock
30.12 01:44:15 [Server] WARNING [com.earth2me.essentials.Essentials] [Essentials] Task #27 for Essentials v${build.number} generated an exception

**Comment by keepcalm** [comment]
derp. think i found it. Hold on, i'll build and then push.
