### ISSUE TITLE
Crash at server startup

### ISSUE THREAD

**Issue by unforgiven91** [keepcalm/BukkitForge#590]
http://pastebin.com/NsMr43TU

running a standard tekkit lite server. 0 plugins. Just trying to get bukkitforge to work. It is in coremods folder, as instructed.

**Comment by WhiplashD** [comment]
Yeah I got the same exact error with builds 255 256 and 257, I just gave up and went back to 252.

**Comment by Ionaru** [comment]
_Sigh_, Tekkitlite has the mod: TreeCapitator, it does NOT work with any BukkitForge version higher then 252. Either delete the mod, or downgrade BukkitForge.

**Comment by unforgiven91** [comment]
thanks for the info.
