### ISSUE TITLE
Feed The Beast Ultimate - Server Crash on start

### ISSUE THREAD

**Issue by Nohau** [keepcalm/BukkitForge#598]
Not utilizing any other plugins currently and using default Ultimate mods / core mods

---- Minecraft Crash Report ----
// Sorry :(

Time: 3/31/13 9:56 AM
Description: Exception in server tick loop

java.lang.NullPointerException
        at keepcalm.mods.bukkit.nmsforge.DimensionManagerImpl.initDimension(DimensionManagerImpl.java:190)
        at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:68)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:758)
        at codechicken.chunkloader.ChunkLoaderManager.getWorld(ChunkLoaderManager.java:537)
        at codechicken.chunkloader.ChunkLoaderManager$ChunkLoaderOrganiser.revive(ChunkLoaderManager.java:334)
        at codechicken.chunkloader.ChunkLoaderManager.revivePlayerLoaders(ChunkLoaderManager.java:902)
        at codechicken.chunkloader.ChunkLoaderManager.tickEnd(ChunkLoaderManager.java:856)
        at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd(ChunkLoaderEventHandler.java:39)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:139)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:283)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:689)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
        Minecraft Version: 1.4.7
        Operating System: Linux (amd64) version 3.2.0-38-generic
        Java Version: 1.7.0_15, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 106355808 bytes (101 MB) / 266620928 bytes (254 MB) up to 3195076608 bytes (3047 MB)
        JVM Flags: 8 total; -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=3 -XX:+AggressiveOpts -XX:UseSSE=4 -Xincgc -Xmx3072M
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        Suspicious classes: FML and Forge are installed
        IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
        FML: MCP v7.26a FML v4.7.35.556 Minecraft Forge 6.6.2.534 88 mods loaded, 88 mods active
        mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MiscPeripheralsASM [MiscPeripherals ASM](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        PowerCrystalsCore [PowerCrystals Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BukkitForge [BukkitForge](BukkitForge-1.4.7-252.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BlockBreak [Block Break Event](BukkitForge-1.4.7-252.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        CoFHCore [CoFH Core](CoFHCore.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Core [BuildCraft](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ComputerCraft [ComputerCraft](computercraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        CCTurtle [ComputerCraft Turtles](computercraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ThermalExpansion [Thermal Expansion](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        OmniTools [OmniTools](omnitools.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        IC2 [IndustrialCraft 2](IC2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        TwilightForest [The Twilight Forest](TwilightForest.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Builders [BC Builders](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Energy [BC Energy](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Factory [BC Factory](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Transport [BC Transport](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Silicon [BC Silicon](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        factorization [Factorization](factorization.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ExtrabiomesXL [ExtrabiomesXL](extrabiomes.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Forestry [Forestry for Minecraft](forestry.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Railcraft [Railcraft](railcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        RedPowerCore [RedPower](redpowercore.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        RedPowerBase [RP Base](redpowercore.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        RedPowerMachine [RP Machine](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        RedPowerCompat [RP Compat](redpowercompat.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        RedPowerWiring [RP Wiring](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        RedPowerLogic [RP Logic](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        RedPowerLighting [RP Lighting](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        RedPowerWorld [RP World](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        RedPowerControl [RP Control](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ThermalExpansion|Factory [Factory](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ThermalExpansion|Energy [Energy](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ThermalExpansion|Transport [Transport](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ImmibisCore [Immibis Core](immibiscore.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Tubestuff [Tubestuff](tubestuff.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        XyCraft [Â§3XyCraft](xycraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        GregTech_Addon [GregTech-Addon](GregTech.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MiscPeripherals [MiscPeripherals](MiscPeripherals.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        AppliedEnergistics [Applied Energistics](AppliedEnergistics.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BiblioCraft [BiblioCraft](BiblioCraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ChargePads [Charge Pads](ChargePads.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ChickenChunks [ChickenChunks](ChickenChunks.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        EnderStorage [EnderStorage](EnderStorage.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        FlatBedrock [FlatBedrock](FlatBedrock.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        GraviGun [GraviGun](GraviGun.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        IC2NuclearControl [Nuclear Control](IC2NuclearControl.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        IronChest [Iron Chest](IronChest.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MFReloaded [Minefactory Reloaded](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MFReloaded|CompatExtraBiomes [MFR Compat: ExtraBiomes](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MFReloaded|CompatForestry [MFR Compat: Forestry](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MFReloaded|CompatIC2 [MFR Compat: IC2](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MFReloaded|CompatPams [MFR Compat: Pam's Mods](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MFReloaded|CompatRP2 [MFR Compat: RP2](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        SoulShards [SoulShards](soulshards.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MFReloaded|CompatSoulShards [MFR Compat: Soul Shards](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MFReloaded|CompatSufficientBiomes [MFR Compat: Sufficient Biomes](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Thaumcraft [Thaumcraft](Thaumcraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MFReloaded|CompatThaumcraft [MFR Compat: Thaumcraft](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MFReloaded|CompatTwilightForest [MFR Compat: TwilightForest](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        XyCraftWorld [Â§2XyCraft World](xycraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MFReloaded|CompatXycraft [MFR Compat: Xycraft](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        mmmPowersuits [MachineMuse's Modular Powersuits](ModularPowersuits.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        NetherOres [Nether Ores](NetherOres.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        PortalGun [Portal Gun](PortalGun.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        PowerConverters [Power Converters](PowerConverters.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        StevesCarts [Steve's Carts](StevesCarts.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BinnieCore [Binnie Core](extrabees.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ExtraBees [Extra Bees](extrabees.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ThaumicBees [ThaumicBees](ThaumicBees.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        XReliquary [Xeno's Reliquary](XReliquary.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        AdvancedMachines [IC2 Advanced Machines Addon](advancedmachines.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        AdvancedSolarPanel [Advanced Solar Panels](advancedsolarpanel.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        EE3 [Equivalent Exchange 3](ee3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        GraviSuite [Gravitation Suite](gravisuite.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ModularForceFieldSystem [Modular ForceField System V2](modularforcefieldsystem.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Mystcraft [Mystcraft](mystcraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ObsidiPlates [Obsidian Pressure Plates](obsidiplates.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        drceph.petrogen [Petroleum Generator](petrogen.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        SecretRoomsMod [The SecretRoomsMod](secretroomsmod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        WR-CBE|Core [WR-CBE Core](wirelessredstonecore.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        WR-CBE|Addons [WR-CBE Addons](wirelessredstoneaddons.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        WR-CBE|RedPower [WR-CBE RedPower](wirelessredstoneredpower.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        XyCraftMachines [Â§9XyCraft Machines](xycraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BukkitForge Details: BukkitForge null-null (with bukkit API version 1.4.7-R0.1)
Plugins Loaded:[No plugins loaded]
        Profiler Position: N/A (disabled)
        Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        Player Count: 0 / 40; []
        Is Modded: Definitely; Server brand changed to 'forge,fml'
        Type: Dedicated Server (map_server.txt)

**Comment by HypnoTherapist** [comment]
I had a similar problem. Try generating a new map. If that fixes it, you
probably have a bugged dimension. My issue was with twilight forest.

**Comment by alexbegt** [comment]
Yes Generate the world.
