### ISSUE TITLE
[1.5.1] Plugins like ChestShop and Essentials can't recognize items from mods.

### ISSUE THREAD

**Issue by krisukun** [keepcalm/BukkitForge#607]
In build 9 of BukkitForge [1.5.1] plugins can recognize items from mods greatly, but in builds above 9 (I have tested builds 22-25), plugins like Essentials and Chestshop seems to not recognize items from mods, tested with commands like: /iteminfo , /item , /give etc, and also tried to buy modded item from chestshop - no luck.

I really don't sure, where the issue is. Builds 13-21 can't load mod "Pixelmon", builds 22-25 works with pixelmon, but there are this issue.

/edit I rollbacked manually changes introduced in build 17 (IC2 fix, just copied this classes from build 9 to build 25) and everything works great, but would be great, if someone fix it officially :)

**Comment by alexbegt** [comment]
I have seen this

**Comment by krisukun** [comment]
It's working now, thanks for the quick fix :)
