### ISSUE TITLE
Everybody counts as a new player

### ISSUE THREAD

**Issue by SpiritedDusty** [keepcalm/BukkitForge#61]
On Essentials when spawning, it always says Welcome to the server and spawns you at the spawn point instead of where you left off before you disconnected. I'm using the Essentails plugin from the dist folder on github.

BukkitForge: BukkitForge-1.4.6-jenkins_is_down.jar

EDIT: Also after logging in once, the motd doesn't show up anymore. Only on first join after the server starts it shows up.

**Comment by keepcalm** [comment]
Temporary fix to the first one - remove EssentialsSpwan.jar. Do you mean that the MOTD only shows up on the first login, and then doesn't show up for anyone else?

**Comment by SpiritedDusty** [comment]
I mean like after starting the server, if a player logs in he sees the MOTD. But after logging off and logging back in, the MOTD doesn't apear.

**Comment by keepcalm** [comment]
Ok. weird.

**Comment by Manawyrm** [comment]
Issue was solved with 5e5b06c6676d7cc92a0aa7da826219187ecb8c8a
