### ISSUE TITLE
ForgeError    1.4.7-257    TekkitLite 0.6.1

### ISSUE THREAD

**Issue by SBlack08** [keepcalm/BukkitForge#612]
oh o.O Sorry

http://pastebin.com/p3aUq9x4

more was not in the console inside...
## Coremods

[1.4.6]TreeCapitator.Forge.1.4.6.r07.Uni.CoreMod
BukkitForge-1.4.7-257
CodeChickenCore 0.7.3
NotEnoughItems 1.4.7.0
PowerCrystalsCore-1.0.3-34
## mods

[1.4.7]bspkrsCorev1.01
AdditionalPipes2.1.3u42-BC3.4.2-MC1.4.7
AdvancedMachines_1.4.6
AdvancedPowerManagement-1.1.55-IC2_1.112
Advanced-Solar-Panels-Addon-1.4.7
buildcraft-A-3.4.3
CoFHCore-1.4.7.3
ComputerCraft1.5
EnderStorage 1.4.1.2
ExtrabiomesXL-universal-1.4.7-3.11.0
FlatBedrock_1.0.3
forestry-A-2.0.0.11
IC2NuclearControl-1.4.6
industrialcraft-2_1.115.231-lf
ironchest-universal-1.4.7-5.1.0.260
LogisticsPipes-MC1.4.7-0.7.0.90
MineFactoryReloaded-2.3.2-287
ModularPowersuits-0.3.2-199
NetherOres-2.0.6-32
OmniTools-3.0.4
PowerConverters-2.2.2-29
Railcraft_1.4.7-6.17.0.0
RedPowerCompat-2.0pr6
RedPowerCore-2.0pr6
RedPowerDigital-2.0pr6
RedPowerMechanical-2.0pr6
ThermalExpansion-2.2.2.2
Transformers v1.7b
WR-CBE Addons 1.3.2.8
WR-CBE Core 1.3.2.8
WR-CBE RedPower 1.3.2.8

**Comment by steffengy** [comment]
you know that this log is first not complete and secondly fine?

**Comment by alexbegt** [comment]
PASTEBIN OR NO HELP

**Comment by SBlack08** [comment]
and can someone help me?

**Comment by Ionaru** [comment]
[1.4.6]TreeCapitator.Forge.1.4.6.r07.Uni.CoreMod

Your problem right there, delete it.

**Comment by SBlack08** [comment]
Many many thanks! it works :D

do you know why I can not play a single player map?
