### ISSUE TITLE
Support for 1.4.7?

### ISSUE THREAD

**Issue by Ionaru** [keepcalm/BukkitForge#614]
Now BukkitForge has been updated to 1.5.1 I can imagine lots of people are happy and stuff.
But there's a problem.

Most modpacks and tech mods are not yet updated to 1.5.1 so we are now stuck at build 257. Will there be new versions for 1.4.7 or is this it.?

**Comment by alexbegt** [comment]
Well I did the 1..5.1 of it so idk if i may update 1.4.7

**Comment by ghost** [comment]
I too would like to see this. Current FTB Lite server runs on 1.4.7, and there's unfortunately a lot of bugs still. :3

**Comment by Dessix** [comment]
I would definitely love to see an update for 1.4.7, as my server is version-locked onto it by the Mindcrack modpack for FTB.

**Comment by Fundaris** [comment]
See https://github.com/keepcalm/BukkitForge/tree/1.4.7

**Comment by alexbegt** [comment]
Fixed
