### ISSUE TITLE
Exception in server tick loop, Server crashes with 1.5.1-267

### ISSUE THREAD

**Issue by TinBritches** [keepcalm/BukkitForge#615]
When I run my server with 1.5.1-259 I can get it to run just fine, but if I use the most up to date version, I get these crashes:

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 4/11/13 1:49 PM
Description: Exception in server tick loop

java.lang.NullPointerException
    at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:299)
    at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:207)
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:107)
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:237)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.5.1
    Operating System: Linux (amd64) version 3.2.0-29-generic
    Java Version: 1.7.0_13, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 33357256 bytes (31 MB) / 386596864 bytes (368 MB) up to 1886519296 bytes (1799 MB)
    JVM Flags: 2 total; -Xmx2024M -Xmx2024M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.44 FML v5.1.16.639 Minecraft Forge 7.7.1.639 6 mods loaded, 6 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BukkitForge [BukkitForge](BukkitForge-1.5.1-267.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BlockBreak [Block Break Event](BukkitForge-1.5.1-267.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Pixelmon [Pixelmon](Pixelmon 2.1.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BukkitForge Details: BukkitForge 1.5.1.267 (with bukkit API version 1.4.7-R0.1)
Plugins Loaded:[Didn't get far enough to load plugins :/]
    Profiler Position: N/A (disabled)
    Player Count: 0 / 30; []
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Fundaris** [comment]
Is fixed in last build :)

**Comment by TinBritches** [comment]
Thanks! =D

**Comment by alexbegt** [comment]
lol Stop reopening and then closing your spaming my email xD

**Comment by TinBritches** [comment]
Sorry, I accidentally clicked reopen instead of comment. I won't do it again I promise! =D

**Comment by alexbegt** [comment]
u better not or no help for u!
