### ISSUE TITLE
[Chat] issue due to an uppercase letter.

### ISSUE THREAD

**Issue by Wolftein** [keepcalm/BukkitForge#65]
When a player is called for example "Wolftein" the chat display {permsuffix} Wolftein {permsuffx}, but if i login with a player called "wolftein" the chat works fine.

**Comment by keepcalm** [comment]
Ok. What plugins are you using? (I'm trying to track down the misbehaving plugin, it's either Towny or Essentials).

**Comment by Wolftein** [comment]
TownyChat :D

**Comment by keepcalm** [comment]
Ah! So i have to look at its code.

**Comment by SpoonsJTD** [comment]
Uppercase/lowercase player name issues should be fixed in latest builds.
