### ISSUE TITLE
Issues w/ getting Items and changing player stats.

### ISSUE THREAD

**Issue by kzh** [keepcalm/BukkitForge#660]
Essentials' /fly does not work at all.
Essentials' /feed spurts out an error but works.
"Error: net.minecraft.util.FoodStats.75119.b(F)V
Whenever I try to spawn an item with a command this error happens:
java.lang.NoSuchMethodError
net.minecraft.inventory.Inventory,getContents()[net/minecraft/item/ItemStack;

If this is a bukkit port, things should be made compatible. 

Also I'm running the Aetheric Crusades ModPack.
Mods:
Aehter II
Aether II(core)
BackPackMod
BetterFurnaces
BiblioCraft
Chisel
CustomMenu
DamageIndicatorsMod
Gravestones
Grimoire
Herbology
InventoryTweaks
Mystcraft
PlayerAPI
ReisMiniMap
VendingBlock

**Comment by alexbegt** [comment]
Class patching problem

**Comment by kzh** [comment]
How can I fix this?

**Comment by master801** [comment]
@furryfaust You don't, BukkitForge is dead.
