### ISSUE TITLE
BukkitForge 301 Not Loading

### ISSUE THREAD

**Issue by Shores2510** [keepcalm/BukkitForge#666]
I get a message that says "SEVERE Something real bad happened. CraftAPI will not run this Minecraft session." I use BukkitForge 301 and Minecraft 1.5.2 for Hexxit 1.0.5

Here's the crash report:

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 8/8/13 11:41 PM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: field_77791_bV
    at iDiamondhunter.bows.bowEnder.func_77615_a(bowEnder.java:163)
    at net.minecraft.item.ItemStack.func_77974_b(ItemStack.java:521)
    at net.minecraft.entity.player.EntityPlayer.func_71034_by(EntityPlayer.java:252)
    at net.minecraft.network.NetServerHandler.func_72510_a(NetServerHandler.java:441)
    at net.minecraft.network.packet.Packet14BlockDig.func_73279_a(SourceFile:46)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:461)
    at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:134)
    at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:53)
    at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:677)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:275)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:573)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:470)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.5.2
    Operating System: Linux (amd64) version 2.6.18-308.13.1.el5
    Java Version: 1.7.0_21, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 212968240 bytes (203 MB) / 798973952 bytes (761 MB) up to 1556938752 bytes (1484 MB)
    JVM Flags: 10 total; -Xincgc -Xmx1536M -XX:MaxPermSize=128M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+DisableExplicitGC -XX:ErrorFile=/dev/null -XX:UseSSE=3
    AABB Pool Size: 2593 (145208 bytes; 0 MB) allocated, 2402 (134512 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    FML: MCP v7.51 FML v5.2.23.737 Minecraft Forge 7.8.1.737 62 mods loaded, 62 mods active
    mcp{7.51} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{5.2.23.737} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{7.8.1.737} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHFramework{1.5.2.5} [CoFH Framework](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.8.7.3} [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.5.2.28} [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisMicroblocks{55.0.7} [Immibis's Microblocks](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_bspkrsCore{v2.09(1.5.2)} [bspkrsCore]([1.5.2]bspkrsCorev2.09.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BukkitForge{Unknown} [BukkitForge](BukkitForge-1.5.2-301.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BlockBreak{1.4.6-0} [Block Break Event](BukkitForge-1.5.2-301.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.5.2.5} [CoFHCore](CoFHCore-1.5.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHWorld{1.5.2.5} [CoFHWorld](CoFHCore-1.5.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TreeCapitator{Forge 1.5.2.r14} [TreeCapitator]([1.5.2]TreeCapitator.Forge.1.5.2.r14.Uni.CoreMod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisMicroblocksInstallCheck{55.0.7} [Immibis's Microblocks (Checks for incorrect installation, ignore this)](immibis-microblocks-55.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DamageIndicatorsMod{2.7.0.1} [Damage Indicators](1.5.2 DamageIndicators v2.7.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AsgardShield_Core{2.0.4} [AsgardShield](1.5.2AsgardShield_Core_2.0.4Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ASAddon_Hallowed{2.0.0} [AS Addon- Hallowed](1.5.2ASAddonHallowed_v2.0.0Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HarkenScythe_Core{2.1.6} [HarkenScythe](1.5.2HarkenScythe_v2.1.6Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ASAddon_HarkenScythe{2.0.0} [AS Addon- HarkenScythe](1.5.2ASAddonHarkenScythe_v2.0.0Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ASAddon_NetherEnder{2.0.0} [AS Addon- Nether-Ender](1.5.2ASAddonNetherEnder_v2.0.0Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ASAddon_ColorAPI{1.0.0} [ASAddon_ColorAPI](1.5.2AsgardShield_Core_2.0.4Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Artifice{1.5.2R1.1.2} [Artifice](Artifice-1.1.2-142.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArtificeCompat|Chisel{1.5.2R1.1.2} [Artifice Compat: Chisel](Artifice-1.1.2-142.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArtificeCompat|EE3{1.5.2R1.1.2} [Artifice Compat: EE3](Artifice-1.1.2-142.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArtificeCompat|Forestry{1.5.2R1.1.2} [Artifice Compat: Forestry](Artifice-1.1.2-142.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArtificeCompat|MFR{1.5.2R1.1.2} [Artifice Compat: MFR](Artifice-1.1.2-142.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArtificeCompat|Railcraft{1.5.2R1.1.2} [Artifice Compat: Railcraft](Artifice-1.1.2-142.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArtificeCompat|Vanilla{1.5.2R1.1.2} [Artifice Compat: Vanilla](Artifice-1.1.2-142.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BattleTowers{1.3.4} [Battle Towers](BattleTowers_1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BetterDungeons{1.8} [Better dungeons](BetterDungeons.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.3.3} [BiblioCraft](BiblioCraft[v1.3.3].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DimDoors{1.5.2R1.4.1RC1} [Dimensional Doors](DimensionalDoors-1.5.2R1.4.1RC1-194.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    eplus{1.15.4} [Enchanting Plus](EnchantingPlus-1.15.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtrabiomesXL{3.13.4} [ExtrabiomesXL](ExtrabiomesXL-universal-1.5.2-3.13.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    hexxitgear{1.5.2R1.0} [Hexxit Gear](HexxitGear-1.0-23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    InfernalMobs{1.3.1} [Infernal Mobs](InfernalMobs_1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Meteors{2.10.2} [Falling Meteors](Meteors Mod V2.10.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    More Bows{1.5_v1} [More Bows mod](More bows 1.5.2_2 Forge.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LegendGear{1.5.2} [LegendGear](NMcCoy-LegendGear-1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura{2.1.2} [Natura](Natura_2.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura|CompatMineFactoryReloaded{0.1} [Natura compat: MFR](Natura_2.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OffLawn{1.0} [offLawn](OffLawn-1.5.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjectZulu|Core{1.0.3.8} [Project Zulu Core](ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjectZulu|Blocks{1.0.3.8} [Project Zulu Block and Items](ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjectZulu|Dungeon{1.0.3.8} [Project Zulu Mobs](ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjectZulu|Mobs{1.0.3.8} [Project Zulu Mobs](ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjectZulu|World{1.0.3.8} [Project Zulu World](ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    xreliquary{1.5.2} [Xeno's Reliquary](Reliquary1.0.6d.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    rftl{1.0} [RottenFleshToLeather](RottenFleshToLeather-1.5.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_Ruins{10.3} [Ruins Spawning System](Ruins_1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    secretroomsmod{4.6.0} [SecretRoomsMod](SecretRoomsMod-universal-4.6.0.283.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SoulShards{1.0.16} [Soul Shards](SoulShards-1.0.36-universal-srg.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.5.1_1.4.0} [Tinkers' Construct](TConstruct_1.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct|CompatMineFactoryReloaded{0.1} [TConstruct Compat: MFR](TConstruct_1.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WildCaves3{0.4.2} [Wild Caves 3](WildCaves3-0.4.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BetterStorage{0.6.2.23} [BetterStorage]([1.5.2]BetterStorage_0.6.2.23.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Backpack{1.12.13} [Backpack](backpack-1.12.13-1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ChestTransporter{1.1.6} [Chest Transporter](chestTransporter_1.1.6_Universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisCore{55.1.6} [Immibis Core](immibis-core-55.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ObsidiPlates{1.5.0} [Obsidian Pressure Plates](obsidiplates-1.5.2-universal-1.5.0.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{1.18.1} [The Twilight Forest](twilightforest-1.18.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chococraft{2.8.8} [Torojima's ChocoCraft](zzzChococraft_2.8.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BukkitForge Details: BukkitForge null-null (with bukkit API version 1.4.7-R0.1)
Plugins Loaded:GroupManager v2.0 (2.11.1) (Phoenix): Enabled, Vault v1.2.25-b333: Enabled, WorldEdit v5.5.7: Enabled, WorldGuard v5.8: Enabled, Essentials v2.11.1: Enabled, EssentialsChat v2.11.1: Enabled, EssentialsProtect v2.11.1: Enabled, EssentialsSpawn v2.11.1: Enabled and Factions v1.8.2: Enabled
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 912 (51072 bytes; 0 MB) allocated, 778 (43568 bytes; 0 MB) used
    Player Count: 2 / 40; [EntityPlayerMP['Shores2510'/239622, l='world', x=-19.70, y=78.12, z=-1371.36], EntityPlayerMP['wno112'/8782, l='world', x=-7.75, y=70.22, z=-1371.79]]
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by alexbegt** [comment]
Why not try mcpc+?

**Comment by Shores2510** [comment]
I'll try. Thanks!

EDIT: Yep! It works. Thanks man!
