### ISSUE TITLE
Logblock Loading

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#67]
30.12 23:12:42 [Server] INFO [de.diddiz.LogBlock.LogBlock] [LogBlock] Disabling LogBlock v1.61
30.12 23:12:42 [Server] INFO [de.diddiz.LogBlock.LogBlock] [LogBlock] Enabling LogBlock v1.61

30.12 23:12:42 [Server] SEVERE [de.diddiz.LogBlock.LogBlock] [LogBlock] Error while loading: com.mysql.jdbc.Driver
30.12 23:12:42 [Server] INFO [de.diddiz.LogBlock.LogBlock] [LogBlock] Connecting to root@jdbc:mysql://localhost:3306/ir_server1...
30.12 23:12:42 [Server] INFO [de.diddiz.LogBlock.LogBlock] [LogBlock] Loading LogBlock v1.61

Build 21

**Comment by minecrafter** [comment]
Try installing the MySQL connector for Java in lib/ and try again.

**Comment by xKillerbees** [comment]
Happen to have a link to that?

**Comment by keepcalm** [comment]
That won't help, the only reason it loads those files is because I tell it to. I'll fix it very shortly.

**Comment by Erycus** [comment]
You sir, are god for creating this project.

Thank you for starting(/kindacontinuing) this and working on it for as long as you have already.
Here's wishing you success.

Cheers.

**Comment by keepcalm** [comment]
thanks!
