### ISSUE TITLE
[Citizens] Not Loading

### ISSUE THREAD

**Issue by jmgilman** [keepcalm/BukkitForge#68]
Attempting to load the latest version of Citizens. Get the following error:

[SEVERE] [BukkitForge] [Citizens] v2.0.6-SNAPSHOT (build 645) is not compatible with Minecraft vgit-BukkitForge-1.4.5-R1.0-b3000jnks (Really: BukkitForge for MC 1.4.6). Disabling.

Not sure exactly what the issue is. How is it not compatible?

**Comment by minecrafter** [comment]
Likely due to it's dependency on NMS classes

**Comment by keepcalm** [comment]
No, it's because of these stupid version checks. If there's an option to disable version checks, that will work.

**Comment by minecrafter** [comment]
If the version checks were bypassed, we have OBC and NMS classes to deal with still. For example, [this](https://github.com/CitizensDev/Citizens2/blob/master/src/main/java/net/citizensnpcs/npc/entity/BatController.java) and [this](https://github.com/CitizensDev/Citizens2/blob/master/src/main/java/net/citizensnpcs/npc/entity/HumanController.java).

**Comment by jmgilman** [comment]
So not much hope then?

**Comment by minecrafter** [comment]
Basically unless "fake" OBC and NMS classes are implemented by keepcalm, which does not seem likely.

**Comment by keepcalm** [comment]
The OBC part wouldn't be too hard - I basically copy-pasted craftbukkit code, so if I (or someone else) just created Craftxxx classes which extend their Bukkitxxx counterparts, it should mostly work... As for NMS, I might look into that.

**Comment by minecrafter** [comment]
NMS will be a difficult stalk to climb here, the best way to do it would be to implement a custom ClassLoader and determine if we're in a Forge/minecraft_server environment or a Bukkit environment and deal with it as necessary, and rewrite Bukkit requests for net.minecraft.server.\* to e.g. keepcalm.mods.bukkitforge.fakeMinecraftServer and forward things to Forge/minecraft_server as needed.

We also have to deal with plugins who are peeping Toms with regards to NBT files, which are plenty abound.

**Comment by keepcalm** [comment]
Yes, that will be fun. I have forked mc-dev and I'm messing around with it as a side project to make it into yet another API for forge. I had considered writing a custom classloader, and I'll probably get started now...

**Comment by jmgilman** [comment]
Well I couldn't find anyway to disable the version checks.

**Comment by keepcalm** [comment]
Ok. Well I'll add a config option to let you set the CraftBukkit build number.

**Comment by mindcloud69** [comment]
Keepcalm 

It looks like Citizens is looking specifically for the version number at the beginning of Util.getMinecraftVersion();

See the version checking code snippet below from the Citizens Github page.

```
    private static final String COMPATIBLE_MC_VERSION = "1.4.5";

    String mcVersion = Util.getMinecraftVersion();
    compatible = mcVersion.startsWith(COMPATIBLE_MC_VERSION);
    if (!compatible) {
        Messaging.severeTr(Messages.CITIZENS_INCOMPATIBLE, getDescription().getVersion(), mcVersion);
        getServer().getPluginManager().disablePlugin(this);
        return;
```

}

What about an configurable version string that you could input in the config file to override the default when a plugin is loaded.

i.e. something like

plugin_opts citizens.jar {

Bukkit_ver="1.4.5 bukkit build"
Debug_output=true
ect...

}

**Comment by keepcalm** [comment]
No, that can't happen since the functions which are being run to get this information don't get told what's calling them. Sorry.

**Comment by Mastergalen** [comment]
Wait, so why can't 

```
 private static final String COMPATIBLE_MC_VERSION = "1.4.5";

    String mcVersion = Util.getMinecraftVersion();
    compatible = mcVersion.startsWith(COMPATIBLE_MC_VERSION);
    if (!compatible) {
        Messaging.severeTr(Messages.CITIZENS_INCOMPATIBLE, getDescription().getVersion(), mcVersion);
        getServer().getPluginManager().disablePlugin(this);
        return;
```

just be removed and the port is done?

**Comment by SpoonsJTD** [comment]
Maybe ask Citizens author to make the dependency check configurable so it can be disabled?

**Comment by minecrafter** [comment]
The check can't be disabled and everything done with. Even if was done, you would still need to implement net.minecraft.server.\* and org.bukkit.craftbukkit.\* classes.

**Comment by Mastergalen** [comment]
I've created an issue on http://issues.citizensnpcs.com/browse/CITIZENS-402

**Comment by Mastergalen** [comment]
They've added an option in the config to disable the version check:

http://issues.citizensnpcs.com/browse/CITIZENS-402#comment-12449

**Comment by zuch0698o** [comment]
so citizens newest dev version will boot up and let us adjust the config. issue i get now is that citizens is dependent on guava 10 not 12 i know keepcalm's bukkit forge is built around 12 is there anyway to code citizens manually or can guava 10 be added as a support option to bukkitforge?

sry for newb question

**Comment by SpoonsJTD** [comment]
This issue is resolved by Citizen config to disable version check. If you have another issue, search to make sure it hasn't already been reported. If not, create a new issue.
