### ISSUE TITLE
Blockbreak/snakeyaml Issue (Cancelled Spam in console)

### ISSUE THREAD

**Issue by lisim** [keepcalm/BukkitForge#73]
http://pastebin.com/33hLtAtY

On load or what seems call of the block break this issue is caused, have not tried other block logging plugins but GriefPrevintion so far will test more

On Build 21 from Jenkins currently newest

**Comment by keepcalm** [comment]
The snakeyaml part is intended as a part of bukkit - it warns authors of plugins that functionality they are using may be removed.
