### ISSUE TITLE
Logblock Active, Wand Does Nothing

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#75]
Assuming this might be in relation to worldedit? The issue of the wand tool not working on right click or spawning it with the /lb tool command. 

http://pastebin.com/JhBFtab5

When I right click with the tool, it doesn't show any information, not even an empty report like it should. I can see why though there is no info given the error.

**Comment by keepcalm** [comment]
That is a fine example of several errors occuring in one short section of code. I'll fix the errors, and I'll work on the item-giving bug as well.
