### ISSUE TITLE
[Logblock] Issues

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#76]
Still does not record placing. Also does not record modded items. 

01.01 03:37:41 [Server] INFO ... 22 more
01.01 03:37:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
01.01 03:37:41 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:601)
01.01 03:37:41 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01.01 03:37:41 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
01.01 03:37:41 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01.01 03:37:41 [Server] INFO at de.diddiz.LogBlock.listeners.BlockBreakLogging.onBlockBreak(BlockBreakLogging.java:39)
01.01 03:37:41 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.block.BukkitBlock.getState(BukkitBlock.java:229)
01.01 03:37:41 [Server] INFO Caused by: java.lang.NullPointerException
01.01 03:37:41 [Server] INFO at fy.run(SourceFile:849)
01.01 03:37:41 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
01.01 03:37:41 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
01.01 03:37:41 [Server] INFO at ho.r(DedicatedServer.java:270)
01.01 03:37:41 [Server] INFO at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
01.01 03:37:41 [Server] INFO at ht.b(SourceFile:30)
01.01 03:37:41 [Server] INFO at iw.b(NetworkListenThread.java:57)
01.01 03:37:41 [Server] INFO at iv.d(NetServerHandler.java:136)
01.01 03:37:41 [Server] INFO at cg.b(TcpConnection.java:454)
01.01 03:37:41 [Server] INFO at ei.a(SourceFile:46)
01.01 03:37:41 [Server] INFO at iv.a(NetServerHandler.java:514)
01.01 03:37:41 [Server] INFO at ir.a(ItemInWorldManager.java:237)
01.01 03:37:41 [Server] INFO at ir.b(ItemInWorldManager.java:330)
01.01 03:37:41 [Server] INFO at ir.d(ItemInWorldManager.java:271)
01.01 03:37:41 [Server] INFO at keepcalm.mods.blockbreak.EventFactory.onBlockHarvested(EventFactory.java:12)
01.01 03:37:41 [Server] INFO at net.minecraftforge.event.EventBus.post(EventBus.java:103)
01.01 03:37:41 [Server] INFO at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
01.01 03:37:41 [Server] INFO at net.minecraftforge.event.ASMEventHandler_78_BlockBreakEventHandler_onBlockBreak_PlayerBreakBlockEvent.invoke(.dynamic)
01.01 03:37:41 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.BlockBreakEventHandler.onBlockBreak(BlockBreakEventHandler.java:24)
01.01 03:37:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
01.01 03:37:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:480)
01.01 03:37:41 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
01.01 03:37:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
01.01 03:37:41 [Server] INFO org.bukkit.event.EventException
01.01 03:37:41 [Server] SEVERE Could not pass event BlockBreakEvent to LogBlock v1.61
01.01 03:37:33 [Server] INFO Giving xKillerbees 1 of Industrial Sawmill
01.01 03:35:49 [Server] INFO at fy.run(SourceFile:849)
01.01 03:35:49 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
01.01 03:35:49 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
01.01 03:35:49 [Server] INFO at ho.r(DedicatedServer.java:270)
01.01 03:35:49 [Server] INFO at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
01.01 03:35:49 [Server] INFO at ht.b(SourceFile:30)
01.01 03:35:49 [Server] INFO at iw.b(NetworkListenThread.java:57)
01.01 03:35:49 [Server] INFO at iv.d(NetServerHandler.java:136)
01.01 03:35:49 [Server] INFO at cg.b(TcpConnection.java:454)
01.01 03:35:49 [Server] INFO at cu.a(SourceFile:44)
01.01 03:35:49 [Server] INFO at iv.a(NetServerHandler.java:734)
01.01 03:35:49 [Server] INFO at iv.d(NetServerHandler.java:768)
01.01 03:35:49 [Server] INFO at x.a(CommandHandler.java:82)
01.01 03:35:49 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
01.01 03:35:49 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
01.01 03:35:49 [Server] INFO at de.diddiz.LogBlock.CommandsHandler.onCommand(CommandsHandler.java:144)
01.01 03:35:49 [Server] INFO java.lang.NullPointerException
01.01 03:35:49 [Server] WARNING Exception in commands handler:

**Comment by keepcalm** [comment]
When you say ''does not record modded items'  do you mean it doesn't record, for example marble being placed/broken or it doesn't record deployers placing blocks?

**Comment by xKillerbees** [comment]
Placing or breaking modded items. Like placing a piece of marble.

**Comment by keepcalm** [comment]
Strange... I might get BC setup in my mcp so i can play around with this...

**Comment by shakey2** [comment]
Yeah I'm having the exact same problem, no modded items are being logged, just vanilla stuff. Also it only works for block destruction, if I break a vanilla block it records it but if I place a vanilla block it does not record it.

**Comment by keepcalm** [comment]
yes, I know about the lack of place, but mod items not working is weird...

**Comment by xKillerbees** [comment]
So placing and breaking vanilla blocks work now. Just not any modded items. This is the error from placing a steam engine. 

http://pastebin.com/CpbcQDbG

If I break it. 

http://pastebin.com/Nd0XX1tq

**Comment by keepcalm** [comment]
Try with build 40, I was making some stupid assumptions...

**Comment by xKillerbees** [comment]
When I try to right click with the logblock tool to check changes on that location. 

http://pastebin.com/DHZBj4hJ

When I placed an item

http://pastebin.com/3NZaFVde

It does now record modded items WITHOUT a damage value. 

Marble is 253 and it records that. 

A block breaker is 763:1 and it does not record me placing it.

**Comment by keepcalm** [comment]
I remember when I played with WE on 1.2.5 I has a similar problem - it would loose all metadata and paste marble instead of marble brick. Does this work on normal bukkit? Placing blocks with damage values (aside from wool)?

**Comment by xKillerbees** [comment]
On my 1.2.5 mcpc server works fine to paste modded items. Including logblock recording

**Comment by keepcalm** [comment]
Ok. I'll see what MCPC does.

**Comment by xKillerbees** [comment]
I'm pretty sure the worldedit fix was done by the author, not MCPC. Logging of modded items though I do not know.

**Comment by lisim** [comment]
Hasnt he moved the mod to forge all together?

**Comment by xKillerbees** [comment]
That hasn't been updated in 2 months. Have my doubts it's ready.

**Comment by shakey2** [comment]
I'm on build 53 and the only mod block that it seems to be recording is marble. I tried batbox which is 608 with no metadamage and it didn't record it.

**Comment by SpoonsJTD** [comment]
Please try this with latest forge build and latest Logblock build.

**Comment by Tampa** [comment]
Just tried LogBlock on my server and i can confirm its not logging most of the blocks, but the ones inside the 256 range that vanilla is in. It simply needs 4096 blocks integrated or something.
