### ISSUE TITLE
Worldedit Set

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#86]
Did a small region. Then //set 1 and it spit out this.

02.01 02:15:22 [Server] INFO    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
02.01 02:15:22 [Server] INFO    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
02.01 02:15:22 [Server] INFO    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
02.01 02:15:22 [Server] INFO    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
02.01 02:15:22 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.Block
02.01 02:15:22 [Server] INFO    at fy.run(SourceFile:849)
02.01 02:15:22 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
02.01 02:15:22 [Server] INFO    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
02.01 02:15:22 [Server] INFO    at ho.r(DedicatedServer.java:270)
02.01 02:15:22 [Server] INFO    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
02.01 02:15:22 [Server] INFO    at ht.b(SourceFile:30)
02.01 02:15:22 [Server] INFO    at iw.b(NetworkListenThread.java:57)
02.01 02:15:22 [Server] INFO    at iv.d(NetServerHandler.java:136)
02.01 02:15:22 [Server] INFO    at cg.b(TcpConnection.java:454)
02.01 02:15:22 [Server] INFO    at cu.a(SourceFile:44)
02.01 02:15:22 [Server] INFO    at iv.a(NetServerHandler.java:734)
02.01 02:15:22 [Server] INFO    at iv.d(NetServerHandler.java:768)
02.01 02:15:22 [Server] INFO    at x.a(CommandHandler.java:82)
02.01 02:15:22 [Server] INFO    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
02.01 02:15:22 [Server] INFO    at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52)
02.01 02:15:22 [Server] INFO    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:197)
02.01 02:15:22 [Server] INFO    at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1339)
02.01 02:15:22 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:425)
02.01 02:15:22 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:509)
02.01 02:15:22 [Server] INFO    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:172)
02.01 02:15:22 [Server] INFO    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:241)
02.01 02:15:22 [Server] INFO    at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:522)
02.01 02:15:22 [Server] INFO    at java.lang.reflect.Method.invoke(Method.java:601)
02.01 02:15:22 [Server] INFO    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02.01 02:15:22 [Server] INFO    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
02.01 02:15:22 [Server] INFO    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02.01 02:15:22 [Server] INFO    at com.sk89q.worldedit.commands.RegionCommands.set(RegionCommands.java:74)
02.01 02:15:22 [Server] INFO    at com.sk89q.worldedit.WorldEdit.getBlockPattern(WorldEdit.java:608)
02.01 02:15:22 [Server] INFO    at com.sk89q.worldedit.WorldEdit.getBlock(WorldEdit.java:549)
02.01 02:15:22 [Server] INFO    at com.sk89q.worldedit.WorldEdit.getBlock(WorldEdit.java:355)
02.01 02:15:22 [Server] INFO    at com.sk89q.worldedit.WorldEdit.getBlock(WorldEdit.java:414)
02.01 02:15:22 [Server] INFO    at com.sk89q.worldedit.bukkit.BukkitWorld.isValidBlockType(BukkitWorld.java:872)
02.01 02:15:22 [Server] INFO java.lang.NoClassDefFoundError: net/minecraft/server/Block

**Comment by keepcalm** [comment]
Use the ported one. I should make that clearer, sorry :P

**Comment by xKillerbees** [comment]
Oh derp, I was sure I was using your port. I for some reason had the original one in there too.
