### ISSUE TITLE
PermissionsEx: No access even with perms (Fixed)

### ISSUE THREAD

**Issue by TempestCraft** [keepcalm/BukkitForge#91]
My admins have the permission of '*' and they still cant use commands such as /help

**Comment by Manawyrm** [comment]
Works fine here. I think you did some configuration wrong...

**Comment by TempestCraft** [comment]
this is how my permissions look like (this is from my one from my old server so it has some permissions that are not needed anymore)

http://pastie.org/private/hzomol7g3turn08yu9vxba

**Comment by lisim** [comment]
that would best be in a pastebin link simply as yamal is sensitive as hell you might have a tab somehwere lol

**Comment by Manawyrm** [comment]
I think (at the current development state) you should NOT use any old configuration files.
Start with a fresh config. PEx works fine here...

**Comment by TempestCraft** [comment]
I did a fresh start and this still happens

This is the text that it says when I try to use /help for example, also ops are only allowed to use commands
You do not have access to that command.
You do not have permission to use this command
